### PR TITLE
Added support for TS0601 CO2 NIDR _TZE200_ogkdpgy2

### PR DESCRIPTION
**Pull request by JeroenVanOort**
I added support for the Tuya TS0601 CO2 NIDR _TZE200_ogkdpgy2. Works using custom quirks in HomeAssistant.

I made an issue before:
- Fix: #1646

### CODE REVIEW

**Comment by javicalle** [comment]
Thanks for your contribution.
Can you edit the first post and tag the issue like this?:
```
I made an issue before:
- Fix: #1646
```

**Review by javicalle — APPROVED** [review]
LGTM

**Comment by Boppie1976** [comment]
Hi Jeroen,

I have the same sensor, but when I add it to Home Assistant it is recognised, but there are no sensors added? How did you get it to work?

Greetings, Bob.

**Comment by javicalle** [comment]
The PR is not included yet in the latest HA version.
Probably it will go in the v2022.11 .

**Comment by Boppie1976** [comment]
Ah! That is great!  I'll wait a little longer 😉 Greetings Bob.

**Comment by Boppie1976** [comment]
With the last update it started working! Thanks alot!
Greetings Bob.

**Pull request merged**
