### PR TITLE
Added quirk for TuyaSmart TS0044 Remote Control

### PR DESCRIPTION
**Pull request by dumpfheimer**
Added support for TuyaSmart TS0044 remote control

Fixes https://github.com/zigpy/zha-device-handlers/issues/525

Please bare with me, this is my first pull request ;-)

### CODE REVIEW

**Comment by tube0013** [comment]
It may make sense to make the tuyaSmartRemote class in the __init__.py so it can be imported into other quirks, there are a bunch of tuya remotes that this will likely work - they just have a different number of buttons.

**Comment by dumpfheimer** [comment]
Not quite sure what broke the tests, but is this in general what you meant? 
https://github.com/dumpfheimer/zha-device-handlers/commit/40d11dbff2362f5fbf7527c0b553869b33b879c7

**Comment by tube0013** [comment]
I think so but will let the devs chime in with their opinions. I know a little bit and saw this as I have the 3 button and realized it would work with the same code so figured it would be wise to make it reusable.

**Comment by dumpfheimer** [comment]
agreed! do you have a device signature of the 3 button remote?

**Comment by tube0013** [comment]
Yes, I is in #595 I also linked to the other issues with devices that look similar there.

**Comment by dmulcahey** [comment]
@dumpfheimer welcome to quirks and thanks for the contribution! You need to rebase this PR because there are conflicts after merging some thermostat support. Let me know when you have some time and I can help you. My handle is the same on discord if you wanna ping me when you have free time. I can help you rebase and we can look at the tests.

**Comment by dumpfheimer** [comment]
okay, so I think I might have manged to rebase it, but the build isn't triggering automatically, like it did before. Not sure why?

**Comment by oxamafia** [comment]
Hi

Can you also fix [#505 ](url) please ?

Thank you for your precious help

**Comment by dumpfheimer** [comment]
@dmulcahey do you have a police for these situations? Should I rather guess and check in the configurations for the other remotes (I do not know for sure if they have the same quirks) or should someone with such a device adapt the TS0044 implementation?

**Comment by dmulcahey** [comment]
> okay, so I think I might have manged to rebase it, but the build isn't triggering automatically, like it did before. Not sure why?

You still have conflicts so the rebase did not work.

**Comment by dumpfheimer** [comment]
@dmulcahey not sure what happened, again..
I did not close the pull request purposely =/

**Comment by dumpfheimer** [comment]
giving this up. created a new repo and new pull request: https://github.com/zigpy/zha-device-handlers/pull/608

**Pull request closed without merging**
