### PR TITLE
Sort README.md list of device manufacturers in alphabetical order

### PR DESCRIPTION
**Pull request by Hedda**
Sort README.md existing list of device manufacturers supported via quirks in alphabetical order.

I wanted to also sort the devices themself by name under each manufacturer as well, however that can wait until if and when this is approved.

Yes, I have CDO. It's like OCD, but all the letters are in alphabetical order, AS THEY SHOULD BE. ;)

### CODE REVIEW

**Comment by dmulcahey** [comment]
I have been thinking about completely removing this from the readme... @Adminiuga what do you think?

**Comment by Adminiuga** [comment]
I think we should have a list, but it shouldn't be worded as "supported", cause I think some people think if there isnt a quirk, then the device won't work with ZHA.
We just should have an automatically generated list of vendors and models and corresponding quirks,.

**Comment by Hedda** [comment]
OK so I changed the phrasing a little regarding "supported hardware". Probably should be clarified further but maybe good for now?

**Comment by dmulcahey** [comment]
I think we are gonna close this in favor of something dymnamically generated as I agree with @Adminiuga comment above: "We just should have an automatically generated list of vendors and models and corresponding quirks,."

**Comment by Hedda** [comment]
OK then submitted https://github.com/zigpy/zha-device-handlers/pull/470 for that one line that mentions "supported hardware".

**Pull request closed without merging**
