### PR TITLE
Add support TS011F _TZ3000_3zofvcaa ZTB242

### LINKED ISSUE #1610: [Device Support Request] TS011F _TZ3000_3zofvcaa Zemismart Zigbee Smart Wall Socket ZTB242 (2 AC plugs + 1 USB type A + 1 USB type C)
**Is your feature request related to a problem? Please describe.**
Device is detected and reports status OK when the command is made from the device itself.
When the command is made from the HA, it triggers all endpoints at once.

**Describe the solution you'd like**
Add support for sending commands from HA for each endpoint separately.

<details>

<summary>Device signature</summary>

```yaml
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress|RxOnWhenIdle|MainsPowered|FullFunctionDevice: 142>, manufacturer_code=4417, maximum_buffer_size=66, maximum_incoming_transfer_size=66, server_mask=10752, maximum_outgoing_transfer_size=66, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x010a",
      "in_clusters": [
        "0x0000",
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006",
        "0xe000",
        "0xe001"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    },
    "2": {
      "profile_id": 260,
      "device_type": "0x010a",
      "in_clusters": [
        "0x0004",
        "0x0005",
        "0x0006",
        "0xe001"
      ],
      "out_clusters": []
    },
    "3": {
      "profile_id": 260,
      "device_type": "0x010a",
      "in_clusters": [
        "0x0004",
        "0x0005",
        "0x0006",
        "0xe001"
      ],
      "out_clusters": []
    },
    "4": {
      "profile_id": 260,
      "device_type": "0x010a",
      "in_clusters": [
        "0x0004",
        "0x0005",
        "0x0006",
        "0xe001"
      ],
      "out_clusters": []
    },
    "242": {
      "profile_id": 41440,
      "device_type": "0x0061",
      "in_clusters": [],
      "out_clusters": [
        "0x0021"
      ]
    }
  },
  "manufacturer": "_TZ3000_3zofvcaa",
  "model": "TS011F",
  "class": "zigpy.device.Device"
}
```

</details>

<details>

<summary>Diagnostic information</summary>

```yaml
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.5.5",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.9.9",
    "docker": true,
    "arch": "aarch64",
    "timezone": "America/Recife",
    "os_name": "Linux",
    "os_version": "5.15.32-v8",
    "supervisor": "2022.05.3",
    "host_os": "Home Assistant OS 8.0",
    "docker_version": "20.10.14",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "zha_toolkit": {
      "version": "v0.8.8",
      "requirements": []
    },
    "hacs": {
      "version": "1.24.5",
      "requirements": [
        "aiogithubapi>=21.11.0"
      ]
    },
    "multiscrape": {
      "version": "6.2.0",
      "requirements": [
        "lxml",
        "beautifulsoup4==4.10.0"
      ]
    },
    "alexa_media": {
      "version": "3.11.3",
      "requirements": [
        "alexapy==1.25.5",
        "packaging>=20.3",
        "wrapt>=1.12.1"
      ]
    },
    "smartir": {
      "version": "1.17.6",
      "requirements": [
        "aiofiles==0.6.0"
      ]
    },
    "climate_ip": {
      "version": "3.5.2",
      "requirements": [
        "requests>=2.21.0",
        "xmljson>=0.2.0"
      ]
    }
  },
  "integration_manifest": {
    "domain": "zha",
    "name": "Zigbee Home Automation",
    "config_flow": true,
    "documentation": "https://www.home-assistant.io/integrations/zha",
    "requirements": [
      "bellows==0.29.0",
      "pyserial==3.5",
      "pyserial-asyncio==0.6",
      "zha-quirks==0.0.73",
      "zigpy-deconz==0.16.0",
      "zigpy==0.45.1",
      "zigpy-xbee==0.14.0",
      "zigpy-zigate==0.7.4",
      "zigpy-znp==0.7.0"
    ],
    "usb": [
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*2652*",
        "known_devices": [
          "slae.sh cc2652rb stick"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*zigstar*",
        "known_devices": [
          "ZigStar Coordinators"
        ]
      },
      {
        "vid": "1CF1",
        "pid": "0030",
        "description": "*conbee*",
        "known_devices": [
          "Conbee II"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8A2A",
        "description": "*zigbee*",
        "known_devices": [
          "Nortek HUSBZB-1"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8B34",
        "description": "*bv 2010/10*",
        "known_devices": [
          "Bitron Video AV2010/10"
        ]
      }
    ],
    "codeowners": [
      "@dmulcahey",
      "@adminiuga"
    ],
    "zeroconf": [
      {
        "type": "_esphomelib._tcp.local.",
        "name": "tube*"
      }
    ],
    "after_dependencies": [
      "usb",
      "zeroconf"
    ],
    "iot_class": "local_polling",
    "loggers": [
      "aiosqlite",
      "bellows",
      "crccheck",
      "pure_pcapy3",
      "zhaquirks",
      "zigpy",
      "zigpy_deconz",
      "zigpy_xbee",
      "zigpy_zigate",
      "zigpy_znp"
    ],
    "is_built_in": true
  },
  "data": {
    "ieee": "**REDACTED**",
    "nwk": 22411,
    "manufacturer": "_TZ3000_3zofvcaa",
    "model": "TS011F",
    "name": "_TZ3000_3zofvcaa TS011F",
    "quirk_applied": false,
    "quirk_class": "zigpy.device.Device",
    "manufacturer_code": 4417,
    "power_source": "Mains",
    "lqi": 255,
    "rssi": -81,
    "last_seen": "2022-06-06T16:31:38",
    "available": true,
    "device_type": "Router",
    "signature": {
      "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress|RxOnWhenIdle|MainsPowered|FullFunctionDevice: 142>, manufacturer_code=4417, maximum_buffer_size=66, maximum_incoming_transfer_size=66, server_mask=10752, maximum_outgoing_transfer_size=66, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
      "endpoints": {
        "1": {
          "profile_id": 260,
          "device_type": "0x010a",
          "in_clusters": [
            "0x0000",
            "0x0003",
            "0x0004",
            "0x0005",
            "0x0006",
            "0xe000",
            "0xe001"
          ],
          "out_clusters": [
            "0x000a",
            "0x0019"
          ]
        },
        "2": {
          "profile_id": 260,
          "device_type": "0x010a",
          "in_clusters": [
            "0x0004",
            "0x0005",
            "0x0006",
            "0xe001"
          ],
          "out_clusters": []
        },
        "3": {
          "profile_id": 260,
          "device_type": "0x010a",
          "in_clusters": [
            "0x0004",
            "0x0005",
            "0x0006",
            "0xe001"
          ],
          "out_clusters": []
        },
        "4": {
          "profile_id": 260,
          "device_type": "0x010a",
          "in_clusters": [
            "0x0004",
            "0x0005",
            "0x0006",
            "0xe001"
          ],
          "out_clusters": []
        },
        "242": {
          "profile_id": 41440,
          "device_type": "0x0061",
          "in_clusters": [],
          "out_clusters": [
            "0x0021"
          ]
        }
      }
    },
    "entities": [
      {
        "entity_id": "button.tz3000_3zofvcaa_ts011f_099182c5_identify",
        "name": "_TZ3000_3zofvcaa TS011F"
      },
      {
        "entity_id": "switch.tz3000_3zofvcaa_ts011f_099182c5_on_off",
        "name": "_TZ3000_3zofvcaa TS011F"
      },
      {
        "entity_id": "switch.tz3000_3zofvcaa_ts011f_099182c5_on_off_2",
        "name": "_TZ3000_3zofvcaa TS011F"
      },
      {
        "entity_id": "switch.tz3000_3zofvcaa_ts011f_099182c5_on_off_3",
        "name": "_TZ3000_3zofvcaa TS011F"
      },
      {
        "entity_id": "switch.tz3000_3zofvcaa_ts011f_099182c5_on_off_4",
        "name": "_TZ3000_3zofvcaa TS011F"
      }
    ],
    "neighbors": [],
    "endpoint_names": [
      {
        "name": "ON_OFF_PLUG_IN_UNIT"
      },
      {
        "name": "ON_OFF_PLUG_IN_UNIT"
      },
      {
        "name": "ON_OFF_PLUG_IN_UNIT"
      },
      {
        "name": "ON_OFF_PLUG_IN_UNIT"
      },
      {
        "name": "unknown 97 device_type of 0xa1e0 profile id"
      }
    ],
    "user_given_name": null,
    "device_reg_id": "273f9b4d5dfea30117bf909a4287836d",
    "area_id": null
  }
}
```

</details>

<details>
<summary>Additional logs</summary>

```
From device (I only pressed to turn ON endpoint 4):

2022-06-06 17:11:51 DEBUG (MainThread) [zigpy.zcl] [0x578B:4:0x0006] Received ZCL frame: b'\x08\xd3\n\x00\x00\x10\x01'
2022-06-06 17:11:51 DEBUG (MainThread) [zigpy.zcl] [0x578B:4:0x0006] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.GLOBAL_COMMAND: 0>, is_manufacturer_specific=0, is_reply=1, disable_default_response=0, reserved=0, *is_cluster=False, *is_general=True), tsn=211, command_id=10, *is_reply=True)
2022-06-06 17:11:51 DEBUG (MainThread) [zigpy.zcl] [0x578B:4:0x0006] Decoded ZCL frame: OnOff:Report_Attributes(attribute_reports=[Attribute(attrid=0x0000, value=TypeValue(type=Bool, value=<Bool.true: 1>))])
2022-06-06 17:11:51 DEBUG (MainThread) [zigpy.zcl] [0x578B:4:0x0006] Received command 0x0A (TSN 211): Report_Attributes(attribute_reports=[Attribute(attrid=0x0000, value=TypeValue(type=Bool, value=<Bool.true: 1>))])
2022-06-06 17:11:51 DEBUG (MainThread) [zigpy.zcl] [0x578B:4:0x0006] Attribute report received: on_off=<Bool.true: 1>
2022-06-06 17:11:51 DEBUG (MainThread) [zigpy.zcl] [0x578B:4:0x0006] Sending reply header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.GLOBAL_COMMAND: 0>, is_manufacturer_specific=False, is_reply=1, disable_default_response=1, reserved=0, *is_cluster=False, *is_general=True), tsn=211, command_id=<GeneralCommand.Default_Response: 11>, *is_reply=True)
2022-06-06 17:11:51 DEBUG (MainThread) [zigpy.zcl] [0x578B:4:0x0006] Sending reply: Default_Response(command_id=10, status=<Status.SUCCESS: 0>)
2022-06-06 17:11:51 DEBUG (MainThread) [zigpy.zcl] [0x578B:4:0x0006] Received ZCL frame: b'\x08\xd3\n\x00\x00\x10\x01'
2022-06-06 17:11:51 DEBUG (MainThread) [zigpy.zcl] [0x578B:4:0x0006] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.GLOBAL_COMMAND: 0>, is_manufacturer_specific=0, is_reply=1, disable_default_response=0, reserved=0, *is_cluster=False, *is_general=True), tsn=211, command_id=10, *is_reply=True)
2022-06-06 17:11:51 DEBUG (MainThread) [zigpy.zcl] [0x578B:4:0x0006] Decoded ZCL frame: OnOff:Report_Attributes(attribute_reports=[Attribute(attrid=0x0000, value=TypeValue(type=Bool, value=<Bool.true: 1>))])
2022-06-06 17:11:51 DEBUG (MainThread) [zigpy.zcl] [0x578B:4:0x0006] Received command 0x0A (TSN 211): Report_Attributes(attribute_reports=[Attribute(attrid=0x0000, value=TypeValue(type=Bool, value=<Bool.true: 1>))])
2022-06-06 17:11:51 DEBUG (MainThread) [zigpy.zcl] [0x578B:4:0x0006] Attribute report received: on_off=<Bool.true: 1>
2022-06-06 17:11:51 DEBUG (MainThread) [zigpy.zcl] [0x578B:4:0x0006] Sending reply header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.GLOBAL_COMMAND: 0>, is_manufacturer_specific=False, is_reply=1, disable_default_response=1, reserved=0, *is_cluster=False, *is_general=True), tsn=211, command_id=<GeneralCommand.Default_Response: 11>, *is_reply=True)
2022-06-06 17:11:51 DEBUG (MainThread) [zigpy.zcl] [0x578B:4:0x0006] Sending reply: Default_Response(command_id=10, status=<Status.SUCCESS: 0>)

From HA (I only pressed to turn OFF endpoint 4):

2022-06-06 17:13:31 DEBUG (MainThread) [zigpy.zcl] [0x578B:4:0x0006] Sending request header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.CLUSTER_COMMAND: 1>, is_manufacturer_specific=False, is_reply=0, disable_default_response=0, reserved=0, *is_cluster=True, *is_general=False), tsn=223, command_id=0, *is_reply=False)
2022-06-06 17:13:31 DEBUG (MainThread) [zigpy.zcl] [0x578B:4:0x0006] Sending request: off()
2022-06-06 17:13:31 DEBUG (MainThread) [zigpy.zcl] [0x578B:4:0x0006] Received ZCL frame: b'\x18\xdf\x0b\x00\x00'
2022-06-06 17:13:31 DEBUG (MainThread) [zigpy.zcl] [0x578B:4:0x0006] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.GLOBAL_COMMAND: 0>, is_manufacturer_specific=0, is_reply=1, disable_default_response=1, reserved=0, *is_cluster=False, *is_general=True), tsn=223, command_id=11, *is_reply=True)
2022-06-06 17:13:31 DEBUG (MainThread) [zigpy.zcl] [0x578B:4:0x0006] Decoded ZCL frame: OnOff:Default_Response(command_id=0, status=<Status.SUCCESS: 0>)
2022-06-06 17:13:31 DEBUG (MainThread) [zigpy.zcl] [0x578B:1:0x0006] Received ZCL frame: b'\x18\xd4\n\x00\x00\x10\x00'
2022-06-06 17:13:31 DEBUG (MainThread) [zigpy.zcl] [0x578B:1:0x0006] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.GLOBAL_COMMAND: 0>, is_manufacturer_specific=0, is_reply=1, disable_default_response=1, reserved=0, *is_cluster=False, *is_general=True), tsn=212, command_id=10, *is_reply=True)
2022-06-06 17:13:31 DEBUG (MainThread) [zigpy.zcl] [0x578B:1:0x0006] Decoded ZCL frame: OnOff:Report_Attributes(attribute_reports=[Attribute(attrid=0x0000, value=TypeValue(type=Bool, value=<Bool.false: 0>))])
2022-06-06 17:13:31 DEBUG (MainThread) [zigpy.zcl] [0x578B:1:0x0006] Received command 0x0A (TSN 212): Report_Attributes(attribute_reports=[Attribute(attrid=0x0000, value=TypeValue(type=Bool, value=<Bool.false: 0>))])
2022-06-06 17:13:31 DEBUG (MainThread) [zigpy.zcl] [0x578B:1:0x0006] Attribute report received: on_off=<Bool.false: 0>
2022-06-06 17:13:31 DEBUG (MainThread) [zigpy.zcl] [0x578B:2:0x0006] Received ZCL frame: b'\x18\xd5\n\x00\x00\x10\x00'
2022-06-06 17:13:31 DEBUG (MainThread) [zigpy.zcl] [0x578B:2:0x0006] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.GLOBAL_COMMAND: 0>, is_manufacturer_specific=0, is_reply=1, disable_default_response=1, reserved=0, *is_cluster=False, *is_general=True), tsn=213, command_id=10, *is_reply=True)
2022-06-06 17:13:31 DEBUG (MainThread) [zigpy.zcl] [0x578B:2:0x0006] Decoded ZCL frame: OnOff:Report_Attributes(attribute_reports=[Attribute(attrid=0x0000, value=TypeValue(type=Bool, value=<Bool.false: 0>))])
2022-06-06 17:13:31 DEBUG (MainThread) [zigpy.zcl] [0x578B:2:0x0006] Received command 0x0A (TSN 213): Report_Attributes(attribute_reports=[Attribute(attrid=0x0000, value=TypeValue(type=Bool, value=<Bool.false: 0>))])
2022-06-06 17:13:31 DEBUG (MainThread) [zigpy.zcl] [0x578B:2:0x0006] Attribute report received: on_off=<Bool.false: 0>
2022-06-06 17:13:31 DEBUG (MainThread) [homeassistant.components.zha.core.channels.base] [0x578B:4:0x0006]: executed 'off' command with args: '()' kwargs: '{}' result: Default_Response(command_id=0, status=<Status.SUCCESS: 0>)
2022-06-06 17:13:31 DEBUG (MainThread) [zigpy.zcl] [0x578B:3:0x0006] Received ZCL frame: b'\x18\xd6\n\x00\x00\x10\x00'
2022-06-06 17:13:31 DEBUG (MainThread) [zigpy.zcl] [0x578B:3:0x0006] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.GLOBAL_COMMAND: 0>, is_manufacturer_specific=0, is_reply=1, disable_default_response=1, reserved=0, *is_cluster=False, *is_general=True), tsn=214, command_id=10, *is_reply=True)
2022-06-06 17:13:31 DEBUG (MainThread) [zigpy.zcl] [0x578B:3:0x0006] Decoded ZCL frame: OnOff:Report_Attributes(attribute_reports=[Attribute(attrid=0x0000, value=TypeValue(type=Bool, value=<Bool.false: 0>))])
2022-06-06 17:13:31 DEBUG (MainThread) [zigpy.zcl] [0x578B:3:0x0006] Received command 0x0A (TSN 214): Report_Attributes(attribute_reports=[Attribute(attrid=0x0000, value=TypeValue(type=Bool, value=<Bool.false: 0>))])
2022-06-06 17:13:31 DEBUG (MainThread) [zigpy.zcl] [0x578B:3:0x0006] Attribute report received: on_off=<Bool.false: 0>
2022-06-06 17:13:31 DEBUG (MainThread) [zigpy.zcl] [0x578B:4:0x0006] Received ZCL frame: b'\x18\xd7\n\x00\x00\x10\x00'
2022-06-06 17:13:31 DEBUG (MainThread) [zigpy.zcl] [0x578B:4:0x0006] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.GLOBAL_COMMAND: 0>, is_manufacturer_specific=0, is_reply=1, disable_default_response=1, reserved=0, *is_cluster=False, *is_general=True), tsn=215, command_id=10, *is_reply=True)
2022-06-06 17:13:32 DEBUG (MainThread) [zigpy.zcl] [0x578B:4:0x0006] Decoded ZCL frame: OnOff:Report_Attributes(attribute_reports=[Attribute(attrid=0x0000, value=TypeValue(type=Bool, value=<Bool.false: 0>))])
2022-06-06 17:13:32 DEBUG (MainThread) [zigpy.zcl] [0x578B:4:0x0006] Received command 0x0A (TSN 215): Report_Attributes(attribute_reports=[Attribute(attrid=0x0000, value=TypeValue(type=Bool, value=<Bool.false: 0>))])
2022-06-06 17:13:32 DEBUG (MainThread) [zigpy.zcl] [0x578B:4:0x0006] Attribute report received: on_off=<Bool.false: 0>
```

</details>

**Additional context**
Does anyone have any suggestion where I could start ?
I have already copied and modified some examples from https://github.com/zigpy/zha-device-handlers/blob/dev/zhaquirks/tuya/ts011f_plug.py and https://github.com/zigpy/zha-device-handlers/blob/dev/zhaquirks/tuya/ts011f_switch.py but no success.
VideoEditor_20220606_052113_1

When paired with Smart Life, all 4 endpoints work independently.

### PR DESCRIPTION
**Pull request by w35l3y**
Zemismart Zigbee Smart Wall Socket (2 AC plugs + 1 USB type A + 1 USB type C)

Fixes #1610

### CODE REVIEW

**Comment by w35l3y** [comment]
> Is the `replacement` part needed? Doesn't seem that the `TuyaZBExternalSwitchTypeCluster` is needed here.
> 
> I believe that your quirk should work without the replacement part. Could you check?

`0xE001 (TuyaZBExternalSwitchTypeCluster)` originally is declared at endpoints 1 to 4, but it only returns something from endpoint 1.
That is the reason I removed them from endpoints 2 to 4.

Also, I added `0x0006 (TuyaZBOnOffAttributeCluster)` to endpoint 1.
I tried adding it to the `signature`, but it didn't work.

If I just remove `replacement`, I receive this:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/zha/__init__.py", line 102, in async_setup_entry
    await zha_gateway.async_initialize()
  File "/usr/src/homeassistant/homeassistant/components/zha/core/gateway.py", line 182, in async_initialize
    self.application_controller = await app_controller_cls.new(
  File "/usr/local/lib/python3.9/site-packages/zigpy/application.py", line 61, in new
    await app._load_db()
  File "/usr/local/lib/python3.9/site-packages/zigpy/application.py", line 53, in _load_db
    await self._dblistener.load()
  File "/usr/local/lib/python3.9/site-packages/zigpy/appdb.py", line 503, in load
    await self._load_unsupported_attributes()
  File "/usr/local/lib/python3.9/site-packages/zigpy/appdb.py", line 554, in _load_unsupported_attributes
    ep = dev.endpoints[endpoint_id]
KeyError: 1
```

**Comment by MattWestb** [comment]
`OnOff.cluster_id,` in signature and `TuyaZBOnOffAttributeCluster` shall working OK.

I  think the system is not liking you was deleting the `OnOff.cluster_id,` /  `TuyaZBOnOffAttributeCluster`  cluster in replacement then it have saved attributes it cant finding on the deleted cluster on the endpoint.

**Comment by w35l3y** [comment]
Just to clarify, the code as is in the PR is working OK fine.

| Endpoint | Cluster | Attribute | Current value | Action taken |
|---|---|---|---|---|
| 1 | 0x0006 | 0x8000 child_lock | Bool.false | Added `TuyaZBOnOffAttributeCluster` to ep 1 |
| 1 | 0x0006 | 0x8001 backlight_mode | SwitchBackLight.Mode_1 | Added `TuyaZBOnOffAttributeCluster` to ep 1 |
| 1 | 0x0006 | 0x8002 power_on_state | PowerOnState.LastState | Added `TuyaZBOnOffAttributeCluster` to ep 1 |
| 1 | 0x0006 | 0x8004 switch_mode | None | Added `TuyaZBOnOffAttributeCluster` to ep 1 (side effect?) |
| 1 | 0xE001 | 0xD030 external_switch_type | ExternalSwitchType.Toggle | Added `TuyaZBExternalSwitchTypeCluster` to ep 1 |
| 2 | 0xE001 | 0xD030 external_switch_type | None | Removed `TuyaZBExternalSwitchTypeCluster` from ep 2 |
| 3 | 0xE001 | 0xD030 external_switch_type | None | Removed `TuyaZBExternalSwitchTypeCluster` from ep 3 |
| 4 | 0xE001 | 0xD030 external_switch_type | None | Removed `TuyaZBExternalSwitchTypeCluster` from ep 4 |

Consider `base` the code that is in the PR...

This is the test result of combinations I did:
| Code | Result |
|---|---|
| base | Works |
| base - `replacement` | Exception |
| base + TuyaZBOnOffAttributeCluster to the `signature` | Didn't recognize quirk |
| base - OnOff from the `signature` + TuyaZBOnOffAttributeCluster to the `signature` | Didn't recognize quirk |

**Comment by MattWestb** [comment]
Have finding one more attribute for the 0xE001 Switch mode cluster:

- 0xD010 Power On Behavior (t.enum8)
  - 0x00 = Off
  - 0x01 = On
  - 0x02 = Last state

Used in Z2M for some TS0004 devices.

**Comment by javicalle** [comment]
My point is: are any of the extra attributes going to be useful for _this device_? If the device can't use them, I would at least consider the option of not taking the extra attributes into account for the final implementation.
It is possible that in the future some new device matches the signature and _does_ use the extra attributes, probably, but it can always be added later.

@w35l3y I would say that the error occurs when restoring the device previous state on the start up (`await app._load_db()`). Could you repeat the test (without the `replacement` part) removing the device first? or repairing after restart?

I want to make it clear that for me there is _no problem_ in the current version, but I would like to know if another solution is possible.

Thanks in advanced.

**Comment by w35l3y** [comment]
> are any of the extra attributes going to be useful for _this device_?

Which extra attributes ?
`child_lock`, `backlight_mode`, `power_on_state` and `external_switch_type` are useful for this device.

> Could you repeat the test (without the `replacement` part) removing the device first?

Result without `replacement`... I removed device and re-paired 3 times just to make sure.
image

**Comment by javicalle** [comment]
> Result without `replacement`... I removed device and re-paired 3 times just to make sure.

Thanks for checking. 🙇🏻 

Maybe the `power_on_state` can modify the device behaviour (device status after power drop).
It's posible to you to modify the attribute value and test?

**Comment by w35l3y** [comment]
Just a side note... I have a scenario that TMS didn't work:
* Tested some commands (TMS is working)
* Removed device
* Removed block `replacement` and saved file
* Restarted HA and paired the device (no entity showed up)
* Returned block `replacement` and saved file
* Restarted HA and entities showed up without doing anything with the device
* Tested some commands (TMS is NOT working)
* Removed device
* Paired device
* Tested some commands (TMS is working again)

Then I did the following tests:

| power_on_state | Endpoints 1-4 Before | Endpoints 1-4 After |
|---|---|---|
| LastState | OFF OFF OFF OFF | OFF OFF OFF OFF |
| LastState | OFF ON OFF ON | OFF ON OFF ON |
| LastState | ON ON ON ON | ON ON ON ON |
| Off | OFF OFF OFF OFF | OFF OFF OFF OFF |
| Off | OFF ON OFF ON | OFF OFF OFF OFF |
| Off | ON ON ON ON | OFF OFF OFF OFF |
| On | OFF OFF OFF OFF | ON ON ON ON |
| On | OFF ON OFF ON | ON ON ON ON |
| On | ON ON ON ON | ON ON ON ON |

**Comment by javicalle** [comment]
So, it seems clear that the `replacement` part is needed, and that at least some of the attributes are useful.

Thanks very much for testing @w35l3y

**Comment by javicalle** [comment]
Sorry, one last thing.

I believe that the replacement for the endpoint 1 must be:
```python
    replacement = {
        ENDPOINTS: {
            1: {
                PROFILE_ID: zha.PROFILE_ID,
                DEVICE_TYPE: zha.DeviceType.ON_OFF_PLUG_IN_UNIT,
                INPUT_CLUSTERS: [
                    Basic.cluster_id,
                    Identify.cluster_id,
                    Groups.cluster_id,
                    Scenes.cluster_id,
                    TuyaZBOnOffAttributeCluster,
                    TuyaZBE000Cluster,
                    TuyaZBExternalSwitchTypeCluster,
                ],
                OUTPUT_CLUSTERS: [Time.cluster_id, Ota.cluster_id],
            },
```

Probably there's no need to change in the rest of endpoins.

**Comment by w35l3y** [comment]
This is the device settings in Smart Life
image
Relay Status = power_on_state
Light Mode = backlight_mode
Child Lock = child_lock

And this the device details in Smart Life
image
There is a fifth endpoint that should work for all endpoints at once, but I don't have the expertise to add it.
I tested adding endpoint 5, but no success.



> I believe that the replacement for the endpoint 1 must be:

It worked.

**Comment by javicalle** [comment]
I had not realized that the device could have a status light 😓 
Then you can control all these properties from the cluster attributes (and the replacement part makes all the sense).


> There is a fifth endpoint that should work for all endpoints at once

I don't remember seeing any implementation like the one you suggest. Maybe it is controlled by a group command but I have no experience in that part.

**Pull request merged**
