### PR TITLE
Fix IKEA five button remote automation triggers

### PR DESCRIPTION
**Pull request by chmielowiec**
For me the following events works. I don't know if ZLL version has same issue.
```
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "00:0d:6f:ff:fe:1d:2b:84",
        "unique_id": "00:0d:6f:ff:fe:1d:2b:84:1:0x0008",
        "endpoint_id": 1,
        "cluster_id": 8,
        "command": "stop",
        "args": []
    },
    "origin": "LOCAL",
    "time_fired": "2020-04-01T06:10:52.237198+00:00",
    "context": {
        "id": "cf6712f5bbfb4154a25556eb6c610b8f",
        "parent_id": null,
        "user_id": null
    }
}

{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "00:0d:6f:ff:fe:1d:2b:84",
        "unique_id": "00:0d:6f:ff:fe:1d:2b:84:1:0x0008",
        "endpoint_id": 1,
        "cluster_id": 8,
        "command": "move",
        "args": [
            1,
            84
        ]
    },
    "origin": "LOCAL",
    "time_fired": "2020-04-01T06:10:51.833328+00:00",
    "context": {
        "id": "704b2a7b0c004782a3549cdf4edc27fb",
        "parent_id": null,
        "user_id": null
    }
}

{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "00:0d:6f:ff:fe:1d:2b:84",
        "unique_id": "00:0d:6f:ff:fe:1d:2b:84:1:0x0008",
        "endpoint_id": 1,
        "cluster_id": 8,
        "command": "stop",
        "args": []
    },
    "origin": "LOCAL",
    "time_fired": "2020-04-01T06:10:50.687511+00:00",
    "context": {
        "id": "8addcedbd9cd4bf1a40af13e438c96b0",
        "parent_id": null,
        "user_id": null
    }
}

{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "00:0d:6f:ff:fe:1d:2b:84",
        "unique_id": "00:0d:6f:ff:fe:1d:2b:84:1:0x0008",
        "endpoint_id": 1,
        "cluster_id": 8,
        "command": "move_with_on_off",
        "args": [
            0,
            84
        ]
    },
    "origin": "LOCAL",
    "time_fired": "2020-04-01T06:10:50.216216+00:00",
    "context": {
        "id": "7a8f43050d7d4063b29201bd95ede3e5",
        "parent_id": null,
        "user_id": null
    }
}
```

### CODE REVIEW

**Comment by dmulcahey** [comment]
whelp I'd have to guess this is a firmware issue here... the one I have sends 83 not 84. We need a proper solution for this we can't just update the values unfortunately.

**Comment by chmielowiec** [comment]
Mine is sw_build_id=2.3.014 with zha profile

**Comment by chmielowiec** [comment]
Also no battery size or quantity info in ZHA.

Logs when I query them manually in ZHA:
battery_quantity: https://paste.ubuntu.com/p/jmrhMj2R6y/
battery_size: https://paste.ubuntu.com/p/7mk6jxzrZW/

**Comment by chmielowiec** [comment]
I got also some warnings `Data remains after deserializing ZCL frame` for dim down button:
https://paste.ubuntu.com/p/HxmKJQbGDC/

**Comment by Adminiuga** [comment]
@dmulcahey  which version is your remote?

**Comment by Adminiuga** [comment]
@dmulcahey the 2.0.314 I have sends broadcasts (if I got the zigbee capture right) but I don't see those incoming on EZSP, although it works fine on ConBee

**Comment by dmulcahey** [comment]
Did they update to ZB 3? A lot of ZB 3 stuff does that if the clusters aren’t bound. I’ll grab the version for mine later.

**Comment by Adminiuga** [comment]
It does report zcl_version 3. Any other way to validate it's zigbee 3
image

And I thought we're binding those clusters, aren't we? Well, maybe not the touch link

**Comment by Adminiuga** [comment]
Correction: version is 2.3.014

**Comment by Adminiuga** [comment]
@dmulcahey the one you have? what sw_build_id does it report and what ZCL Version?
Could we use zcl_version to distinguish between device automations?

**Comment by chmielowiec** [comment]
I have E1524 with sw_build_id=2.3.014 and zcl_version=3

@Adminiuga I will use raw zha_events in my automations, thanks. Didn't know about it.

**Comment by chmielowiec** [comment]
Closing, I use zha_event in automations now.

**Comment by Adminiuga** [comment]
@dmulcahey question remains open if the args would stay the same for the future releases. If yes, then maybe we could get away with different dicts based on zcl_version value.

**Comment by TheJulianJES** [comment]
Same issue here - bought the five button remote today and it has zcl_version: 3, sw_build_id: 2.3.014, app_version: 33, hw_version: 1, stack_version: 98 and sends out "84".
It's the E1810 model.

**Comment by MattWestb** [comment]
E1810 and the E1524 have the same software loaded and using the same OTA files only different data setting in the user data of the flash and slightly modded hardware.

**Comment by dmulcahey** [comment]
Please rebase to pick up the CI change. We swapped from travis to GH Actions. Sorry for the inconvenience.

**Comment by dmulcahey** [comment]
@Adminiuga mine is 1.2.214. I rebased this so CI is all set... what do we want to do here? do we want to do something w/ software build id in quirks?

**Comment by Adminiuga** [comment]
lemme check what's mine is...

**Comment by MattWestb** [comment]
If having one remote paired in ZHA then updating it if its old ZLL and the problem is away and no need doing dula coding :-))

**Comment by Adminiuga** [comment]
What's the node descriptor for yours? I've noticed mine tries to verify the link key, so I assume it's ZB3
```
  "node_descriptor": "NodeDescriptor(byte1=2, byte2=64, mac_capability_flags=128, manufacturer_code=4476, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=0)
  ```

**Comment by MattWestb** [comment]
All IKEA controlling devices is requesting one new TC link key then pairing = Zigbee 3 with expansion of the old motion sensor that is ZLL.

**Comment by Adminiuga** [comment]
> old firmware with version 1.2x and new ZB3 ones is 2.3x

Yep, so by distinguishing by ZB3 vs HA1.2 using the node descriptor, we can indirectly distinguish between updated and not updated ikeas.

**Comment by Adminiuga** [comment]
@dmulcahey so looks like `(self.node_desc.server_mask >> 9) == 22` for ZB3 devices

**Comment by MattWestb** [comment]
One thing but i think its dont have with this to do but still can.
Looks like deCONZ was having problems with the toggle / light reset button that was getting some strange replay from the coordinator and is stopping sending scenes commands.
https://github.com/dresden-elektronik/deconz-rest-plugin/pull/5012

**Comment by bridadan** [comment]
I've got the same issue here. Not a deal breaker for me but I'd be interested in getting this working for the future. Anything I can do to help this along? Happy to help with implementation if need be, though I haven't worked within this project before.

**Comment by MattWestb** [comment]
Then https://github.com/zigpy/zha-device-handlers/pull/1114 is merged, update the firmware to current production and its working then its using the new data and have one own quirk part with fixed device automatons.

For the moment i cant recommending updating the firmware if you is using the remote for searing lights then its loosing group binding but device binding is working OK.

**Comment by puddly** [comment]
@MattWestb should we remove the second parameter entirely from all of the IKEA quirks? @dmulcahey suggested this earlier:

```diff
-{"move_mode": 0, "rate": 84}
+{"move_mode": 0}
```

Unless a device happens to send different commands that only differ by their `rate`, this shouldn't break anything.

**Comment by MattWestb** [comment]
I must testing if its working OK on the current firmware and if its working OK it  shall fixing this firmware setting / version 2.
Other controllers i have not seen this problem only 2 that have different cluster setting or bad device name (Short and OpenClose buttons).

**Comment by MattWestb** [comment]
Was making automatons in HA for dim up and down and its was working OK with the quirks in the update PR.
Changing DA to:
```
         (SHORT_PRESS, DIM_UP): {
            COMMAND: COMMAND_STEP_ON_OFF,
            CLUSTER_ID: 8,
            ENDPOINT_ID: 1,
            PARAMS: {"step_mode": 0},
        },
        (LONG_PRESS, DIM_UP): {
            COMMAND: COMMAND_MOVE_ON_OFF,
            CLUSTER_ID: 8,
            ENDPOINT_ID: 1,
            PARAMS: {"move_mode": 0},
        },
        (SHORT_PRESS, DIM_DOWN): {
            COMMAND: COMMAND_STEP,
            CLUSTER_ID: 8,
            PARAMS: {"step_mode": 1},
        },
        (LONG_PRESS, DIM_DOWN): {
            COMMAND: COMMAND_MOVE,
            CLUSTER_ID: 8,
            ENDPOINT_ID: 1,
            PARAMS: {"move_mode": 1},
        },
```
and the automatons is still working OK after restart of HA with the changes.

We also having one unused stop commands from long press dim up/down but without directions.
Its possible implanting the same as OpenClose is having (with `args` for getting it with direction) or only one stop for both if some one like implanting it.

Our @puddly i can putting this fix in the PR for fixing the last problems that is not being merged and we can closing this issue then it shall working OK if the device is having the same cluster setting and is doing the same with all 3 versions of the device class implanted (i can only testing the current production without distroing  my remote for flashing one old firmware with SWD).

Is that OK ?

**Pull request closed without merging**
