### PR TITLE
Fix instantaneous demand on Schneider Wiser outlets

### PR DESCRIPTION
**Pull request by kosmiq**
Based on the code supplied by krlssn in comment https://github.com/zigpy/zha-device-handlers/issues/1889#issuecomment-1337368444

I'm VERY new to the whole Python world so I feel totally lost when it comes to writing tests and honestly not capable of doing so currently. I'm currently trying to get a dev env setup with Python 3.12 but I get weird errors regarding building wheels and whatnot. I'll see if I can get that running...

## Proposed change
- Add quirks for Schneider Wiser outlets and how metering is calculated

## Additional information
- PR is based on the code attached to this comment: https://github.com/zigpy/zha-device-handlers/issues/1889#issuecomment-1337368444
- I added the `<SimpleDescriptor...>` based on log information obtained via HA. I also attempted to verify other information by comparing to my 2-way Wiser outlet.
- I have attached the info I got from HA so someone can look and confirm: [Wiser-2way.json](https://github.com/zigpy/zha-device-handlers/files/13665503/Wiser-2way.json)

## Checklist

- [ ] The changes are tested and work correctly
- [ ] `pre-commit` checks pass / the code has been formatted using Black
- [ ] Tests have been added to verify that the new code works

### CODE REVIEW

**Comment by kosmiq** [comment]
Also I would love some guidance on how I can test this on my HA Green that I'm running. Do I compile and upload as a custom component? I'd rather not screw it up since it works wonderfully at the moment, except for this little pesky thing with how numbers are reported :)

**Comment by alrassia** [comment]
> Also I would love some guidance on how I can test this on my HA Green that I'm running. Do I compile and upload as a custom component? I'd rather not screw it up since it works wonderfully at the moment, except for this little pesky thing with how numbers are reported :)

You can take a look at https://community.home-assistant.io/t/how-to-setup-local-zha-quirks/341226 on how to setup using a custom quirk.

**Comment by Hedda** [comment]
> > Also I would love some guidance on how I can test this on my HA Green that I'm running. 
> 
> You can take a look at https://community.home-assistant.io/t/how-to-setup-local-zha-quirks/341226 on how to setup using a custom quirk.

Also check out this PR with an end-user how-to guide for the readme -> https://github.com/zigpy/zha-device-handlers/pull/2419 + this other discussion here -> https://github.com/zigpy/zha-device-handlers/discussions/2467

**Comment by TheJulianJES** [comment]
@kosmiq Were you able to get this running and verify that it works for your plugs (by installing the file as a custom quirk)?

**Comment by TheJulianJES** [comment]
Pushed some small changes. This can be tested as a custom quirk using this: https://github.com/zigpy/zha-device-handlers/issues/1889#issuecomment-1901043565

**Comment by kosmiq** [comment]
> @kosmiq Were you able to get this running and verify that it works for your plugs (by installing the file as a custom quirk)?

Hi! Not yet. It’s on my radar but life got in the way with Christmas and all. Still looking to find the time. 

Thanks for the cleanup and adding the tests! Much appreciated

**Comment by TheJulianJES** [comment]
Tested here: https://github.com/zigpy/zha-device-handlers/issues/1889#issuecomment-1902459242

So, should be fine. Tests are also added.

**Pull request merged**
