### PR TITLE
Support ZCLv7 zigpy changes

### PR DESCRIPTION
**Pull request by puddly**
https://github.com/zigpy/zigpy/pull/716

### CODE REVIEW

**Comment by TheJulianJES** [comment]
The Philips quirk currently implements the OnOff/start_up_on_off (0x4003) option "manually":
https://github.com/zigpy/zha-device-handlers/blob/833c1b913105c87fe93b8dfd20902d27ec4004f8/zhaquirks/philips/__init__.py#L93-L97

I guess this can be removed in the future then. (But having it also shouldn't hurt anything)

**Comment by puddly** [comment]
It looks like all of the Philips/Signify light quirks can be removed, since they were just exposing the new ZCLv7 startup attributes.

**Comment by puddly** [comment]
@Shulyaka can you suggest some unique names for the XBee quirk's client and server commands?

https://github.com/zigpy/zha-device-handlers/blob/b180e4f7ab4a096688f4d4ad9b47ac1b3efa9fe2/zhaquirks/xbee/__init__.py#L282-L283

I'm trying to map each cluster's client/server command names to their definitions and currently the XBee quirk is the only one with non-unique names.

**Comment by Shulyaka** [comment]
@puddly I will only be able to check on Friday, no earlier, too busy...

**Comment by Shulyaka** [comment]
Hi @puddly, sorry for the delay!

It appears that you can just remove the client `io_sample` command for this cluster, it's not used. I just tested it on my environment.

**Comment by dmulcahey** [comment]
@puddly this still a thing?

**Comment by puddly** [comment]
Yeah, gotta finish the zigpy side. Forgot what I got stuck on...

**Comment by puddly** [comment]
I've updated this PR and the [corresponding one in zigpy](https://github.com/zigpy/zigpy/pull/716) with the changes since May. Both are functional for me. However, my network is pretty homogeneous and quirks at the moment doesn't have complete unit test coverage so I'm not confident that the code is free of any new bugs.

Does anyone with Tuya devices or others that require heavy attribute/command rewriting in quirks want to try these changes out?

You can setup an editable copy of ZHA in your `custom_components` folder (https://github.com/zigpy/zigpy/issues/826#issuecomment-947850313) and update the zigpy and quirks dependencies in the `manifest.json` file:

```
git+https://github.com/puddly/zigpy@puddly/zclv7
git+https://github.com/puddly/zha-device-handlers@puddly/zclv7-fixes
```

**Comment by MattWestb** [comment]
I can  trying it on my large test network (13 devices 5 routers and 8 SED) but i think its not helping then its have some routers and all types of IKEA controllers and one tuya TRV but is using  my new quirk and is not using the tests (i have broken all test then reworking the quirk) and they is not sending so much data but i can playing with them so they is doing it.

Also i have local quirks that is not in HA 2021-10 (IKEA 5 button and shortcut) but they is in your dev so shall not being any problems.
I can "de patching" ZHA (patch for presets for my TRV) and using the old quirk for the testing then the TRV is on my living room table.

If you like i can doing it but i dont knowing if its helping your test case.

**Comment by puddly** [comment]
> If you like i can doing it but i dont knowing if its helping your test case.

Thanks. Any real-world Tuya tests are better than none.

**Comment by MattWestb** [comment]
@puddly can you explaining how to change the `manifest.json` i only getting error and ZHA is not loading.

And shall i putting the complete downloaded git only the zgpy / zhaquirks folder in the custom_components folder ?

I have forgetting how i was doing then running bellows alpha / beta as custom_components ;-((

**Comment by puddly** [comment]
My mistake, Home Assistant runs more checks on the requirements in `manifest.json` before passing them to `pip`.

1. Copy/paste the `homeassistant/components/zha` folder into `custom_components/zha`. You could also `git clone` the Home Assistant repo and symlink the folder to track your changes.
2. Edit `manifest.json` and add a top-level `"version": "1.0.0"` key so it loads as a custom component.
3. Edit `manifest.json` and replace the `zigpy==...` dependency with `django@git+https://github.com/puddly/zigpy@puddly/zclv7`[^1].
4. Do the same for `zha-quirks==...`: `django@git+https://github.com/puddly/zha-device-handlers@puddly/zclv7-fixes`.

```diff
diff --git a/custom_components/zha/manifest.json b/custom_components/zha/manifest.json
index 1fa15259..56b76c4a 100644
--- a/custom_components/zha/manifest.json
+++ b/custom_components/zha/manifest.json
@@ -1,4 +1,5 @@
 {
+  "version": "1.0.0",
   "domain": "zha",
   "name": "Zigbee Home Automation",
   "config_flow": true,
@@ -7,9 +8,9 @@
     "bellows==0.28.0",
     "pyserial==3.5",
     "pyserial-asyncio==0.5",
-    "zha-quirks==0.0.63",
+    "django@git+https://github.com/puddly/zha-device-handlers@puddly/zclv7-fixes",
     "zigpy-deconz==0.13.0",
-    "zigpy==0.41.0",
+    "django@git+https://github.com/puddly/zigpy@puddly/zclv7",
     "zigpy-xbee==0.14.0",
     "zigpy-zigate==0.7.3",
     "zigpy-znp==0.6.1"
```

[^1]: `django` can really be any package name, it's just to trick Home Assistant into thinking it's not installed and then passing that whole string to `pip`. I picked `django` because it's probably not installed and won't be maliciously parked.

**Comment by MattWestb** [comment]
I was adding the first with version and deleting the zigpy and zha_quirk.
Then running pip **in** the  HA container with your 2 gits and restarting HA and somthing have being loaded:
```
Logger: homeassistant.config_entries
Source: components/zha/__init__.py:99
First occurred: 22:44:15 (1 occurrences)
Last logged: 22:44:15

Error setting up entry socket://192.168.2.127:6638 (LIDL LED NCP) for zha
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/zha/__init__.py", line 99, in async_setup_entry
    setup_quirks(config)
  File "/usr/local/lib/python3.9/site-packages/zhaquirks/__init__.py", line 394, in setup
    importlib.import_module(modname)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/zhaquirks/centralite/__init__.py", line 11, in <module>
    class CentraLiteAccelCluster(CustomCluster):
  File "/usr/local/lib/python3.9/site-packages/zigpy/zcl/__init__.py", line 91, in __init_subclass__
    raise TypeError(
TypeError: `manufacturer_attributes` is deprecated. Copy the parent class's `attributes` dictionary and update it with your manufacturer-specific `attributes`. Make sure to specify that it is manufacturer-specific through the  appropriate constructor or tuple!
```
I shall deleting my custom quirks then they can doing bad things and reporting back.

**Comment by puddly** [comment]
The error is coming from `/usr/local/lib/python3.9/site-packages/zhaquirks/centralite/__init__.py` so it seems like the `zha-quirks` package is not on the ZCLv7 branch, only `zigpy`.

**Comment by MattWestb** [comment]
I was doing one `pip uninstall zha-quirks` and then one "puddly" `pip install git+https://github.com/puddly/zha-device-handlers@puddly/zclv7-fixes`
and restarted HA and i have no errors and my tuya TRV have loosing its patched quirks so i thinks its loaded OK.

I think PIP was not deleting the old OK then installing the new one.

I testing little but i must going to sleep then having working to do tomorrow noon but i testing then i have time.

**Comment by MattWestb** [comment]
The TRV without the updated quirk dont have so many functions only on / off and setting / reporting setpopint temperature but i have ding both in ZHA and local for nearly one half hour and its very fast reporting to ZHA but slow reacting on commands but its still one "half sleeping end device" so its normal.

No error or warning in HA the log but the log file its being pity large with my debug setting.

Shall i testing all IKEA controllers 2 or is the tuya TRV enough ?

**Comment by MattWestb** [comment]
One error in the test setup but i dont knowing if its related to this update:
 ```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/zha/api.py:631
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: November 14, 2021, 23:40:09 (2 occurrences)
Last logged: November 14, 2021, 23:40:54

[140339730776896] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/zha/api.py", line 631, in websocket_device_cluster_commands
    ATTR_NAME: commands[CLUSTER_COMMANDS_SERVER][cmd_id][0],
TypeError: 'ZCLCommandDef' object is not subscriptable

```

**Comment by MattWestb** [comment]
Was looking in the log and i have some logging enabled but not so much and its was triggered the reporting attributes form one IKEA CWS 3 (the new RGBW bulb with MG21 module) or from analytics HA is collecting:
```
2021-11-14 23:32:15 DEBUG (MainThread) [zigpy.zcl] [0x6c21:1:0x0300] ZCL request 0x000a: Report_Attributes(attribute_reports=[Attribute(attrid=0x0007, value=TypeValue(type=uint16_t, value=250))])
2021-11-14 23:32:15 DEBUG (MainThread) [zigpy.zcl] [0x6c21:1:0x0300] Attribute report received: color_temperature=250
2021-11-14 23:33:15 INFO (MainThread) [homeassistant.components.analytics] Submitted analytics to Home Assistant servers. Information submitted includes {'uuid': 'bbe501a5c0d44ed687d61bf1bc49b40b', 'version': '2021.11.0', 'installation_type': 'Home Assistant Container'}
2021-11-14 23:40:09 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140339730776896] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/zha/api.py", line 631, in websocket_device_cluster_commands
    ATTR_NAME: commands[CLUSTER_COMMANDS_SERVER][cmd_id][0],
TypeError: 'ZCLCommandDef' object is not subscriptable
2021-11-14 23:40:54 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140339730776896] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/zha/api.py", line 631, in websocket_device_cluster_commands
    ATTR_NAME: commands[CLUSTER_COMMANDS_SERVER][cmd_id][0],
TypeError: 'ZCLCommandDef' object is not subscriptable
2021-11-14 23:42:47 DEBUG (MainThread) [zigpy.zcl] [0x6c21:1:0x0006] ZCL header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.GLOBAL_COMMAND: 0>, is_manufacturer_specific=0, is_reply=1, disable_default_response=0, reserved=0, *is_cluster=False, *is_general=True), tsn=120, command_id=10, *is_reply=1)
2021-11-14 23:42:47 DEBUG (MainThread) [zigpy.zcl] [0x6c21:1:0x0006] ZCL request 0x000a: Report_Attributes(attribute_reports=[Attribute(attrid=0x0000, value=TypeValue(type=Bool, value=<Bool.false: 0>))])
2021-11-14 23:42:47 DEBUG (MainThread) [zigpy.zcl] [0x6c21:1:0x0006] Attribute report received: on_off=<Bool.false: 0>
2021-11-14 23:42:47 DEBUG (MainThread) [zigpy.zcl] [0x6c21:1:0x0008] ZCL header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.GLOBAL_COMMAND: 0>, is_manufacturer_specific=0, is_reply=1, disable_default_response=0, reserved=0, *is_cluster=False, *is_general=True), tsn=121, command_id=10, *is_reply=1)
2021-11-14 23:42:47 DEBUG (MainThread) [zigpy.zcl] [0x6c21:1:0x0008] ZCL request 0x000a: Report_Attributes(attribute_reports=[Attribute(attrid=0x0000, value=TypeValue(type=uint8_t, value=42))])
2021-11-14 23:42:47 DEBUG (MainThread) [zigpy.zcl] [0x6c21:1:0x0008] Attribute report received: current_level=42
``` 
Then the error its tagged ZHA is not very likely its not relented to the analytic and around the error (5 minutes before and 30 minutes after) it was only the IKEA light that was reporting attributes.

**Pull request merged**
