### PR TITLE
decoupled mode for lumi.ctrl_ln1.aq1, lumi.ctrl_ln2.aq1

### LINKED ISSUE #365: [Device Support Request] Aqara Wall Switch - decoupled mode?
How to configure the button on QBKG12LM to decoupled mode?
I need to receive button events, but control the relay separately.

### PR DESCRIPTION
**Pull request by jinhong-**
Resolves #365

Adds support for decoupled mode for lumi.ctrl_ln1.aq1 and lumi.ctrl_ln2.aq1 devices

### CODE REVIEW

**Comment by dmulcahey** [comment]
Just run black, iSort etc and should be good to go

**Review by Adminiuga — APPROVED** [review]
Lgtm. Once lint is fixed can be merged

**Comment by jinhong-** [comment]
Ran it through black. Should be fixed now

**Comment by dmulcahey** [comment]
Still needs imports sorted

**Comment by jinhong-** [comment]
@dmulcahey ran isort as well

**Pull request merged**
