### PR TITLE
Added another IKEA FLOALT panel to CCT ZHA light quirk

### PR DESCRIPTION
**Pull request by TheJulianJES**
Same as https://github.com/zigpy/zha-device-handlers/pull/793 but with a different device.
Signature: https://paste.ubuntu.com/p/c7dvvvgypb/

### CODE REVIEW

**Review by dmulcahey — APPROVED** [review]

**Comment by Iyaka25747** [comment]
TX for having added IKEA "FLOALT panel WS 60x60" !!!

**Comment by nielspeen** [comment]
Is this why my FLOALT WS 30x30 panels show up as a _switch_ whereas the 60x60 panels shows up as a _light_?

**Comment by MattWestb** [comment]
Have you updated the firmware on the panel to Zigbee 3 ?

What is the "cluster device signature" showing ?

**Comment by nielspeen** [comment]
I've seen Home Assistant push updates to my panels, but I have not yet figured out which version it uses.

This is the signature:

`{
  "node_descriptor": "NodeDescriptor(byte1=1, byte2=64, mac_capability_flags=142, manufacturer_code=4476, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=0, maximum_outgoing_transfer_size=82, descriptor_capability_field=0, *allocate_address=True, *complex_descriptor_available=False, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False, *is_valid=True, *logical_type=<LogicalType.Router: 1>, *user_descriptor_available=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0220",
      "in_clusters": [
        "0x0000",
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006",
        "0x0008",
        "0x0300",
        "0x0b05",
        "0x1000"
      ],
      "out_clusters": [
        "0x0005",
        "0x0019",
        "0x0020",
        "0x1000"
      ]
    }
  },
  "manufacturer": "IKEA of Sweden",
  "model": "FLOALT panel WS 30x30",
  "class": "zigpy.device.Device"
}`

**Comment by MattWestb** [comment]
very likely old ZLL then you dont have the second endpoint.

Manage cluster > basic cluster > SW_build_id and then clicking get zigbee attribute.

**Comment by nielspeen** [comment]
Ah! There we go: 2.3.068

**Comment by MattWestb** [comment]
The second endpoint is looking like this in the  "cluster device signature":
```

    "242": {
      "profile_id": 41440,
      "device_type": "0x0061",
      "in_clusters": [
        "0x0021"
      ],
      "out_clusters": [
        "0x0021"
      ]
    }
```

**Comment by nielspeen** [comment]
That worked. It has the second endpoint and HA now correctly identifies it as a light. Thanks!

**Comment by MattWestb** [comment]
Great then you have getting on more real Zigbee 3 device.
IKEA have only the old motion sensor and the old CWS (RGBW) that still is ZLL all the rest is updated.

**Pull request merged**
