### PR TITLE
#1361 Adding _TZE200_tviaymwx to the supported switches

### LINKED ISSUE #1361: [Device Support Request]
**Is your feature request related to a problem? Please describe.**

When my zigbee is discovered (_TZE200_tviaymwx ) by the Zigbee Home Automation integration Home Assistant, it's not properly recognized. Is not using the propew Quirk (TuyaSingleSwitchTO) and thus, is nos showing the proper controls. This is a new variant of the same 1 gang switch.

image

**Describe the solution you'd like**
I like the device to be discovered properly and with the proper quirkc attached like this other one

image

**Device signature - this can be acquired by removing the device from ZHA and pairing it again from the add devices screen. Be sure to add the entire content of the log panel after pairing the device to a code block below this line.**

```
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4098, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0051",
      "in_clusters": [
        "0x0000",
        "0x0004",
        "0x0005",
        "0xef00"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    }
  },
  "manufacturer": "_TZE200_tviaymwx",
  "model": "TS0601",
  "class": "zigpy.device.Device"
}
```

**Additional context**

### PR DESCRIPTION
**Pull request by luisgreen**
This pull request add the _TZE200_tviaymwx manufacturer model support,  Resolves #1361

### CODE REVIEW

**Review by MattWestb — APPROVED** [review]

**Comment by luisgreen** [comment]
@MattWestb I tested this locally and works as expected FYI.

**Comment by MattWestb** [comment]
The device and the quirk looks very OK !!
But your network is not having one link with LQI over 100 and only one over 50 = very week signal between the devices.
If you is getting problem with your system you need getting better LQI between your devices or they can dropping off / reseeding data all the time.

Also looking so you is not using one Zigbee channel that have strong WiFi around your devices then you need moving the Zigbee or WiFi network (the channel numbers is not the same in Zigbee and WiFi).

### Great work adding the new switch !!

**Comment by luisgreen** [comment]
Your comments are awesome @MattWestb thanks! I have two routers, evenly distributed, WIFI 2.4 is on channel 7 and I assume the default zigpy is 15. not sure what else I can do for enhancing this. What do you suggest?

**Comment by MattWestb** [comment]
If its working OK = do nothing !!

Look little later on the network map if the LQi is going up (ZHA is doing scans around every 4 hour) if its being better.

The 2 plugs is having TI chips but i hope its not CC-2530 ones than they normally having  bad radio / antennas and also very old buggy Zigbee stack that very likely is not Zugbee 3.

If needing put some good router devices around the switches so they is getting help reaching the coordinator.
Good routers is **NOT** OSRAM plugs then they is doing more damage then helping (bad hard and software in them) but normally all light and plugs is working OK.

Look also if the switch "passilo" is getting only one link (its one end device and shall having only one parent but some routers is not deleting there children then timing out or they is jumping to one new parent router = Philips HUE devices).

Silabs chips is normally working OK and is having very good radio on the chip and is used by IKEA and tuya and many more small and large company's but all is having bugs and "personality" that can making problems with some device and both is working OK with problematic Xiaomi / Aqara sensors (that is very picky of there parents).

**Pull request merged**
