### PR TITLE
add support for URC4460BC0-X-R

### PR DESCRIPTION
**Pull request by dXcess**
this quirk will fix an issue where the battery status is displayed as unknown.

Issues and resolution originally submitted here:
https://github.com/zigpy/zha-device-handlers/issues/1550

### CODE REVIEW

**Comment by TheJulianJES** [comment]
Thanks for the PR!

Since the `universalelectronics` folder was added with this PR, we also need a `__init__.py` file there.
Can you create that and just put something like `"""Module for Universal Electronics devices."""` in that file?

**Comment by dXcess** [comment]
> Thanks for the PR!
> 
> Since the `universalelectronics` folder was added with this PR, we also need a `__init__.py` file there. Can you create that and just put something like `"""Module for Universal Electronics devices."""` in that file?


Thanks for the guidance. I just created the file as suggested. Hopefully it was properly submitted as part of the pull request?

**Comment by TheJulianJES** [comment]
> Hopefully it was properly submitted as part of the pull request?

Yep, it was! I made a small change to rename that file (to remove the dashes, so it properly works) and everything looks good to me now.
Thanks for your work!

**Review by TheJulianJES — APPROVED** [review]

**Review by javicalle — APPROVED** [review]
LGTM

**Pull request merged**
