### PR TITLE
Innr SP120 multiplier fix

### PR DESCRIPTION
**Pull request by goxlur**
Fix for Innr SP120 plug ElectricalMeasurement and Meter cluster multipliers and divisors.

### CODE REVIEW

**Comment by Adminiuga** [comment]
Please also post the datecode attribute value and firmware version if zha reports it for the plug you tested the quirk with

**Comment by MattWestb** [comment]
You can using Black Playground for fixing most bad formatting https://black.vercel.app/.

**Comment by goxlur** [comment]
> Please also post the datecode attribute value and firmware version if zha reports it for the plug you tested the quirk with

date_code: 20171027-100
Firmware: 0x11040002

**Comment by Adminiuga** [comment]
Run the isort again so the checks would pass

**Comment by dmulcahey** [comment]
@Adminiuga are you good with this?

**Comment by Adminiuga** [comment]
Yes

**Pull request merged**
