### PR TITLE
Add Tuya cover `_TZE200_vdiuwbkq` variant

### PR DESCRIPTION
**Pull request by FedeltaMedia**
New cover model _TZE200_vdiuwbkq added for Tuya TS0601

## Proposed change

Implement new cover model _TZE200_vdiuwbkq for Tuya TS0601 as discussed in #3117 

## Checklist

- [X] The changes are tested and work correctly
- [X] `pre-commit` checks pass / the code has been formatted using Black
- [X] Tests have been added to verify that the new code works

### CODE REVIEW

**Comment by FedeltaMedia** [comment]
Screenshot 2024-11-04 at 09 53 13
Added the modified [ts0601_cover.py](https://github.com/zigpy/zha-device-handlers/pull/3471/commits/5bd25751575d7a662c76d48a9015aa79619a2d54#diff-d538b25af8d48a5d2c3ce15a3ae96192b0e4e044b4f2115e6c81bdcdd351f088) python file through custom quirk. Works perfectly!

@TheJulianJES Can you add a Tuya label and approve the changes please? Thanks!

**Review by TheJulianJES — APPROVED** [review]
Thanks!

**Comment by StrangerKLG** [comment]
Hi! 
Can you add TS0601_TZE204_bjzrowv2
I foud some information in for zigbee2mqtt but nothing for ZHA

https://github.com/Koenkk/zigbee2mqtt/issues/22016?ysclid=m7ruiz4zk6573330650

if you need any additional info just let me know - i'll try to send everthing i can get

**Comment by FedeltaMedia** [comment]
@StrangerKLG Who? Me? You’re responding in my pull request?

Maybe better to open your own pull request where you make the file changes. Or if you’re not familiar with that, open a new issue for yourself.

**Comment by StrangerKLG** [comment]
> @StrangerKLG Who? Me? You’re responding in my pull request?
> 
> Maybe better to open your own pull request where you make the file changes. Or if you’re not familiar with that, open a new issue for yourself.

Sorry, my mistake

**Pull request merged**
