### PR TITLE
Add Tuya cover TS0601 `_TZE200_nw1r9hp6` variant

### PR DESCRIPTION
**Pull request by MopishHobgoblin**
Added ("_TZE200_nw1r9hp6", "TS0601") to line 375.

## Checklist

- [x] The changes are tested and work correctly
- [ ] `pre-commit` checks pass / the code has been formatted using Black
- [ ] Tests have been added to verify that the new code works

### CODE REVIEW

**Comment by TheJulianJES** [comment]
Were you able to test that change (as a custom quirk) to see that it works correctly?

**Comment by javicalle** [comment]
It seems consistent with Z2M:
* https://github.com/Koenkk/zigbee-herdsman-converters/blob/484be3b58fdb04eb67ac6ddad8c4bab325837c39/src/devices/tuya.ts#L2124

**Comment by MopishHobgoblin** [comment]
> Were you able to test that change (as a custom quirk) to see that it works correctly?

Yes, working as expected with a custom quirk.

**Review by TheJulianJES — APPROVED** [review]

**Comment by TheJulianJES** [comment]
Thanks!

**Pull request merged**
