### PR TITLE
Add support for Adeo LDSENK08 contact and vibration detector

### LINKED ISSUE #2249: [Device Support Request] ADEO LDSENK08 contact and vibration detector
**Is your feature request related to a problem? Please describe.**
ADEO (Lexman) LDSENK08 device is a contact sensor with a vibration sensor.
The device only shows a IasZone sensor in ZHA with the contact and vibration events mixed. You cannot know if it is a vibration or an open contact event.
The type of event can be found by reading the zone_status property :
- if ZONE_STATUS first bit is set, it's an open contact
- if ZONE_STATUS second bit is set, it's a vibration event

Integration has been done in zigbee2mqtt : https://www.zigbee2mqtt.io/devices/LDSENK08.html

PS : the device also gives tamper and low battery details on bits 3 and 4 but I guess this will be addressed here : https://github.com/home-assistant/core/issues/72828

**Describe the solution you'd like**
I would like to separate contact and vibration sensors in ZHA.
I've made a quirk which works by adding 2 endpoints for the contact and vibration sensors and using a bus to pass the events depending on the Iaszone zone_status bits.
It's my first quirk and I am not sure it's done the right way. I would like your opinion before opening a PR.

```python
"""Device handler for ADEO Lexman LDSENK08 smart door window sensor with vibration"""
import logging

from typing import Any, List, Optional, Union

from zigpy.profiles import zha
from zigpy.quirks import CustomDevice, CustomCluster
import zigpy.types as t
from zigpy.zcl.clusters.general import (
    Basic,
    Identify,
    Ota,
    PollControl,
    PowerConfiguration,
)
from zigpy.zcl.clusters.homeautomation import Diagnostic
from zigpy.zcl.clusters.security import IasZone
from zigpy.zcl import foundation

from zhaquirks import Bus, LocalDataCluster
from zhaquirks.const import (
    DEVICE_TYPE,
    ENDPOINTS,
    INPUT_CLUSTERS,
    MODELS_INFO,
    OUTPUT_CLUSTERS,
    PROFILE_ID,
    ZONE_STATUS,
    ZONE_TYPE,
    ON,
    OFF,
)

_LOGGER = logging.getLogger(__name__)

class IasMultiZoneCluster(CustomCluster, IasZone):
    """Multi Zone Cluster."""
    _CONSTANT_ATTRIBUTES = {ZONE_TYPE: IasZone.ZoneType.Standard_CIE}

    def handle_cluster_request(
        self,
        hdr: foundation.ZCLHeader,
        args: List[Any],
        *,
        dst_addressing: Optional[
            Union[t.Addressing.Group, t.Addressing.IEEE, t.Addressing.NWK]
        ] = None,
    ):
        """Handle a cluster command received on this cluster."""
        if hdr.command_id == 0:
            #If we have bit 2, it's a vibration
            if (args[0] & 2) > 0:
                self.endpoint.device.ias_bus.listener_event("vibration_event", ON)
            else:
                self.endpoint.device.ias_bus.listener_event("vibration_event", OFF)
            #If we have bit 1, it's open
            if (args[0] & 1) > 0:
                self.endpoint.device.ias_bus.listener_event("contact_event", ON)
            else:
                self.endpoint.device.ias_bus.listener_event("contact_event", OFF)
        super().handle_cluster_request(hdr, args, dst_addressing=dst_addressing)

class VibrationCluster(CustomCluster, IasZone):
    """Vibration Sensor."""
    _CONSTANT_ATTRIBUTES = {ZONE_TYPE: IasZone.ZoneType.Vibration_Movement_Sensor}

    def __init__(self, *args, **kwargs):
        """Init."""
        super().__init__(*args, **kwargs)
        self.endpoint.device.ias_bus.add_listener(self)

    def vibration_event(self, value):
        """Vibration event."""
        self._update_attribute(ZONE_STATUS, value)

class ContactCluster(LocalDataCluster, IasZone):
    """Open/close Sensor."""
    _CONSTANT_ATTRIBUTES = {ZONE_TYPE: IasZone.ZoneType.Contact_Switch}

    def __init__(self, *args, **kwargs):
        """Init."""
        super().__init__(*args, **kwargs)
        self.endpoint.device.ias_bus.add_listener(self)

    def contact_event(self, value):
        """Contact event."""
        self._update_attribute(ZONE_STATUS, value)

class AdeoLdsenk08(CustomDevice):
    """Adeo contact and vibration sensor controller."""

    def __init__(self, *args, **kwargs):
        """Init device."""
        self.ias_bus = Bus()
        super().__init__(*args, **kwargs)

    signature = {
        #  <SimpleDescriptor endpoint=1 profile=260 device_type=1026
        #  device_version=1
        #  input_clusters=[0, 1, 3, 32, 1280, 2821]
        #  output_clusters=[25]>
        MODELS_INFO: [("ADEO", "LDSENK08")],
        ENDPOINTS: {
            1: {
                PROFILE_ID: zha.PROFILE_ID,  # 260
                DEVICE_TYPE: zha.DeviceType.IAS_ZONE,  # 2048
                INPUT_CLUSTERS: [
                    Basic.cluster_id,  # 0
                    PowerConfiguration.cluster_id,  # 1
                    Identify.cluster_id,  # 3
                    PollControl.cluster_id,  # 32
                    IasZone.cluster_id,  # 1280
                    Diagnostic.cluster_id  # 2821
                ],
                OUTPUT_CLUSTERS: [
                    Ota.cluster_id  # 25
                ],
            }
        },
    }

    replacement = {
        ENDPOINTS: {
            1: {
                PROFILE_ID: zha.PROFILE_ID,
                DEVICE_TYPE: zha.DeviceType.IAS_ZONE,
                INPUT_CLUSTERS: [
                    Basic.cluster_id,  # 0
                    PowerConfiguration.cluster_id,  # 1
                    Identify.cluster_id,  # 3
                    PollControl.cluster_id,  # 32
                    IasMultiZoneCluster,  # 1280
                    Diagnostic.cluster_id  # 2821
                ],
                OUTPUT_CLUSTERS: [
                    Ota.cluster_id  # 25
                ],
            },
            2: {
                PROFILE_ID: zha.PROFILE_ID,
                DEVICE_TYPE: zha.DeviceType.IAS_ZONE,
                INPUT_CLUSTERS: [
                    VibrationCluster,  # 1280
                ],
                OUTPUT_CLUSTERS: [],
            },
            3: {
                PROFILE_ID: zha.PROFILE_ID,
                DEVICE_TYPE: zha.DeviceType.IAS_ZONE,
                INPUT_CLUSTERS: [
                    ContactCluster,  # 1280
                ],
                OUTPUT_CLUSTERS: [],
            },
        },
    }
```
Capture d’écran du 2023-03-03 17-51-59

<details>

<summary>Device signature</summary>

```yaml
{
      "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4727, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
      "endpoints": {
        "1": {
          "profile_id": 260,
          "device_type": "0x0402",
          "in_clusters": [
            "0x0000",
            "0x0001",
            "0x0003",
            "0x0020",
            "0x0500",
            "0x0b05"
          ],
          "out_clusters": [
            "0x0019"
          ]
        }
      }
    }
```

</details>

<details>

<summary>Diagnostic information</summary>

```yaml
  "data": {
    "ieee": "**REDACTED**",
    "nwk": 35566,
    "manufacturer": "ADEO",
    "model": "LDSENK08",
    "name": "ADEO LDSENK08",
    "quirk_applied": true,
    "quirk_class": "sensor_ldsenk08.AdeoLdsenk08",
    "manufacturer_code": 4727,
    "power_source": "Battery or Unknown",
    "lqi": null,
    "rssi": null,
    "last_seen": "2023-03-03T17:32:07",
    "available": true,
    "device_type": "EndDevice",
    "signature": {
      "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4727, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
      "endpoints": {
        "1": {
          "profile_id": 260,
          "device_type": "0x0402",
          "in_clusters": [
            "0x0000",
            "0x0001",
            "0x0003",
            "0x0020",
            "0x0500",
            "0x0b05"
          ],
          "out_clusters": [
            "0x0019"
          ]
        }
      }
    },
    "active_coordinator": false,
    "entities": [
      {
        "entity_id": "binary_sensor.capteur_fenetre_sous_sol_1_iaszone",
        "name": "ADEO LDSENK08"
      },
      {
        "entity_id": "button.capteur_fenetre_sous_sol_1_identify",
        "name": "ADEO LDSENK08"
      },
      {
        "entity_id": "sensor.capteur_fenetre_sous_sol_1_battery",
        "name": "ADEO LDSENK08"
      }
    ],
    "neighbors": [],
    "routes": [],
    "endpoint_names": [
      {
        "name": "IAS_ZONE"
      }
    ],
    "user_given_name": "Capteur fen\u00eatre sous-sol 1",
    "device_reg_id": "18908c59f20baa5018193bd17fa3521d",
    "area_id": "sous_sol",
    "cluster_details": {
      "1": {
        "device_type": {
          "name": "IAS_ZONE",
          "id": 1026
        },
        "profile_id": 260,
        "in_clusters": {
          "0x0000": {
            "endpoint_attribute": "basic",
            "attributes": {
              "0x0004": {
                "attribute_name": "manufacturer",
                "value": "ADEO"
              },
              "0x0005": {
                "attribute_name": "model",
                "value": "LDSENK08"
              }
            },
            "unsupported_attributes": {}
          },
          "0x0001": {
            "endpoint_attribute": "power",
            "attributes": {
              "0x0020": {
                "attribute_name": "battery_voltage",
                "value": 29
              },
              "0x0021": {
                "attribute_name": "battery_percentage_remaining",
                "value": 128
              },
              "0x0031": {
                "attribute_name": "battery_size",
                "value": 255
              },
              "0x0033": {
                "attribute_name": "battery_quantity",
                "value": 0
              }
            },
            "unsupported_attributes": {}
          },
          "0x0003": {
            "endpoint_attribute": "identify",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0020": {
            "endpoint_attribute": "poll_control",
            "attributes": {
              "0x0000": {
                "attribute_name": "checkin_interval",
                "value": 13200
              }
            },
            "unsupported_attributes": {}
          },
          "0x0500": {
            "endpoint_attribute": "ias_zone",
            "attributes": {
              "0x0000": {
                "attribute_name": "zone_state",
                "value": 1
              },
              "0x0001": {
                "attribute_name": "zone_type",
                "value": 0
              },
              "0x0002": {
                "attribute_name": "zone_status",
                "value": 48
              },
              "0x0010": {
                "attribute_name": "cie_addr",
                "value": "e0:79:8d:ff:fe:74:16:62"
              },
              "0x0011": {
                "attribute_name": "zone_id",
                "value": 0
              },
              "0x0013": {
                "attribute_name": "current_zone_sensitivity_level",
                "value": 1
              }
            },
            "unsupported_attributes": {
              "0x0012": {
                "attribute_name": "num_zone_sensitivity_levels_supported"
              }
            }
          },
          "0x0b05": {
            "endpoint_attribute": "diagnostic",
            "attributes": {},
            "unsupported_attributes": {}
          }
        },
        "out_clusters": {
          "0x0019": {
            "endpoint_attribute": "ota",
            "attributes": {},
            "unsupported_attributes": {}
          }
        }
      }
    }
  }
}
```

</details>

<details>
<summary>Additional logs</summary>

```
Paste any additional debug logs here.
Don't remove the extra line breaks outside the ``` marks.
```

</details>

**Additional context**

### PR DESCRIPTION
**Pull request by dranih**
Adding a new quirk to have both contact and vibration sensors from Adeo LDSENK08.
Fixes #2249

### CODE REVIEW

**Comment by javicalle** [comment]
LGTM, but...

@TheJulianJES I believe that this can also be addressed in ZHA, maybe in a cleaner way?:
* https://github.com/home-assistant/core/blob/52a94dd2ac50b9035555e69100db33e968e9365d/homeassistant/components/zha/binary_sensor.py#L159-L175

We can create the 2 new sensors (contact + vibration) matching the models_info. What do you yhink?

**Comment by MattWestb** [comment]
Do we having getting the the quirk class working for this in ZHA so not need adding device info for all sensors ?
If yes i think its better using quirk class if its coming more versions that is using the same functions in the future.

**Comment by TheJulianJES** [comment]
Hmm, with the current implementation, the bits were also stripped in the IasZone channel. That `async_update` method was never actually called.

However, https://github.com/home-assistant/core/pull/89481 cleans this up and and should indeed make it possible.
I'll have a look at it in a bit.

**Comment by TheJulianJES** [comment]
https://github.com/home-assistant/core/pull/89481 should make it possible to "cleanly" implement this in ZHA without creating artificial clusters.

However, with https://github.com/home-assistant/core/pull/91841 merged, the artificial `IasZone` clusters with different types should now have proper names by default in HA.

... so I guess the quirk would be fine too.

**Pull request closed without merging**
