### PR TITLE
Add quirks to support Sinope light and dimmer

### PR DESCRIPTION
**Pull request by claudegel**
First PR for Sinope Light and dimmer

### CODE REVIEW

**Comment by claudegel** [comment]
Don't understand what is missing in the formating

**Comment by Adminiuga** [comment]
if you run `black /home/travis/build/zigpy/zha-device-handlers/zhaquirks/sinope/light.py` what changes does it make to the file?

**Comment by claudegel** [comment]
Black only reformat the OUTPUT_CLUSTERS: line, splitting it in one line per cluster_id. I see that I'm missing the empty line at the end. Don't know if it could be the problem

**Comment by claudegel** [comment]
If I run `black /var/www/html/zha-device-handlers/zha-device-handlers/zhaquirks/sinope/light.py` I get 1 file left unchanged.
This is my local light.py which is the same as the one I try in my PR
If I do `diff local-light.py git-light.py` it return no difference

**Comment by Adminiuga** [comment]
in your local copy, you could add `--diff \` line in `script/check_format` script, after line containing `--check \` and run `tox -e lint` which would run the same tests the CI is running and then you could see what is it complaining about.

**Comment by Adminiuga** [comment]
it's the same fix as you had in https://github.com/zigpy/zha-device-handlers/pull/425/commits/e9e64ccff9997e91fabe1a3139985f1ab219940b but just to different class definition

**Comment by claudegel** [comment]
Thank you. Next I'll check for Sinopé water leak devices and load controler to see if they work in ZHA

**Comment by claudegel** [comment]
Le Thu, 30 Jul 2020 18:10:44 -0700
Alexei Chetroi <notifications@github.com> a écrit:

> Merged #425 into dev.
> 

Can you tell me how I can update my fork of zha-device-handlers on git
to get all the new commits in dev branch ?

Thank you

-- 
Claude Gélinas

**Comment by Adminiuga** [comment]
Check https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork
Essentially you add an "upstream" remote, fetch it, then pull updates from upstream dev branch into your local dev branch and then push the updated local dev branch to your fork.

**Pull request merged**
