### PR TITLE
Add initial support for Insta NEXENTRO Pushbutton Interface

### LINKED ISSUE #2084: [Device Support Request] Insta GmbH NEXENTRO Pushbutton Interface
**Is your feature request related to a problem? Please describe.**

I'm unable to make any automations:
image
Probably because there are no entities:
image
But events are fired:
image

**Describe the solution you'd like**

I would like to be able to make automations :)

<details>
<summary>Device signature</summary>

```yaml
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress|RxOnWhenIdle|MainsPowered|FullFunctionDevice: 142>, manufacturer_code=4474, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
  "endpoints": {
    "4": {
      "profile_id": 260,
      "device_type": "0x0105",
      "in_clusters": [
        "0x0000",
        "0x0003"
      ],
      "out_clusters": [
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006",
        "0x0008",
        "0x0019",
        "0x0300"
      ]
    },
    "5": {
      "profile_id": 260,
      "device_type": "0x0105",
      "in_clusters": [
        "0x0000",
        "0x0003"
      ],
      "out_clusters": [
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006",
        "0x0008",
        "0x0019",
        "0x0300"
      ]
    },
    "7": {
      "profile_id": 260,
      "device_type": "0x0203",
      "in_clusters": [
        "0x0000",
        "0x0003"
      ],
      "out_clusters": [
        "0x0003",
        "0x0004",
        "0x0019",
        "0x0102"
      ]
    },
    "242": {
      "profile_id": 41440,
      "device_type": "0x0061",
      "in_clusters": [],
      "out_clusters": [
        "0x0021"
      ]
    }
  },
  "manufacturer": "Insta GmbH",
  "model": "NEXENTRO Pushbutton Interface",
  "class": "zigpy.device.Device"
}
```

</details>

<details>

<summary>Diagnostic information</summary>

```yaml
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.1.0",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.7",
    "docker": true,
    "arch": "armv7l",
    "timezone": "Europe/Berlin",
    "os_name": "Linux",
    "os_version": "5.15.76-v7",
    "supervisor": "2022.12.1",
    "host_os": "Home Assistant OS 9.4",
    "docker_version": "20.10.19",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {},
  "integration_manifest": {
    "domain": "zha",
    "name": "Zigbee Home Automation",
    "config_flow": true,
    "documentation": "https://www.home-assistant.io/integrations/zha",
    "requirements": [
      "bellows==0.34.5",
      "pyserial==3.5",
      "pyserial-asyncio==0.6",
      "zha-quirks==0.0.90",
      "zigpy-deconz==0.19.2",
      "zigpy==0.52.3",
      "zigpy-xbee==0.16.2",
      "zigpy-zigate==0.10.3",
      "zigpy-znp==0.9.2"
    ],
    "usb": [
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*2652*",
        "known_devices": [
          "slae.sh cc2652rb stick"
        ]
      },
      {
        "vid": "1A86",
        "pid": "55D4",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus v2"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*zigstar*",
        "known_devices": [
          "ZigStar Coordinators"
        ]
      },
      {
        "vid": "1CF1",
        "pid": "0030",
        "description": "*conbee*",
        "known_devices": [
          "Conbee II"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8A2A",
        "description": "*zigbee*",
        "known_devices": [
          "Nortek HUSBZB-1"
        ]
      },
      {
        "vid": "0403",
        "pid": "6015",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate+"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8B34",
        "description": "*bv 2010/10*",
        "known_devices": [
          "Bitron Video AV2010/10"
        ]
      }
    ],
    "codeowners": [
      "@dmulcahey",
      "@adminiuga",
      "@puddly"
    ],
    "zeroconf": [
      {
        "type": "_esphomelib._tcp.local.",
        "name": "tube*"
      },
      {
        "type": "_zigate-zigbee-gateway._tcp.local.",
        "name": "*zigate*"
      },
      {
        "type": "_zigstar_gw._tcp.local.",
        "name": "*zigstar*"
      },
      {
        "type": "_slzb-06._tcp.local.",
        "name": "slzb-06*"
      }
    ],
    "dependencies": [
      "file_upload"
    ],
    "after_dependencies": [
      "onboarding",
      "usb",
      "zeroconf"
    ],
    "iot_class": "local_polling",
    "loggers": [
      "aiosqlite",
      "bellows",
      "crccheck",
      "pure_pcapy3",
      "zhaquirks",
      "zigpy",
      "zigpy_deconz",
      "zigpy_xbee",
      "zigpy_zigate",
      "zigpy_znp"
    ],
    "is_built_in": true
  },
  "data": {
    "ieee": "**REDACTED**",
    "nwk": 32105,
    "manufacturer": "Insta GmbH",
    "model": "NEXENTRO Pushbutton Interface",
    "name": "Insta GmbH NEXENTRO Pushbutton Interface",
    "quirk_applied": false,
    "quirk_class": "zigpy.device.Device",
    "manufacturer_code": 4474,
    "power_source": "Mains",
    "lqi": 248,
    "rssi": -84,
    "last_seen": "2023-01-05T20:42:58",
    "available": true,
    "device_type": "Router",
    "signature": {
      "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress|RxOnWhenIdle|MainsPowered|FullFunctionDevice: 142>, manufacturer_code=4474, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
      "endpoints": {
        "4": {
          "profile_id": 260,
          "device_type": "0x0105",
          "in_clusters": [
            "0x0000",
            "0x0003"
          ],
          "out_clusters": [
            "0x0003",
            "0x0004",
            "0x0005",
            "0x0006",
            "0x0008",
            "0x0019",
            "0x0300"
          ]
        },
        "5": {
          "profile_id": 260,
          "device_type": "0x0105",
          "in_clusters": [
            "0x0000",
            "0x0003"
          ],
          "out_clusters": [
            "0x0003",
            "0x0004",
            "0x0005",
            "0x0006",
            "0x0008",
            "0x0019",
            "0x0300"
          ]
        },
        "7": {
          "profile_id": 260,
          "device_type": "0x0203",
          "in_clusters": [
            "0x0000",
            "0x0003"
          ],
          "out_clusters": [
            "0x0003",
            "0x0004",
            "0x0019",
            "0x0102"
          ]
        },
        "242": {
          "profile_id": 41440,
          "device_type": "0x0061",
          "in_clusters": [],
          "out_clusters": [
            "0x0021"
          ]
        }
      }
    },
    "active_coordinator": false,
    "entities": [
      {
        "entity_id": "button.insta_gmbh_nexentro_pushbutton_interface_identify",
        "name": "Insta GmbH NEXENTRO Pushbutton Interface"
      }
    ],
    "neighbors": [],
    "routes": [],
    "endpoint_names": [
      {
        "name": "COLOR_DIMMER_SWITCH"
      },
      {
        "name": "COLOR_DIMMER_SWITCH"
      },
      {
        "name": "WINDOW_COVERING_CONTROLLER"
      },
      {
        "name": "unknown 97 device_type of 0xa1e0 profile id"
      }
    ],
    "user_given_name": null,
    "device_reg_id": "8dab62ebda6d89aff874774ea3d9f8e9",
    "area_id": "simon",
    "cluster_details": {
      "4": {
        "device_type": {
          "name": "COLOR_DIMMER_SWITCH",
          "id": 261
        },
        "profile_id": 260,
        "in_clusters": {
          "0x0000": {
            "endpoint_attribute": "basic",
            "attributes": {
              "0x0004": {
                "attribute_name": "manufacturer",
                "value": "Insta GmbH"
              },
              "0x0005": {
                "attribute_name": "model",
                "value": "NEXENTRO Pushbutton Interface"
              }
            },
            "unsupported_attributes": {}
          },
          "0x0003": {
            "endpoint_attribute": "identify",
            "attributes": {},
            "unsupported_attributes": {}
          }
        },
        "out_clusters": {
          "0x0003": {
            "endpoint_attribute": "identify",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0004": {
            "endpoint_attribute": "groups",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0005": {
            "endpoint_attribute": "scenes",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0006": {
            "endpoint_attribute": "on_off",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0008": {
            "endpoint_attribute": "level",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0019": {
            "endpoint_attribute": "ota",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0300": {
            "endpoint_attribute": "light_color",
            "attributes": {},
            "unsupported_attributes": {}
          }
        }
      },
      "5": {
        "device_type": {
          "name": "COLOR_DIMMER_SWITCH",
          "id": 261
        },
        "profile_id": 260,
        "in_clusters": {
          "0x0000": {
            "endpoint_attribute": "basic",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0003": {
            "endpoint_attribute": "identify",
            "attributes": {},
            "unsupported_attributes": {}
          }
        },
        "out_clusters": {
          "0x0003": {
            "endpoint_attribute": "identify",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0004": {
            "endpoint_attribute": "groups",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0005": {
            "endpoint_attribute": "scenes",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0006": {
            "endpoint_attribute": "on_off",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0008": {
            "endpoint_attribute": "level",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0019": {
            "endpoint_attribute": "ota",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0300": {
            "endpoint_attribute": "light_color",
            "attributes": {},
            "unsupported_attributes": {}
          }
        }
      },
      "7": {
        "device_type": {
          "name": "WINDOW_COVERING_CONTROLLER",
          "id": 515
        },
        "profile_id": 260,
        "in_clusters": {
          "0x0000": {
            "endpoint_attribute": "basic",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0003": {
            "endpoint_attribute": "identify",
            "attributes": {},
            "unsupported_attributes": {}
          }
        },
        "out_clusters": {
          "0x0003": {
            "endpoint_attribute": "identify",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0004": {
            "endpoint_attribute": "groups",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0019": {
            "endpoint_attribute": "ota",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0102": {
            "endpoint_attribute": "window_covering",
            "attributes": {},
            "unsupported_attributes": {}
          }
        }
      },
      "242": {
        "device_type": {
          "name": "unknown",
          "id": 97
        },
        "profile_id": 41440,
        "in_clusters": {},
        "out_clusters": {
          "0x0021": {
            "endpoint_attribute": "green_power",
            "attributes": {},
            "unsupported_attributes": {}
          }
        }
      }
    }
  }
}
```

</details>

<details>
<summary>Additional logs</summary>

I don't think the logs are necessary

</details>

**Additional context**

### PR DESCRIPTION
**Pull request by SimonIT**
This is my quirk which fixes #2084

I'm not sure about some of my design choices, so please leave a comment what do you think :)

This is the device:
Probi_57004000_1024_1024

This is their app to control it:
image

- As you can use the two inputs E1 and E2 for most of the functions individually I used `SHORT_PRESS` for E1 and `ALT_SHORT_PRESS` for E2. Not sure what would be better
- The next thing is, that I don't know what the Control setting of the app should do. It sends these I events
```
<Event zha_event[L]: device_ieee=84:2e:14:ff:fe:a4:80:c1, unique_id=84:2e:14:ff:fe:a4:80:c1:4:0x0008, device_id=a751568436a0fe45653ef0d2ceae20f3, endpoint_id=4, cluster_id=8, command=move, args=[<MoveMode.Down: 1>, 51, <bitmap8.0: 0>, <bitmap8.0: 0>], params=move_mode=MoveMode.Down, rate=51, options_mask=bitmap8.0, options_override=bitmap8.0>
<Event zha_event[L]: device_ieee=84:2e:14:ff:fe:a4:80:c1, unique_id=84:2e:14:ff:fe:a4:80:c1:4:0x0008, device_id=a751568436a0fe45653ef0d2ceae20f3, endpoint_id=4, cluster_id=8, command=move_with_on_off, args=[<MoveMode.Up: 0>, 51], params=move_mode=MoveMode.Up, rate=51>
<Event zha_event[L]: device_ieee=84:2e:14:ff:fe:a4:80:c1, unique_id=84:2e:14:ff:fe:a4:80:c1:4:0x0008, device_id=a751568436a0fe45653ef0d2ceae20f3, endpoint_id=4, cluster_id=8, command=stop, args=[<bitmap8.0: 0>, <bitmap8.0: 0>], params=options_mask=bitmap8.0, options_override=bitmap8.0>
```
  I mapped it to DIM, but I'm not sure if it's correct.
- I'm really confused about the scene mode. I don't know what it should do. It sendd some weird events:
```
<Event zha_event[L]: device_ieee=84:2e:14:ff:fe:a4:80:c1, unique_id=84:2e:14:ff:fe:a4:80:c1:4:0x0005, device_id=a751568436a0fe45653ef0d2ceae20f3, endpoint_id=4, cluster_id=5, command=store, args=[0x8CEE, 0], params=group_id=0x8CEE, scene_id=0>
<Event zha_event[L]: device_ieee=84:2e:14:ff:fe:a4:80:c1, unique_id=84:2e:14:ff:fe:a4:80:c1:5:0x0005, device_id=a751568436a0fe45653ef0d2ceae20f3, endpoint_id=5, cluster_id=5, command=recall, args=[0xD475, 0, 10], params=group_id=0xD475, scene_id=0, transition_time=10>
```
- For the switch mode I used a button. It sends a `toggle`-command and I wasn't sure what fits the best.

Feel free to leave some improvement thoughts. It's my first quirk

### CODE REVIEW

**Comment by MattWestb** [comment]
For some remotes i have used `BUTTON_1` and `BUTTON_2` in device automatons and the command is the same like `long press` for both. 

For the scene commands: The device is sending light controlling commands to its bounded group, recall and add to the  devices in the group and i think it shall working OK but need testing how to change the group (if its possible or random assigned by device then bring reset) and changing the scene number for more scenes.
I think this commands not good implanting as device automation but you must look how the device is using them and perhaps you is finding one good way doing it.

For the mode change we need to knowing the command set to the device from the app but its using BT and its not likely its the same as the Zigbee on if its can do it with  Zigbee commands.

Look if you can finding some posting in the net if some have founding it.

Great work !!!

**Comment by SimonIT** [comment]
Yes, the power source is correctly reported:
image
Is there a way to format the firmware number? In the app it is displayed as 0.0.52.5 which is basically 0x00001455 (from ha) in decimal.
I just found an explanation what each of the modes does:
[image](https://www.insta.de/files/Insta/media/product_docs/bedienungsanleitungen/bda_57004000_en.pdf)

**Comment by TheJulianJES** [comment]
A string representation for the firmware is often reported on the `Basic` cluster by the `sw_build_id` attribute.
The number shown on the device page is the numeric firmware version reported by the device when it asks ZHA for a firmware update. This can only be a number.

**Comment by MattWestb** [comment]
@SimonIT Did you trying asking Insta if thy have / can implanting the switch modes on Zigbee cluster ?
Perhaps they have it but not documented it and can being used if they is giving the information.
I think it shall being in there interest getting good support for there products on (Z)HA and other open systems.

Some manufactures is fixing there firmware so its being  ZCL complaint and / or making quirks in ZHA for getting them working well in our systems.

Also possible using [ZHA-Toolkit](https://github.com/mdeweerd/zha-toolkit) and scanning the device for not known commands and attributes but its not so easy knowing what they is doing and some device is not liking getting scanned (like some LIDL / tuya devices is bad behaving after being scanned and need being deletes and resetted after one scan).

**Comment by SimonIT** [comment]
I just wrote them yesterday some questions via email. We will see if the answer me.
If you look at my linked issue #2084 zha-toolkit scan of it. There is also `sw_build_id`.

**Comment by TheJulianJES** [comment]
Was there some response to the mail or is this ready to merge/for review as-is?

**Comment by SimonIT** [comment]
Sadly, there was no response from them.
That's how it looks:
image
I think it's ready

**Comment by javicalle** [comment]
The replacement part is exactly the same that the signature, isnt it?

If it is the case, I believe that you can ommit the replacement part and just define the `device_automation_triggers` to make it work. Could you check?

**Comment by SimonIT** [comment]
I tried that before, but then everything is empty:
image
image
image

**Review by TheJulianJES — APPROVED** [review]
LGTM. Thanks @SimonIT!

**Pull request merged**
