### PR TITLE
Update ts0601_motion.py

### PR DESCRIPTION
**Pull request by SentrySOB**
Add TZE200_auin8mzr Presence Sensor

### CODE REVIEW

**Comment by SentrySOB** [comment]
fingerprint: [{modelID: 'TS0601', manufacturerName: '_TZE200_auin8mzr'}],
        model: 'TS0601_motion_sensor',
        vendor: 'TuYa',
        description: 'Human presence sensor AIR',
        fromZigbee: [fz.tuya_motion_sensor],
        toZigbee: [tz.tuya_motion_sensor],
        exposes: [
            e.occupancy(),
            exposes.enum('o_sensitivity', ea.STATE_SET, Object.values(tuya.msLookups.OSensitivity)).withDescription('O-Sensitivity mode'),
            exposes.enum('v_sensitivity', ea.STATE_SET, Object.values(tuya.msLookups.VSensitivity)).withDescription('V-Sensitivity mode'),
            exposes.enum('led_status', ea.STATE_SET, ['ON', 'OFF']).withDescription('Led status switch'),
            exposes.numeric('vacancy_delay', ea.STATE_SET).withUnit('sec').withDescription('Vacancy delay').withValueMin(0)
                .withValueMax(1000),
            exposes.numeric('light_on_luminance_prefer', ea.STATE_SET).withDescription('Light-On luminance prefer')
                .withValueMin(0).withValueMax(10000),
            exposes.numeric('light_off_luminance_prefer', ea.STATE_SET).withDescription('Light-Off luminance prefer')
                .withValueMin(0).withValueMax(10000),
            exposes.enum('mode', ea.STATE_SET, Object.values(tuya.msLookups.Mode)).withDescription('Working mode'),
            exposes.numeric('luminance_level', ea.STATE).withDescription('Luminance level'),
            exposes.numeric('reference_luminance', ea.STATE).withDescription('Reference luminance'),
            exposes.numeric('vacant_confirm_time', ea.STATE).withDescription('Vacant confirm time'),
        ],
    },

**Comment by javicalle** [comment]
Is your device matching the quirk?
It is not the same signature that the one from PR #1593 

The DP seems to be correct. Are the entities created in HA? Any errors in the logs?

**Comment by SentrySOB** [comment]
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.6.0",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.9.12",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Australia/Sydney",
    "os_name": "Linux",
    "os_version": "5.15.41",
    "supervisor": "2022.05.3",
    "host_os": "Home Assistant OS 8.1",
    "docker_version": "20.10.14",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "version": "1.25.2",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "smart_thermostat": {
      "version": "2021.11.1",
      "requirements": []
    },
    "alexa_media": {
      "version": "3.11.3",
      "requirements": [
        "alexapy==1.25.5",
        "packaging>=20.3",
        "wrapt>=1.12.1"
      ]
    },
    "reaper": {
      "version": "0.2.2",
      "requirements": [
        "python-reaperdaw==0.0.7"
      ]
    },
    "weatherapi": {
      "version": "0.8",
      "requirements": []
    },
    "bureau_of_meteorology": {
      "version": "1.1.8",
      "requirements": []
    },
    "ai_thermostat": {
      "version": "0.9.3",
      "requirements": []
    },
    "watchman": {
      "version": "0.5.1",
      "requirements": [
        "prettytable==3.0.0"
      ]
    },
    "jq300": {
      "version": "0.10.2",
      "requirements": [
        "paho-mqtt==1.5.1"
      ]
    },
    "localtuya": {
      "version": "3.2.1",
      "requirements": []
    },
    "mqtt_discoverystream": {
      "version": "0.8",
      "requirements": []
    }
  },
  "integration_manifest": {
    "domain": "zha",
    "name": "Zigbee Home Automation",
    "config_flow": true,
    "documentation": "https://www.home-assistant.io/integrations/zha",
    "requirements": [
      "bellows==0.30.0",
      "pyserial==3.5",
      "pyserial-asyncio==0.6",
      "zha-quirks==0.0.75",
      "zigpy-deconz==0.16.0",
      "zigpy==0.45.1",
      "zigpy-xbee==0.14.0",
      "zigpy-zigate==0.7.4",
      "zigpy-znp==0.7.0"
    ],
    "usb": [
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*2652*",
        "known_devices": [
          "slae.sh cc2652rb stick"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*zigstar*",
        "known_devices": [
          "ZigStar Coordinators"
        ]
      },
      {
        "vid": "1CF1",
        "pid": "0030",
        "description": "*conbee*",
        "known_devices": [
          "Conbee II"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8A2A",
        "description": "*zigbee*",
        "known_devices": [
          "Nortek HUSBZB-1"
        ]
      },
      {
        "vid": "0403",
        "pid": "6015",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate+"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8B34",
        "description": "*bv 2010/10*",
        "known_devices": [
          "Bitron Video AV2010/10"
        ]
      }
    ],
    "codeowners": [
      "@dmulcahey",
      "@adminiuga"
    ],
    "zeroconf": [
      {
        "type": "_esphomelib._tcp.local.",
        "name": "tube*"
      },
      {
        "type": "_zigate-zigbee-gateway._tcp.local.",
        "name": "*zigate*"
      }
    ],
    "after_dependencies": [
      "usb",
      "zeroconf"
    ],
    "iot_class": "local_polling",
    "loggers": [
      "aiosqlite",
      "bellows",
      "crccheck",
      "pure_pcapy3",
      "zhaquirks",
      "zigpy",
      "zigpy_deconz",
      "zigpy_xbee",
      "zigpy_zigate",
      "zigpy_znp"
    ],
    "is_built_in": true
  },
  "data": {
    "ieee": "**REDACTED**",
    "nwk": 45611,
    "manufacturer": "_TZE200_auin8mzr",
    "model": "TS0601",
    "name": "_TZE200_auin8mzr TS0601",
    "quirk_applied": true,
    "quirk_class": "ts0601_motion.HumanPresenceSensorAIR",
    "manufacturer_code": 4098,
    "power_source": "Mains",
    "lqi": 120,
    "rssi": -70,
    "last_seen": "2022-06-02T11:56:07",
    "available": true,
    "device_type": "Router",
    "signature": {
      "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress|RxOnWhenIdle|MainsPowered|FullFunctionDevice: 142>, manufacturer_code=4098, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
      "endpoints": {
        "1": {
          "profile_id": 260,
          "device_type": "0x0107",
          "in_clusters": [
            "0x0000",
            "0x0004",
            "0x0005",
            "0x000c",
            "0x0400",
            "0x0406",
            "0xef00"
          ],
          "out_clusters": [
            "0x000a",
            "0x0019"
          ]
        }
      }
    },
    "entities": [
      {
        "entity_id": "binary_sensor.en_suite_occupancy_sensor_occupancy",
        "name": "_TZE200_auin8mzr TS0601"
      }
    ],
    "neighbors": [],
    "endpoint_names": [
      {
        "name": "OCCUPANCY_SENSOR"
      }
    ],
    "user_given_name": "En suite Occupancy Sensor",
    "device_reg_id": "c15fd378f913b649b11dacf41de11678",
    "area_id": "ensuite"
  }
}

**Comment by SentrySOB** [comment]
Yes. The device is matching the new quirk name. I changed it to make sure it was finding the changes.

No Errors I can see in the logs. 

I did at one point have Illuminance showing up in HA. Also had a switch entity using TuyaOnOff for the LED. The switch didn't work at all controlling the LED and caused issues with Flake8 and other tests so removed that. Not sure why Illuminance is not showing up at all anymore. It was showing up greyed out, then was showing up in blue yet never changed value from 1lux. Now not showing at all. Only entity showing is Occupancy.

**Comment by SentrySOB** [comment]
LQI and RSSI also showing.

**Comment by javicalle** [comment]
If you map the DP_105 to the `AnalogInput`, set the `present_value` attribute:
```
        105: DPToAttributeMapping(
            TuyaAnalogInput.ep_attribute,
            "present_value",
        ),
```

Your device must show at least 3 devices in HA:
* Occupancy
* Illuminance
* AnalogInput (whatever that is in HA)

All the other reports are mapped as attributes of cluster `TuyaHumanPresenceSensorAIRManufCluster`. 
You can update the values of the DPs (those that allow it) by setting their value from the device view, managing the cluster attributes.
If the relationship between the DP and its functionality is clear, you can assign descriptive names to the attributes (eg: `dp_103`--> `vacancy_delay`)

Enabling the debug logging you can get info about the reported values from device:
* https://www.home-assistant.io/integrations/zha/#debug-logging
This can be usefull for testing device behavior in realtime, and also can give us some clues with what happens to the illuminance entity.

**Comment by SentrySOB** [comment]
I copied and pasted so I have no idea how correct any of the info for the DP is. Looking at the DP's don't think there is any analogue inputs so have changed that to match the others.  Occupancy shows up and is working. Luminance is showing up yet doesn't change value at all. There are then the 2 hidden entities that are LQI and RSSI. 




"You can update the values of the DPs (those that allow it) by setting their value from the device view, managing the cluster attributes."   Where is the device view? I can't see any DP values in Settings/Devices and Services/Devices/

Have added the lines in the config.yaml for logging. Can't find anything in the logs about that sensor. Tried a bunch of searches and nothing brings up any results related to that sensor or the DP's.

**Pull request closed without merging**
