### PR TITLE
added power configuration to motion aq2b

### PR DESCRIPTION
**Pull request by sarakha63**
I guess power configuration was forgotten on alternative quirk for motion aq2.

I tested this on 5 devices i had which regsitered with this quirk and never reported battery. And with this simple modification now they all report there battery fluently and constitently

regards

### CODE REVIEW

**Comment by Adminiuga** [comment]
please rebase against current dev so only commit related to this PR is present. Those thermostat commits are completely unrelated.

**Review by Adminiuga — CHANGES_REQUESTED** [review]
Please rebase against current dev or only include related commit in the PR

**Comment by sarakha63** [comment]
I dont understand what happened. As if you look at file changer there is only one file changed.

Ill check

**Comment by sarakha63** [comment]
i rebased everything. Now it should be good

**Review by Adminiuga — APPROVED** [review]
lgtm

**Comment by Adminiuga** [comment]
BTW, it probably happened because you are submitting the change from the dev branch of you fork. You'll run into same issues next time you submit a PR.
before starting work on a new feature/fix, do a `git checkout -b my-fix-for-something dev` to create a new branch and work in there.

**Comment by sarakha63** [comment]
youre right. totally right

**Pull request merged**
