### PR TITLE
Add Tuya soil sensor variant `_TZE200_9cqcpkgb`

### PR DESCRIPTION
**Pull request by cooki371**
## Proposed change

Adding the soil sensor variant _TZE200_9cqcpkgb. 
Amazon [Link](https://amzn.eu/d/00WuY5P)

## Checklist

- [x] The changes are tested and work correctly
- [ ] `pre-commit` checks pass / the code has been formatted using Black
- [ ] Tests have been added to verify that the new code works

### CODE REVIEW

**Review by javicalle — APPROVED** [review]
LGTM

**Comment by javicalle** [comment]
Adding a link to the device vendor or similar would help others to identify the device.

**Comment by cooki371** [comment]
Added an amazon link to the device I tested it with.

**Review by TheJulianJES — APPROVED** [review]
Thanks!

**Pull request merged**
