### PR TITLE
Added py extension + fixed device type for Osram AC05347

### PR DESCRIPTION
**Pull request by TheJulianJES**
Fix for #485 
The file was missing the ".py" extension
The device type was also incorrect.

### CODE REVIEW

**Comment by TheJulianJES** [comment]
It seems like the tests are failing now, because it has the ".py" extension (I guess they didn't run properly before).
"zll.DeviceType.COLOR_DIMMABLE_LIGHT" doesn't exist. I guess COLOR_LIGHT was meant to be used?
(Will push more commits to fix this soon.)
Would be nice to have the device signature though - I wasn't able to find it in any issues.
Maybe @Goldwing1973 can post the signature?

**Comment by TheJulianJES** [comment]
From searching online, it seems like this is a "Tunable White" light, so a COLOR_TEMPERATURE_LIGHT.
The device signature would really help.

**Comment by Goldwing1973** [comment]
> 
> 
> From searching online, it seems like this is a "Tunable White" light, so a COLOR_TEMPERATURE_LIGHT.
> The device signature would really help.

I will pair one in ZHA and look for the signature

**Comment by TheJulianJES** [comment]
Thanks!

**Comment by Goldwing1973** [comment]
> 
> 
> Thanks!

{
  "node_descriptor": "NodeDescriptor(byte1=1, byte2=64, mac_capability_flags=142, manufacturer_code=48042, maximum_buffer_size=64, maximum_incoming_transfer_size=0, server_mask=0, maximum_outgoing_transfer_size=0, descriptor_capability_field=3)",
  "endpoints": {
    "3": {
      "profile_id": 49246,
      "device_type": "0x0220",
      "in_clusters": [
        "0x0000",
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006",
        "0x0008",
        "0x0300",
        "0x1000",
        "0xfc0f"
      ],
      "out_clusters": [
        "0x0019"
      ]
    }
  },
  "manufacturer": "unk_manufacturer",
  "model": "unk_model",
  "class": "zigpy.device.Device"
}

This is what i get from Zigbee device signature in ZHA

**Comment by TheJulianJES** [comment]
Changed the device type to ZLL COLOR_TEMPERATURE_LIGHT now.
This should fix what was "broken" in #485.

**Comment by TheJulianJES** [comment]
@Goldwing1973 I saw that your device also paired with "unk_model" and "unk_manufacturer".
The implementation of the quirk will NOT fix this.
This quirk only allows for the use of the "save_defaults" command.
The bug you're experiencing is most likely https://github.com/home-assistant/core/issues/35534

**Comment by Goldwing1973** [comment]
> 
> 
> @Goldwing1973 I saw that your device also paired with "unk_model" and "unk_manufacturer".
> The implementation of the quirk will NOT fix this.
> This quirk only allows for the use of the "save_defaults" command.
> The bug you're experiencing is most likely [home-assistant/core#35534](https://github.com/home-assistant/core/issues/35534)
> 
> #491 was related to this PR.
> Like was mentioned in [#491 (comment)](https://github.com/zigpy/zha-device-handlers/pull/491#issuecomment-694353683), it's just a different device signature.
> If @makuser wants, I can also add "(OSRAM, "CLA60 TW OSRAM")" for this quirk.
> This _should_ work.

Does that mean i won't be able to control the light either? because that is the reason why i *tried and failed miserably* to make the quirk.
When i add it now, i do see a switch for the device, but when i flip it it returns to the off state a second later.

**Comment by TheJulianJES** [comment]
You didn't fail miserably!
It were just two tiny things that were wrong.
Your quirk allows to send the "save_defaults" command to the Osram light. This sets the current set light state as the startup state.
The issue you're experiencing is likely because you're running one of these experimental radios (https://www.home-assistant.io/integrations/zha/#experimental-support-for-additional-zigbee-radio-modules).
This is the bug report you wanna follow: https://github.com/home-assistant/core/issues/35534
You can check the (debug) logs to see if the issue is similar/the same.

**Pull request merged**
