### PR TITLE
Add support for Tuya Neo Outdoor Siren with Solar (TZE200_nlrfgpny)

### PR DESCRIPTION
**Pull request by miawgogo**
## Proposed change

Adds support for the Neo Outdoor siren to ZHA and resolves issue #2375

I'll fill this in as i get more of it done

## Checklist

- [ ] The changes are tested and work correctly
- [ ] `pre-commit` checks pass / the code has been formatted using Black
- [ ] Tests have been added to verify that the new code works

### CODE REVIEW

**Comment by lboue** [comment]
@ioangogo Can you fix the issues so we can merge?

**Comment by miawgogo** [comment]
its currently a draft?

**Comment by dominikamann** [comment]
Is there any news on this topic? I would like to use the siren "out of the box" with HomeAssistant Zigbee. Unfortunately, there are very few sirens on the market. The integration of this Zigbee Device would be a real asset for HomeAssistant. I have already bought one. Thank you!

**Comment by harishvelli** [comment]
Interested in this, would be great to make this work natively with zha.

**Comment by nils-82** [comment]
Interested in this as well, that would be great to make this work natively with zha.

**Comment by liouma** [comment]
Interested in this as well, that would be great to make this work natively with zha.

**Pull request closed without merging**
