### PR TITLE
Adding partial support for MOES MS-105B (Double DIY Dimmer)

### PR DESCRIPTION
**Pull request by davefx**
Basic on/off works for 1st and 2nd light.
I would need help in order to make the brightness to be fully working as well.

The device is already supported by Zigbee2Mqtt: https://www.zigbee2mqtt.io/devices/MS-105B.html

### CODE REVIEW

**Comment by davefx** [comment]
Related to #1233

**Comment by davefx** [comment]
The current status of the PR provides support to the first of the two channels.
I've tried to make several changes to get and/or set the status of the second channel, with no luck.

I'm a bit lost about what to do now, so I've recovered some logs to see if we can make this device to fully work with a bit of help from you.

With the first light off, and the second light already on (previously activated via the wall switch), I manually turned off the second light from the wall switch. 
First I got several repeated indications for 6 seconds, that seem to be related to the change of light status:
```
2021-12-27 09:29:16 DEBUG (MainThread) [zigpy_deconz.api] APS data indication response: [33, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|2: 34>, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x0000>, 1, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x3562>, 1, 260, 61184, b'\tH\x02\x01p\x07\x01\x00\x01\x00', 0, 175, 255, 233, 96, 18, 0, -55]
2021-12-27 09:29:16 DEBUG (MainThread) [zigpy.zcl] [0x3562:1:0xef00] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=CLUSTER_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=72 command_id=2>
2021-12-27 09:29:16 DEBUG (MainThread) [zigpy.zcl] [0x3562:1:0xef00] ZCL request 0x0002: [Command(status=1, tsn=112, command_id=263, function=0, data=[1, 0])]
2021-12-27 09:29:16 DEBUG (MainThread) [zigpy_deconz.api] 'aps_data_indication' response from <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x3562>, ep: 1, profile: 0x0104, cluster_id: 0xef00, data: b'09480201700701000100'

```

After that, I received these other indications (that could be brightness-related...)
```
2021-12-27 09:29:17 DEBUG (MainThread) [zigpy_deconz.api] APS data indication response: [36, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|2: 34>, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x0000>, 1, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x3562>, 1, 260, 61184, b'\tI\x02\x01q\x08\x02\x00\x04\x00\x00\x03\xd0', 0, 175, 255, 233, 96, 18, 0, -55]
2021-12-27 09:29:17 DEBUG (MainThread) [zigpy.zcl] [0x3562:1:0xef00] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=CLUSTER_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=73 command_id=2>
2021-12-27 09:29:17 DEBUG (MainThread) [zigpy.zcl] [0x3562:1:0xef00] ZCL request 0x0002: [Command(status=1, tsn=113, command_id=520, function=0, data=[4, 0, 0, 3, 208])]
2021-12-27 09:29:17 DEBUG (MainThread) [zigpy_deconz.api] 'aps_data_indication' response from <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x3562>, ep: 1, profile: 0x0104, cluster_id: 0xef00, data: b'094902017108020004000003d0'
2021-12-27 09:29:36 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_request (27, 1, 0, <DeconzAddressEndpoint address_mode=2 address=0x3562 endpoint=1>, 260, 61184, 1, b'\x05\x02\x10\x00\x00\x00\x00\x02\x01\x00\x01\x01', 2, 0)
2021-12-27 09:29:36 DEBUG (MainThread) [zigpy_deconz.api] Request id: 0x01 'aps_data_confirm' for <DeconzAddressEndpoint address_mode=ADDRESS_MODE.NWK address=0x3562 endpoint=1>, status: 0x00
2021-12-27 09:29:36 DEBUG (MainThread) [zigpy_deconz.api] APS data indication response: [30, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|2: 34>, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x0000>, 1, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x3562>, 1, 260, 61184, b'\x0c\x02\x10\x00\x0b\x00\x00', 0, 175, 255, 241, 96, 18, 0, -52]
2021-12-27 09:29:36 DEBUG (MainThread) [zigpy.zcl] [0x3562:1:0xef00] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=True is_reply=True disable_default_response=False> manufacturer=4098 tsn=0 command_id=Command.Default_Response>
2021-12-27 09:29:36 DEBUG (MainThread) [zigpy_deconz.api] 'aps_data_indication' response from <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x3562>, ep: 1, profile: 0x0104, cluster_id: 0xef00, data: b'0c0210000b0000'
2021-12-27 09:29:36 DEBUG (MainThread) [zigpy_deconz.api] APS data indication response: [36, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|2: 34>, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x0000>, 1, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x3562>, 1, 260, 61184, b'\tJ\x02\x01r\x02\x02\x00\x04\x00\x00\x03\xe4', 0, 175, 255, 241, 96, 18, 0, -52]
2021-12-27 09:29:36 DEBUG (MainThread) [zigpy.zcl] [0x3562:1:0xef00] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=CLUSTER_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=74 command_id=2>
2021-12-27 09:29:36 DEBUG (MainThread) [zigpy.zcl] [0x3562:1:0xef00] ZCL request 0x0002: [Command(status=1, tsn=114, command_id=514, function=0, data=[4, 0, 0, 3, 228])]
2021-12-27 09:29:36 DEBUG (MainThread) [zigpy_deconz.api] 'aps_data_indication' response from <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x3562>, ep: 1, profile: 0x0104, cluster_id: 0xef00, data: b'094a02017202020004000003e4'

[... several repetitions of the last indication for 5 seconds ...]

2021-12-27 09:29:41 DEBUG (MainThread) [zigpy_deconz.api] APS data indication response: [36, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|2: 34>, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x0000>, 1, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x3562>, 1, 260, 61184, b'\tJ\x02\x01r\x02\x02\x00\x04\x00\x00\x03\xe4', 0, 175, 255, 241, 96, 18, 0, -52]
2021-12-27 09:29:41 DEBUG (MainThread) [zigpy.zcl] [0x3562:1:0xef00] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=CLUSTER_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=74 command_id=2>
2021-12-27 09:29:41 DEBUG (MainThread) [zigpy.zcl] [0x3562:1:0xef00] ZCL request 0x0002: [Command(status=1, tsn=114, command_id=514, function=0, data=[4, 0, 0, 3, 228])]
2021-12-27 09:29:41 DEBUG (MainThread) [zigpy_deconz.api] 'aps_data_indication' response from <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x3562>, ep: 1, profile: 0x0104, cluster_id: 0xef00, data: b'094a02017202020004000003e4'

``` 

Then, I turned it on again from the wall switch. I received this following event lots of times for 7 seconds, which seems to correspond to the status on/off of the two lights:
```
2021-12-27 09:39:46 DEBUG (MainThread) [zigpy_deconz.api] APS data indication response: [33, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|2: 34>, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x0000>, 1, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x3562>, 1, 260, 61184, b'\tR\x02\x01u\x07\x01\x00\x01\x01', 0, 175, 255, 135, 97, 18, 0, -55]
2021-12-27 09:39:46 DEBUG (MainThread) [zigpy.zcl] [0x3562:1:0xef00] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=CLUSTER_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=82 command_id=2>
2021-12-27 09:39:46 DEBUG (MainThread) [zigpy.zcl] [0x3562:1:0xef00] ZCL request 0x0002: [Command(status=1, tsn=117, command_id=263, function=0, data=[1, 1])]
2021-12-27 09:39:46 DEBUG (MainThread) [zigpy_deconz.api] 'aps_data_indication' response from <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x3562>, ep: 1, profile: 0x0104, cluster_id: 0xef00, data: b'09520201750701000101'
```

And then I received several indications that seem to correspond to the change of brightness (as the light doesn't turn on/off immediately, but does it gradually). Also, if you keep the wall switch down, the dimmer starts changing the brightness.
```
2021-12-27 09:39:47 DEBUG (MainThread) [zigpy_deconz.api] APS data indication response: [36, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|2: 34>, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x0000>, 1, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x3562>, 1, 260, 61184, b'\tV\x02\x01y\x08\x02\x00\x04\x00\x00\x02\xc5', 0, 175, 255, 135, 97, 18, 0, -54]
2021-12-27 09:39:47 DEBUG (MainThread) [zigpy.zcl] [0x3562:1:0xef00] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=CLUSTER_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=86 command_id=2>
2021-12-27 09:39:47 DEBUG (MainThread) [zigpy.zcl] [0x3562:1:0xef00] ZCL request 0x0002: [Command(status=1, tsn=121, command_id=520, function=0, data=[4, 0, 0, 2, 197])]
2021-12-27 09:39:47 DEBUG (MainThread) [zigpy_deconz.api] 'aps_data_indication' response from <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x3562>, ep: 1, profile: 0x0104, cluster_id: 0xef00, data: b'095602017908020004000002c5'
2021-12-27 09:39:48 DEBUG (MainThread) [zigpy_deconz.api] APS data indication response: [36, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|2: 34>, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x0000>, 1, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x3562>, 1, 260, 61184, b'\tW\x02\x01z\x08\x02\x00\x04\x00\x00\x02\x9e', 0, 175, 255, 135, 97, 18, 0, -53]
2021-12-27 09:39:48 DEBUG (MainThread) [zigpy.zcl] [0x3562:1:0xef00] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=CLUSTER_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=87 command_id=2>
2021-12-27 09:39:48 DEBUG (MainThread) [zigpy.zcl] [0x3562:1:0xef00] ZCL request 0x0002: [Command(status=1, tsn=122, command_id=520, function=0, data=[4, 0, 0, 2, 158])]
2021-12-27 09:39:48 DEBUG (MainThread) [zigpy_deconz.api] 'aps_data_indication' response from <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x3562>, ep: 1, profile: 0x0104, cluster_id: 0xef00, data: b'095702017a080200040000029e'

```

**Comment by MattWestb** [comment]
The repeating of first command is because ZHA is not replaying with default response then the device is sending commands to the system.
Its one user that have doing much work fixing the tuya DP dimmers (hi have getting all switches working OK) but hi dont have tuya  dimmers for trying the function on so help is more then welcome. 
Taking one look at https://github.com/zigpy/zha-device-handlers/issues/1033 and hope you and other can hgetting it fixed.

**Comment by davefx** [comment]
Checking the Zigbee2Mqtt support for this device I've found out that the second light is controlled through datapoints 7 (for on/off) and 8 (for brightness).

I've changed the quirk so the second light is in 7, and the on/off status and command works.
However, the brightness still doesn´t and I'm not sure about how to get the brightness working in datapoint 8, keeping the on-off in datapoint 7 and joining them into a single entity.

Also, zigbee2mqtt sends an on-off order when setting brightness. I see this would be also needed in ZHA, as setting the brightness > 0 marks the light on in Home Assistant, but it doesn't actually turn on the light.

@MattWestb Could you lend me a hand about this?

**Comment by davefx** [comment]
Sorry, I missed all the already-done work in #1033 by @javicalle .

Nevertheless, I honestly think it's better to have a partially working device than a no-working device at all, so I think it could be a good thing to merge this PR meanwhile.

**Comment by MattWestb** [comment]
Great work done !!

I have thinking the same with both tuya DP multi gang Switches and dimmers and have adding some so users can have little use of there devices and its much better then putting them in the box for chinese junc.

Now the switches is working OK and the dimmers in in the row !!

If you like and can doing testing its very likely we can getting all devices working OK in ZHA then coding and cant testing is not working well as also having the device and cant doing coding is also not working ;-)

**Comment by nworbneb** [comment]
I'm not sure what @javicalle timeline is but they are working on a permanent framework to support this.  In the meantime the quirk posted in #1033 has been working perfectly for me for the last few weeks for both gangs.

**Comment by javicalle** [comment]
I wanted to inform that I have released PR #1247 that aims to solve the same problem as this PR of yours.
I am aware of the effort and work required to carry out the PR, but onstantly I believe that the approach of PR #1247 will facilitate the inclusion of new devices in a more agile way

I hope you understand my motives. In no case do I intend to disparage your work.

Regards.

**Comment by dmulcahey** [comment]
Let’s use the approach from #1247

**Comment by dmulcahey** [comment]
As stated. Lets use the approach outlined above. Thanks for the contribution anyhow. If you would like to continue with this please update it to follow the new approach and submit a new PR. Thanks!!

**Pull request closed without merging**
