### PR TITLE
Update ts0601_motion.py

### PR DESCRIPTION
**Pull request by SentrySOB**
Added  _TZE200_auin8mzr. Motion detection working. Quirk needs work to get all features operational.

https://www.zigbee2mqtt.io/devices/TS0601_motion_sensor.html

Link to device with full list of Exposes. Will try to get it working, new to this so any help appreciated.

### CODE REVIEW

**Comment by javicalle** [comment]
You probably will need a new `MmwRadarManufCluster` definition (maybe `TuyaPirSensorManfCluster`?). You can replicate the actual one with the DP and replacements needed for your device.

According to herdsman-converters, that device exposes this values:
* https://github.com/Koenkk/zigbee-herdsman-converters/blob/a1b6a7ef34eaf1b337a071a80f2b336986fb29c0/devices/tuya.js#L2058-L2080

You can get the value <--> DP relationship from:
* https://github.com/Koenkk/zigbee-herdsman-converters/blob/a1b6a7ef34eaf1b337a071a80f2b336986fb29c0/lib/tuya.js#L530-L540

Probably you can use:
* DP_1 mapped to `TuyaOccupancySensing`
* DP_109 mapped to `TuyaIlluminanceMeasurement`
* DP_110 mapped to `TuyaOnOff` (from zhaquirks.tuya.mcu)

And the other ones as attributes of your new cluster, just like:
https://github.com/zigpy/zha-device-handlers/blob/4c067ac7af513daa953f0de83c70209520b15926/zhaquirks/tuya/ts0601_motion.py#L135-L151

**Comment by SentrySOB** [comment]
Thx. Will see how I go.

**Comment by SentrySOB** [comment]
Not sure where the hex codes are meant to come from to link to the DP's.

{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress|RxOnWhenIdle|MainsPowered|FullFunctionDevice: 142>, manufacturer_code=4417, maximum_buffer_size=66, maximum_incoming_transfer_size=66, server_mask=10752, maximum_outgoing_transfer_size=66, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0301",
      "in_clusters": [
        "0x0000",
        "0x0004",
        "0x0005",
        "0x0201",
        "0x0204",
        "0xef00"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    },
    "242": {
      "profile_id": 41440,
      "device_type": "0x0061",
      "in_clusters": [],
      "out_clusters": [
        "0x0021"
      ]
    }
  },
  "manufacturer": "_TZE200_2ekuz3dz",
  "model": "TS0601",
  "class": "ts0601_electric_heating.MoesBHT_GPP"
}

The device signature doesn't have enough outputs to connect to all the exposes listed.

Thinking will be easier to go back to Zigbee2MQTT

**Comment by javicalle** [comment]
> Not sure where the hex codes are meant to come from to link to the DP's.

In the attributes definition? They are random values. I get `0xEF` + DP in Hex. But they can be any value (that does not exist previously in the cluster).


> The device signature doesn't have enough outputs to connect to all the exposes listed.

No, definitely not.
Z2M has figured out how to expose those 'settings' but in ZHA it's not straightforward and requires implementation.

**Comment by SentrySOB** [comment]
Ok Thx.  

The signature has 7 inputs exposed in the signature.

"0x0000",
"0x0004",
"0x0005",
"0x000c",
"0x0400",
"0x0406",
"0xef00"

I'm guessing that 0, 4, 5 and 61184 are 

Basic
Groups
Scenes
TuyaNewManufCluster

How do I find the input clusters for 12, 1024 and 1030?

Or do I have this totally wrong?

Is there some kind of documentation anywhere to assist? I feel like Linus on his Linux daily driver test where if you already know how to do it then it's fine, yet if don't already know....


I now have the luminance reading 1 lux regardless of brightness. Better than it being greyed out I guess, yet not very useful still.

**Pull request closed without merging**
