### PR TITLE
Convert Sinope files to new style AttributeDefs

### PR DESCRIPTION
**Pull request by claudegel**
## Proposed change

Update Sinope file format to new style AttributeDefs for thermostat.py, switch.py and sensor.py
Light.py is already modified in another PR #3313

## Checklist

- [x] The changes are tested and work correctly
- [x] `pre-commit` checks pass / the code has been formatted using Black
- [ ] Tests have been added to verify that the new code works

### CODE REVIEW

**Comment by claudegel** [comment]
Can anybody explain what's wrong and how to fix please
Couldn't combine from non-existent path 'coverage*/.coverage*'

**Comment by TheJulianJES** [comment]
It seems to be an issue with our CI at the moment, don't worry about it for now.
EDIT: Fixed now.

**Comment by claudegel** [comment]
Thank's

**Review by TheJulianJES — APPROVED** [review]
LGTM, thanks!
Hopefully didn't miss anything 😅

**Pull request merged**
