### PR TITLE
Extend Xiaomi wall switch support

### PR DESCRIPTION
**Pull request by sanyatuning**
Add support for xiaomi wall switches
- natural wire or fire wire version
- 1 or 2 button

### CODE REVIEW

**Comment by sanyatuning** [comment]
@dmulcahey or @Adminiuga can you pls review this?

**Comment by dmulcahey** [comment]
I’ll get this taken care of before I cut the release before the beta

David F. Mulcahey

**Comment by Adminiuga** [comment]
Looks good to me. So Xiaomi wants the request always to come from src endpoint 1 ?

**Comment by sanyatuning** [comment]
yes, always from 1, don't know why

**Pull request merged**
