### PR TITLE
create button.py

### PR DESCRIPTION
**Pull request by weihuan1111**

### CODE REVIEW

**Review by weihuan1111 — COMMENTED** [review]
update

**Review by weihuan1111 — COMMENTED** [review]
update

**Review by weihuan1111 — COMMENTED** [review]
update

**Review by weihuan1111 — COMMENTED** [review]
update

**Comment by weihuan1111** [comment]
@dmulcahey please help to review the merge require,thanks

**Comment by weihuan1111** [comment]
@dmulcahey  hello, can you tell me how to make this commit take effect?

**Comment by dmulcahey** [comment]
Update to the latest HA

**Comment by puddly** [comment]
@weihuan1111 in this PR, did you remove `LevelControl` and replace the `Ota` output cluster with `Basic` intentionally, or was this a mistake? The device supports OTA.

**Comment by weihuan1111** [comment]
@puddly What is the meaning of replacement in the code? Is it neccessary to remove the repacement?

**Comment by dmulcahey** [comment]
Replacement allows you to change standard clusters for modified versions. It also allows you to add or remove clusters if they aren’t functional or if they’re missing. Lots of devices don’t follow the specifications and we need a way to correct them

**Comment by weihuan1111** [comment]
> Replacement allows you to change standard clusters for modified versions. It also allows you to add or remove clusters if they aren’t functional or if they’re missing. Lots of devices don’t follow the specifications and we need a way to correct them

OK， i will remove the repacement and test it

**Comment by MattWestb** [comment]
For one Zigbbee Light controller is sending all commands from out cluster so OnOff and Level control must being on the out part.

One very good example of bad devices is tuya TS004F that have both on in and out and is making ZHA thinking its one light that can being controller from the GUI = false then its one remote that only sending commands.
In the quirk we have deleting them in the replacement from the in and its sending commands OK from the out cluster and ZHA is not making one light in the GUI that  can sending commands to it (that is not possible then its one sleeping device) and all is working OK (the group cluster is little special then the device is not supporting binding and need it as in cluster for adding groups like lights but its one other story).

**Pull request merged**
