### PR TITLE
Add Battery quirk for Zen thermostat

### PR DESCRIPTION
**Pull request by Adminiuga**
Add Battery quirk for Zen Within Zen-01 thermostat.

### CODE REVIEW

**Comment by dmulcahey** [comment]
```
lint run-test: commands[0] | flake8
240./zhaquirks/zen/thermostat.py:1:1: D200 One-line docstring should fit on one line with quotes
241./zhaquirks/zen/thermostat.py:31:38: E231 missing whitespace after ','
242ERROR: InvocationError for command /home/travis/build/dmulcahey/zha-device-handlers/.tox/lint/bin/flake8 (exited with code 1)
```

**Comment by dmulcahey** [comment]
still don't know what happened to travis... it's running just not reporting correctly

**Comment by Adminiuga** [comment]
Running `black` insist on removing the white space on like 29, but then lint is not happy.

**Comment by Adminiuga** [comment]
Nvm. For some reason the installed one behaves differently from pre-commit one.

**Pull request merged**
