### PR TITLE
Add iCasa wall mounted remote support: ICZB-KPD12, ICZB-KPD14S, ICZB-KPD18S 

### PR DESCRIPTION
**Pull request by Emrvb**
This pull requests replaces https://github.com/zigpy/zha-device-handlers/pull/855

I have made an initial implementation for support for the icasa wall mounted zigbee remotes ICZB-KPD12, ICZB-KPD14S and ICZB-KPD18S. Remotes are mentioned here #503

ICZB-KPD12: This remote has ON and OFF buttons (hold for dimming up/down) 
ICZB-KPD14S: This remote has ON and OFF buttons (hold for dimming up/down) and 2 SCENE buttons (hold for storing, push to recall).
ICZB-KPD18S: This remote has ON and OFF buttons (hold for dimming up/down) and 6 SCENE buttons (hold for storing, push to recall).

I myself am not very familiar with zigpy in general and the device handlers in particular, so I'm left with a few questions I would like answered in order to complete this device handler. I'll raise issues for the shortly.

### CODE REVIEW

**Comment by Hedda** [comment]
@Emrvb Any updates on this support quirk for icasa wall-mounted remotes Zigbee devices for ZHA?

**Comment by dmulcahey** [comment]
Can we finish this or shall I close it?

**Comment by Emrvb** [comment]
@dmulcahey

I would love to make this ready for merge. Do you mind having a look at #1040 and #1041? They went stale and I didn't want to bump them unless somebody was interested in merging this.

**Comment by dmulcahey** [comment]
The button events are currently all over the place. There is no spec for things like double press, long hold / release etc. So I am ok w/ the caching mentioned in #1041 to distinguish the different buttons. 

As for the scene stuff mentioned in #1040 : We don’t currently support Zigbee scenes officially at all. I am sure you can set them up and manage them (potentially) if you issue all of the raw commands. Using names like store and recall may convey the false impression that we do support them so I am in favor of avoiding those names.

**Comment by Emrvb** [comment]
Regarding #1040, in my opinion labeling the events like "Recall Scene 1 Pressed" and "Store Scene 1 Pressed" doesn't imply any support from Home Assistant but could prevent some confusion for owners of this device. Then again, I am probably biased.

This is the last time I'll advocate for the labeling. If you prefer the implementation as is, let me know and I'll get it ready for merge.

Offtopic: these panels are pretty neat. It's very easy to bind devices from Home Assistant, I was pleasantly surprised this was implemented in the firmware. Certainly beats holding your panel and in-wall devices next to each other.

**Comment by Emrvb** [comment]
@dmulcahey I tried to make a merge as easy as possible by testing against the current dev branch. I modified the device_automation_triggers to work with PARAMS instead of ARGS, but now the tests fail because of my abuse of the command params (the ones where I overload the stop command with move_on_off parameters).

I can either remove these triggers (and the custom cluster) or you could decide to merge anyway. Due to circumstances I'm currently unable to test this quirk in home assistant.

**Comment by Hedda** [comment]
Should probably be left open until at least open PR is closed -> https://github.com/zigpy/zha-device-handlers/pull/1039

**Comment by Emrvb** [comment]
@Hedda 

No updates from me, I was under the impression this could have been merged as is. Any suggestions for improvements are welcome. I see a test failed, if I have some free time this week I'll have a look at that.

**Comment by TheJulianJES** [comment]
(PR also needs to rebased)

**Comment by Hedda** [comment]
> (PR also needs to rebased)

@Emrvb can  you please rebase this PR?

**Comment by Hedda** [comment]
Any updates on this PR?

**Comment by Emrvb** [comment]
Sorry for my absence, I've been swamped both at work and at home.

I'll try to have a look into this soon. My own HA is severely outdated, so I would have to get to that first. I did notice some preliminary support for the events these devices emit has been added already.

**Pull request closed without merging**
