### PR TITLE
Quirks for FeiBit light switches

### PR DESCRIPTION
**Pull request by yruss972**
* FNB56-ZSW01LX2.0
* FNB56-ZSW02LX2.0
* FNB56-ZSW03LX2.0

Switches also marketed by ZemiSmart under the KS-811 model

### CODE REVIEW

**Comment by dmulcahey** [comment]
We’re these not working as is? I only see profile swaps from ZLL to ZHA. This shouldn’t be needed. What is the difference in experience in ZHA with and without this change?

**Comment by yruss972** [comment]
@dmulcahey Thanks for taking a look. 

I admit this was a break glass attempt to get a switch working and I don't understand myself why it helped.

These switches have been working well for me in Deconz for years.
I switched over to ZHA via Raspbee a couple months ago and had about 12 of them working OOTB, though ZHA tends to show some irrelevant options.
Last week I added two more of these switches (2x1 gang) in one room and only one would work at a time- really weird.
I have multiple working routers in the same room and more in adjacent rooms so I didn't suspect any reception issues.
Replacing the HW didn't make any difference and I successfully paired the same HW somewhere else.

I originally thought the issue was some routing limitation since this was probably my 33rd device on the network. I tried adding via a working device in the room, etc. but it doesn't seem to mean anything with a zigpy-deconz backend? Everything always shows as connected directly to the coordinator.

When nothing worked, I wrote a custom quirk, originally not even swapping from ZLL to ZHA. Only when I made the swap to ZHA, did I manage to successfully pair both switches in the room.

Since it worked I figured I'd share. Maybe there is some added or different resilience/retry logic which only takes effect via the ZHA code path?

**Comment by dmulcahey** [comment]
Routers will change that limit. I am at 160 devices in prod

**Comment by yruss972** [comment]
I really have no idea- I've got some 20+ routers out of ~32/33 devices.
The error messages I'm getting look the same as before but on a different device in a completely different part of the house:
```
2022-09-12 21:04:55.377 WARNING (MainThread) [homeassistant.components.zha.core.channels.base] [0xFE79:2:0x0006]: async_initialize: all attempts have failed: [DeliveryError('[0xfe79:2:0x0006]: Message send failure'), DeliveryError('[0xfe79:2:0x0006]: Message send failure'), DeliveryError('[0xfe79:2:0x0006]: Message send failure'), DeliveryError('[0xfe79:2:0x0006]: Message send failure')]
```

This time, the misbehaving device is a E220-KR4N0Z0-HA power strip which has an annoying issue of showing as lights rather than sockets/switches so maybe a quirk is a good idea anyway. I'll try one locally and see if the problems shift to some other quirkless device again.

**Comment by yruss972** [comment]
Circling back, I wrote up a custom quirk for the now misbehaving devices here: #1749 and now they are all paired again without issues. I really don't know how/if the quirks are making a difference but it seems to do something.

**Comment by TheJulianJES** [comment]
I see you also removed the ``LevelControl`` cluster. Currently tracking a similar issue here: https://github.com/zigpy/zha-device-handlers/issues/1188#issuecomment-1371281949

Was the problem that the devices showed a brightness slider in HA, even though they only switch on/off?

**Comment by MattWestb** [comment]
Changing ZLL to ZH can making problems then its some fundamental different how the mesh is working but the device is still doing there thing so if its one ZLL router its still doing the router things "ala ZLL" but ZHA is thinking its one ZH router.

**Pull request closed without merging**
