### PR TITLE
Add Unitec Valve Thermostat

### PR DESCRIPTION
**Pull request by idstein**
Adding another Tuya valve variant
https://zigbee.blakadder.com/Unitec_30946.html

```
#  endpoint=1 profile=260 device_type=81 device_version=0 input_clusters=[0, 4, 5, 61184]
#  output_clusters=[10, 25]>
```

### CODE REVIEW

**Comment by idstein** [comment]
This valve also has a window opening detection. So it might also be a variant of MoesHY368_Type1, but it looks absolutely identical to Revolt NX4911 (implemented as SiterwellGS361_Type2) https://zigbee.blakadder.com/Revolt_NX-4911.html.

But the Revolt NX4911 also has a window detection built-in according to the German webpage see https://www.revolt-power.de/Weltweit-steuerbares-Heizkoerper-Design-Thermostat-NX-4911-919.shtml

**Comment by MattWestb** [comment]
Z2M have adding it as one SiterwellGS361 and i have not seen any complains that is not working OK in there issues.

You can also adding the Manufacture ID on the type 1 then normally its coming one upgraded version with the other zigbee module and then must doing on more PR.

`("_TYST11_ps5v5jor", "s5v5jor"),`

I have adding it in the [tuya TRV matrix](https://github.com/zigpy/zigpy/discussions/653#discussioncomment-314395) as its in the pipe :-))

**Comment by dmulcahey** [comment]
Needs conflicts resolved

**Comment by idstein** [comment]
> Needs conflicts resolved

Done.

**Comment by dmulcahey** [comment]
Thanks!

**Pull request merged**
