### PR TITLE
Adding Rotating Knob plus scene DA for DMS

### PR DESCRIPTION
**Pull request by MattWestb**
Adding the new Smart Rotating Knob with both command end event mode and device automatons that working but one is hitted of one HA bug that we cant fixing.
Adding Event mode (tuya scenes) after 10 mounts of user requests and all possible device automatons for it.

Implanting sending "tuya magic" from the device class that working every time the device is doing  on new joining do the 3 new endpoints is being initiated OK.

### CODE REVIEW

**Comment by MattWestb** [comment]
Its one problem if the user is resetting the device and also taking out the battery / battery is being dead in the operation is the device loosing the "tuya magic spell".
This quirk not handling that and the user must deleting the device in ZHA and readding it for the spell being recanted and enabling the 3 new endpoints and can loosing the linked automatons, but its the best i can doing with my knowledge.
Only resetting or only battery dead is no problem the device is keeping the magic only both at the same time is the bad.

Have trying implanting the casting of the magic spell from basic cluster but  its not working for this device then the casting is coming to late and the device is not in INIT mode.

If some one is making one good working implementation of it in tuya INIT and its working it can being imported and used in the future.

Both devices is tested by my and one user the knob and one other the DMS.

**Comment by MattWestb** [comment]
One more thing is that the device is repeating commands sent from EP 2-4 but we is sending default response from the quirk and also filtering the res endings so users is not getting multiple events / device automation rigged.

I have sniffing and ZHA is sending the default response with right sequences number and other data and no manufacture stuff is flagged so i think its one undocumented future of tuya TS004X devices.
If some one like digging deeper in it, pleas do.

**Comment by javicalle** [comment]
> One more thing is that the device is repeating commands sent from EP 2-4 but we is sending default response from the quirk and also filtering the res endings so users is not getting multiple events / device automation rigged.
> 
> I have sniffing and ZHA is sending the default response with right sequences number and other data and no manufacture stuff is flagged so i think its one undocumented future of tuya TS004X devices. If some one like digging deeper in it, pleas do.

I assume that this is happening for the `TuyaSmartRemote004FDMS` quirk, is that correct?

I've looked at the code and haven't seen anything strange. Maybe `TuyaSmartRemoteOnOffCluster` class can be simplified a bit (but it would surely be a breaking change in the events).

Perhaps it is related to the amount of traces. In some tests that I have done, the HA took a little longer to answer the default response because the number of traces caused a lot of access to the disk.
Do you have a way to check the behavior after disabling the traces?

If you have any logs of the repeating commands or if they are in a post I can take a look at them too to see if I see anything.

**Comment by MattWestb** [comment]
The old problem device yes the DiMerSwitch and its have both in and output cluster and i was trying adding the OnOff as In cluster but then i loosing the events in HA but the quirk is working and then looking in the log is no difference only losing the zha_events.
The Group cluster need being as in so can adding the device ad one light  in one group for searing light then it cant binding the out cluster to groups.

I have sniffing and the firs command is sent and the coordinator is sending one default response perhaps little late and the device is reseeding the first DR is revived and one more after next time out. I think its no timing problem only bad made firmware for the device.

Braking the events is bad for that cluster then it can being  used for the Smart Rotating Knob how much it have being rotated and how fast that all versions (some hundred versions is possible but not useful in reality).

Some commands generated and the trace [TS004f-trace.txt](https://github.com/zigpy/zha-device-handlers/files/8310156/TS004f-trace.txt).

I taking on look then disabling all unneeded debut and looking if its working better but i think its not.

Thanks for looking on the code then im not have the deep knowledge if i have doing somthing wrong.

**Comment by javicalle** [comment]
I haven't appreciate until now, but it seems very strange to me that endpoints 2-4 have the `TuyaSmartRemoteOnOffCluster` as INPUT_CLUSTERS, but endpoint 1 has it as OUTPUT_CLUSTERS. I would expect that in all endpoints would be the same kind.

I will look at this traces later. 👍🏻

**Comment by MattWestb** [comment]
Thanks i was thinking i was missing putting it back after some test and have fixing that and "scene commands" is working better from EP1.

Edit: I remember now and have moving it back after more test.
In Command mode if having EP 1 as in cluster ZHA is not using the real On and Off sent from it (its revived in the log but no tha_event) but the level control commands is working OK so is changing it or we is loosing commands for 2 buttons in command mode.

This is the one of the most hacky normal Zigbee device not in class with MCU ones but have so much things wrong made but in the end its not working so bad.

**Comment by javicalle** [comment]
Ummmm, I have seen some things at code that maybe can explain what are you seen.

I will try to explain what is the code doing. Then maybe we can try to adjust the behavior to what you would like to be.

The `TuyaSmartRemoteOnOffCluster` cluster extends the standar `OnOff` cluster, but with some custom code:
* handles duplicated messages
* implements the 0xFC and 0xFD `manufacturer_server_commands`
* handles only the events for 0xFC and 0xFD commands

OK, I believe that `manufacturer_server_commands` are only for the one kind of cluster (¿the input_cluster maybe?). If you want to handle the other type (the output_cluster if I'm correct), the `manufacturer_client_commands` must also be implemented. Probably that will be important when device changes from command to events mode.

Whith the `TuyaSmartRemoteOnOffCluster` all the standard `OnOff` events will be lost because the class doesn't handle it.

I hope you'll excuse me, but I'm not sure when the problem occurs.

My interpretation is the following:
* when the device is configured in command mode, it's like there is only a switch (`OnOff`) with dim and color? functions. All this is done through the standard Zigbee cluster/events on endpoint 1
* when the device is configured in events mode, the device behaves as if it had 4 endpoints that send events through the 0xFC and 0xFD commands

It's correct?

With these approach, my suggestion would be use this new class:
```python
class TuyaSmartRemoteOnOffCluster_2(OnOff, EventableCluster):
    """TuyaSmartRemoteOnOffCluster: fire events corresponding to press type."""

    name = "TS004X_cluster"
    ep_attribute = "TS004X_cluster"

    manufacturer_attributes = {
        0x8001: ("backlight_mode", SwitchBackLight),
        0x8002: ("power_on_state", PowerOnState),
        0x8004: ("switch_mode", SwitchMode),
    }


    class RotateType(t.enum8):
        """Rotate type enum."""

        RIGHT = 0x00
        LEFT = 0x01
        STOP = 0x02


    class PressType(t.enum8):
        """Rotate type enum."""

        SHORT_PRESS = 0x00
        DOUBLE_PRESS = 0x01
        LONG_PRESS = 0x02


    manufacturer_server_commands = {
        # 0xFC: ("rotate_type", (t.uint8_t,), False),
        # 0xFD: ("press_type", (t.uint8_t,), False),
        0xFC: ("rotate_type", (RotateType), False),
        0xFD: ("press_type", (PressType), False),
    }

    manufacturer_client_commands = manufacturer_server_commands
```

It would still be a WIP. It doesn't handle repeated messages and ZHA events would change format, but it is simpler than the previous implementation.

If you want you can try with this new class (in all the endpoints) and using it as `input_cluster` also in endpoint 1.
I'm also wondering if it would be necessary to define the `OnOff` cluster as output_cluster:
```python

    replacement = {
        ENDPOINTS: {
            1: {
                PROFILE_ID: zha.PROFILE_ID,
                DEVICE_TYPE: zha.DeviceType.NON_COLOR_CONTROLLER,
                INPUT_CLUSTERS: [
                    Basic.cluster_id,
                    PowerConfiguration.cluster_id,
                    Identify.cluster_id,
                    Groups.cluster_id,  # Is needed for adding group then binding is not working.
                    TuyaSmartRemoteOnOffCluster_2,
                    LightLink.cluster_id,
                ],
                OUTPUT_CLUSTERS: [
                    Ota.cluster_id,
                    Time.cluster_id,
                    Identify.cluster_id,
                    Groups.cluster_id,
                    Scenes.cluster_id,
                    # OnOff.cluster_id,  # would be needed in command mode?
                    LevelControl.cluster_id,
                    Color.cluster_id,
                    LightLink.cluster_id,
                ],
            },
            .../...
```

**Comment by javicalle** [comment]
Question: are endpoints 2-4 generating entities in HA? If they only manage events they shouldn't, right?

**Comment by MattWestb** [comment]
First thanks for looking o the problematic !!
- All known devices is using EP 1 and one "normal" remote but is having most cluster as and in and out. All is using the OnOff and also the Light level sending commands to lights.
The Smart Rotating Knob is also using the color cluster and sending 3 different color commands (TC, SATURATION and one more) i command mode.
I have only finding ZCL commends being sent from the device that is working OK.
- Events (tuya scene) mode is using the OnOff cluster and sending 1/2 commands for scenes (single, double or long hold (relese) pressed) and rotated. The commands is out of ZCL and but is not tagged manufacture in the frame what i have seen. Only the DMS is using more end points that is being activated then the device in in INIT mode (before its being stetted up and can changing its hardware config) and "casting tuya magic" befors the system is starting setting the device up is activating the new EPs and then is sending "scene" commands on all 4 EPs. The problem is that EP1 must functioning with bot normal OnOff ZCL commands that is manages of the Zigbee stack and the scene commands that we must acking in the quirk and "decoding" to events.

So in sort yes.

I think i deleting the DMR and paring it with my tuya ZBGW and doing on fast sniff for see if its sending the default response to the in or out cluster then we is knowing how tuya is doing it.

I can making on test version after doing the sniffing but its important having the filtering function if the default response is not working OK or is all automatons for event mode not working.

And you last Q is yes and can using the "original" device class without the OnOff functionality (also without the added rotating then its always on EP1 what we is knowing for the moment).

**Comment by MattWestb** [comment]
By the way without the quirk that is deleting in OnOff cluster and changing the device type (its not recommended to do) ZHA is doing 4 light switches in the GUI that is not working then its one remote and not 4 lights.

**Comment by MattWestb** [comment]
I think i must accepting its one real tuya device is looking in the new sniffs from tuya ZBGW:
```
No.	Time	Protocol	IEEE Src	IEEE Dst	Zigbee Src	Zigbee Dst	ZBN Dst	Group Nr	ZBN Seq	ZBA Seq	ZDP Seq	Nwk Seq	Src EP	Dst EP	Info
987	14:12:54,455147	ZigBee HA	0x46a4	0x2f06	0x46a4	0x0000	0x0000		92	12		21	4	1	ZCL OnOff: Unknown Command, Seq: 119
988	14:12:54,463572	ZigBee	0x2f06	0x0000	0x46a4	0x0000	0x0000		220			188			Route Record, Dst: 0x0000
989	14:12:54,506291	ZigBee HA	0x2f06	0x0000	0x46a4	0x0000	0x0000		92	12		189	4	1	ZCL OnOff: Unknown Command, Seq: 119
990	14:12:54,534924	ZigBee HA	0x0000	0x2f06	0x0000	0x46a4	0x46a4		224	127		16	1	4	ZCL: Default Response, Seq: 119
991	14:12:54,546086	IEEE 802.15.4	0x46a4	0x2f06	0x46a4	0x2f06						22			Data Request
992	14:12:54,556370	ZigBee HA	0x2f06	0x46a4	0x0000	0x46a4	0x46a4		224	127		190	1	4	ZCL: Default Response, Seq: 119
993	14:12:54,656022	IEEE 802.15.4	0x46a4	0x2f06	0x46a4	0x2f06						23			Data Request
994	14:12:54,755601	IEEE 802.15.4	0x46a4	0x2f06	0x46a4	0x2f06						24			Data Request
995	14:12:55,262328	ZigBee HA	0x46a4	0x2f06	0x46a4	0x0000	0x0000		94	13		25	4	1	ZCL OnOff: Unknown Command, Seq: 119
996	14:12:55,270470	ZigBee HA	0x2f06	0x0000	0x46a4	0x0000	0x0000		94	13		191	4	1	ZCL OnOff: Unknown Command, Seq: 119
997	14:12:55,294089	ZigBee HA	0x0000	0x2f06	0x0000	0x46a4	0x46a4		226	128		17	1	4	ZCL: Default Response, Seq: 119
998	14:12:55,355981	IEEE 802.15.4	0x46a4	0x2f06	0x46a4	0x2f06						26			Data Request
999	14:12:55,363257	ZigBee HA	0x2f06	0x46a4	0x0000	0x46a4	0x46a4		226	128		192	1	4	ZCL: Default Response, Seq: 119
1000	14:12:55,460119	IEEE 802.15.4	0x46a4	0x2f06	0x46a4	0x2f06						27			Data Request
1001	14:12:55,560615	IEEE 802.15.4	0x46a4	0x2f06	0x46a4	0x2f06						28			Data Request
1002	14:12:55,598623	ZigBee	0x881d	0xffff	0x881d	Broadcast	0xfffc		6			5			Link Status
1003	14:12:56,067800	ZigBee HA	0x46a4	0x2f06	0x46a4	0x0000	0x0000		96	14		29	4	1	ZCL OnOff: Unknown Command, Seq: 119
1004	14:12:56,075729	ZigBee HA	0x2f06	0x0000	0x46a4	0x0000	0x0000		96	14		193	4	1	ZCL OnOff: Unknown Command, Seq: 119
1005	14:12:56,106681	ZigBee HA	0x0000	0x2f06	0x0000	0x46a4	0x46a4		228	129		18	1	4	ZCL: Default Response, Seq: 119
1006	14:12:56,157510	IEEE 802.15.4	0x46a4	0x2f06	0x46a4	0x2f06						30			Data Request
1007	14:12:56,165913	ZigBee HA	0x2f06	0x46a4	0x0000	0x46a4	0x46a4		228	129		194	1	4	ZCL: Default Response, Seq: 119
```
The remote is sending the command from EP4 in Seq: 119 and its doing one jump to the coordinator and the coordinator is replaying with one default response and is doing one jump back to the device and the device is doing . . .  Seq: 119 repeated 2 times as in ZHA.
And from EP1:
```
No.	Time	Protocol	IEEE Src	IEEE Dst	Zigbee Src	Zigbee Dst	ZBN Dst	Group Nr	ZBN Seq	ZBA Seq	ZDP Seq	Nwk Seq	Src EP	Dst EP	Info
2091	14:19:08,176630	ZigBee HA	0x46a4	0x2f06	0x46a4	0x0000	0x0000		98	15		34	1	1	ZCL OnOff: Unknown Command, Seq: 120
2092	14:19:08,185069	ZigBee	0x2f06	0x0000	0x46a4	0x0000	0x0000		226			136			Route Record, Dst: 0x0000
2093	14:19:08,228584	ZigBee HA	0x2f06	0x0000	0x46a4	0x0000	0x0000		98	15		137	1	1	ZCL OnOff: Unknown Command, Seq: 120
2094	14:19:08,270808	ZigBee HA	0x0000	0x2f06	0x0000	0x46a4	0x46a4		153	205		142	1	1	ZCL: Default Response, Seq: 120
2095	14:19:08,272458	IEEE 802.15.4	0x46a4	0x2f06	0x46a4	0x2f06						35			Data Request
2096	14:19:08,282778	ZigBee HA	0x2f06	0x46a4	0x0000	0x46a4	0x46a4		153	205		138	1	1	ZCL: Default Response, Seq: 120
```
Working OK as in ZHA.
Was testing EP 2-4 and all doing the same and the EP1 is "normal".

I think we must accepting the device is not ZCL compatible on EP 1-4 then its tuya playground and we cant doing anything about that.

More thinking and testing ?

**Comment by javicalle** [comment]
> By the way without the quirk that is deleting in OnOff cluster and changing the device type (its not recommended to do) ZHA is doing 4 light switches in the GUI that is not working then its one remote and not 4 lights.

I am curious to know what happens if you define the `TuyaSmartRemoteOnOffCluster` clusters as output_clusters (and add the sentence `manufacturer_client_commands = manufacturer_server_commands`) I cannot get the conversation where was told me, but I seemed to understand that in that case HA does not generate the entities.

I can see that ZBGW is also sending the messages twice, so the message duplicated handle will be needed.

I will review later more code...

**Comment by javicalle** [comment]
> * The commands is out of ZCL and but is not tagged manufacture in the frame what i have seen.

I can always learn new things. Until now he had not been aware of the consequences (and the reason why) sometimes the manufacturer's methods were used for the attributes/methods and other times the cluster standards were extended to handle new attributes. Thanks for that 🙇🏻 

I think all my explanation about the `manufacturer_client_commands` and `manufacturer_server_commands` generating HA entities is not correct, so let's just forget it and disregard it. 🤦🏻‍♂️ 

My interpretation of the (ideal) device operation would be:
* the `TuyaSmartRemoteOnOffCluster` cluster handles event management
* in command mode, only a standard `OnOff` cluster is needed

That's why I think that a configuration like the following _could_ work:
```python
    replacement = {
        ENDPOINTS: {
            1: {
                PROFILE_ID: zha.PROFILE_ID,
                DEVICE_TYPE: zha.DeviceType.NON_COLOR_CONTROLLER,
                INPUT_CLUSTERS: [
                    Basic.cluster_id,
                    PowerConfiguration.cluster_id,
                    Identify.cluster_id,
                    Groups.cluster_id,  # Is needed for adding group then binding is not working.
                    TuyaSmartRemoteOnOffCluster_2,
                    LightLink.cluster_id,
                ],
                OUTPUT_CLUSTERS: [
                    Ota.cluster_id,
                    Time.cluster_id,
                    Identify.cluster_id,
                    Groups.cluster_id,
                    Scenes.cluster_id,
                    OnOff.cluster_id,  # would be needed in command mode?
                    LevelControl.cluster_id,
                    Color.cluster_id,
                    LightLink.cluster_id,
                ],
            },
            .../...
```

Like other times, I don't think there is really anything wrong with the code. There are parts that don't fit my interpretation, but that doesn't mean they're wrong. There are always multiple ways to reach the same result.
I understand how tiring it can be to re-validate something you've probably already tried multiple times, so feel free to ignore my requests if you think it's something that's already been validated. Like I said, if the code works, I don't see anything wrong.

I've checked the "tuya magic spell" part and in that case, there's not much I can add. If there is anything else you want me to review or need help with, I will do so as much as possible.

**Comment by MattWestb** [comment]
The general TS004F part is very likely also working for the upcoming **HG08164** (_TZ3000_rco1yzb1) that is being seen in CSA certified products and some user have getting its hands on https://csa-iot.org/csa_product/smart-switch-2/.
Hope LIDL is putting it out in Austria so i can testing if its have events (scene) mode or only command mode.

**Comment by dmulcahey** [comment]
Are we good to merge this one?

**Comment by javicalle** [comment]
LGTM, let's merge this version to see if it can come out with the new release of HA.

**Comment by javicalle** [comment]
I was thinking that when we get it into `tuya.__init__.py` we could try an implementation like:
```python
class TuyaBewitchedDevice:
     """Tuya device casting init spell."""

    SPELL_TARGET_ENDPOINT = 1
    SPELL_TARGET_INCLUSTER = 0
    SPELL_TARGET_ATTRS = [4, 0, 1, 5, 7, 0xFFFE]

    def __init__(self, *args, **kwargs):
        """Initialize with task."""
        super().__init__(*args, **kwargs)

        self._init_plug_task = asyncio.create_task(self.spell())

    async def spell(self) -> None:
        """Initialize device so that all endpoints become available."""
        basic_cluster = self.endpoints[SPELL_TARGET_ENDPOINT].in_clusters[SPELL_TARGET_INCLUSTER]

        await basic_cluster.read_attributes(SPELL_TARGET_ATTRS)
        _LOGGER.debug("Device class is casting Tuya Magic Spell")
```

Then, when necessary it would be enough to define the device as:
```python
class AnotherTuyaWeirdDevice(CustomDevice, TuyaBewitchedDevice):
    """Just another Tuya device doing Tuya things."""

    signature = {
      .../...
```

**Comment by MattWestb** [comment]
I think best merger and later i can testing the `TuyaBewitchedDevice` if its working OK with our problem child device getting the spell from INIT.
Its little time consuming then need deleting the device and the quirk and restating HA and verifying its have loosing the magic and then putting the quirk back and restarting HA and checking that the magic have applayed in the device and making it many time so being sure its working for "normal users" without problem.

**Comment by MattWestb** [comment]
I open one new issue then Smart things have fixing the problem with default response on E? 2-4 but its not for this PR.

**Comment by MattWestb** [comment]
Issue posted for function for fixing the last bad thing https://github.com/zigpy/zha-device-handlers/issues/1448.

**Pull request merged**
