### PR TITLE
Forward Philips Hue contact sensor changes to OnOff cluster

### LINKED ISSUE #3314: [Device Support Request] SOC001 - Philips Contact sensor
### Problem description

Signify released a while a go a contact sensor to extend their security product portfolio.
Unfortunately they almost exclusively putted all relevant attributes in their manufacturer cluster.
Good news is that the device seems to overall have a good behaviour continuing the reputation of Signify.

### Solution description

1. Implement the manufacturer specific cluster :
- PhilipsContactCluster : 0xFC06

2. Implements the associated attributes :
- Contact
Attribute: 0x0100
Data Type: 8-Bit Enumeration (0x30)
Uint8: 1 (0x01)

- Last contact change (10th of a second)
Attribute: 0x0101
Data Type: 32-Bit Unsigned Integer (0x23)
Uint32: 0 (0x00000000)

- Tamper
Attribute: 0x0102
Data Type: 8-Bit Enumeration (0x30)
Uint8: 0 (0x00)

- Last tamper change (10th of a second)
Attribute: 0x0103
Data Type: 32-Bit Unsigned Integer (0x23)
Uint32: 12425 (0x00003089)

3. Handle the on_off cluster as it is stateless and only meant for biding with lights.

### Screenshots/Video

<details><summary>Screenshots/Video</summary>

[Paste/upload your media here]

</details>

### Device signature

<details><summary>Device signature</summary>

```json
{
  "node_descriptor": {
    "logical_type": 2,
    "complex_descriptor_available": 0,
    "user_descriptor_available": 0,
    "reserved": 0,
    "aps_flags": 0,
    "frequency_band": 8,
    "mac_capability_flags": 128,
    "manufacturer_code": 4107,
    "maximum_buffer_size": 82,
    "maximum_incoming_transfer_size": 128,
    "server_mask": 11264,
    "maximum_outgoing_transfer_size": 128,
    "descriptor_capability_field": 0
  },
  "endpoints": {
    "2": {
      "profile_id": "0x0104",
      "device_type": "0x0402",
      "input_clusters": [
        "0x0000",
        "0x0001",
        "0x0003",
        "0xfc06"
      ],
      "output_clusters": [
        "0x0000",
        "0x0003",
        "0x0006",
        "0x0019"
      ]
    }
  },
  "manufacturer": "Signify Netherlands B.V.",
  "model": "SOC001",
  "class": "soc001.SignifyContact"
}
```

</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>

```json
None
```

</details>

### Logs

<details><summary>Logs</summary>

```python
None
```

</details>

### Custom quirk

<details><summary>Custom quirk</summary>

```python
"""Signify SOC001 device."""

from zigpy.quirks.v2 import QuirkBuilder,ClusterType,BinarySensorDeviceClass
import zigpy.types as types
from zigpy.quirks import CustomCluster

class PhilipsManufacturerSpecific(CustomCluster):
    """Philips Contact manufacturer cluster."""

    cluster_id: types.uint16_t = 0xFC06
    name = "Philips Manufacturer specific"
    ep_attribute = "philips_manufacturer_specific"
    attributes = {
        0x0100: ("contact", types.enum8, True),
        0x0101: ("last_contact_change", types.uint32_t, True),
        0x0102: ("tamper", types.enum8, True),
        0x0103: ("last_tamper_change", types.uint32_t, True),
    }

(
    QuirkBuilder("Signify Netherlands B.V.", "SOC001")
    .removes(
        cluster_id=6,
        endpoint_id=2,
        cluster_type=ClusterType.Client
    )
    .replaces(
        replacement_cluster_class=PhilipsManufacturerSpecific,
        cluster_id=64518,
        endpoint_id=2
    )
    .binary_sensor(
        attribute_name="contact",
        cluster_id=64518, #0xfc06,
        endpoint_id=2,
        device_class=BinarySensorDeviceClass.OPENING
    )
    .binary_sensor(
        attribute_name="tamper",
        cluster_id=64518, #0xfc06,
        endpoint_id=2,
        device_class=BinarySensorDeviceClass.TAMPER
    )
    .add_to_registry()
)
```

</details>

### Additional information

Unfortunately the device does not respond it's attributes whatsoever, probably to make our life a little bit harder.
To discover the attributes, I iterated all attribute addresses and read them to get the following data :

-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2024-08-19T04 | 37 | 20.475616+00 | 0 | Manufacturer Specific | 256 | enum8.undefined_0x00 | 0x0100 | 0xFC06 | 2 | 0 | 17 | 88 | 1 | 0d | ce | f9 | 51 | 0x100B | 0x30
2024-08-19T04 | 37 | 25.483887+00 | 0 | Manufacturer Specific | 257 | 47103 | 0x0101 | 0xFC06 | 2 | 0 | 17 | 88 | 1 | 0d | ce | f9 | 51 | 0x100B | 0x23
2024-08-19T04 | 37 | 30.487990+00 | 0 | Manufacturer Specific | 258 | enum8.undefined_0x00 | 0x0102 | 0xFC06 | 2 | 0 | 17 | 88 | 1 | 0d | ce | f9 | 51 | 0x100B | 0x30
2024-08-19T04 | 37 | 35.495690+00 | 0 | Manufacturer Specific | 259 | 172317 | 0x0103 | 0xFC06 | 2 | 0 | 17 | 88 | 1 | 0d | ce | f9 | 51 | 0x100B | 0x23

But realised afterward that ebaauw did all the work here : https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7226

### PR DESCRIPTION
**Pull request by TheJulianJES**
## Proposed change
This forwards all attribute updates from the custom Hue `contact` attribute to the `OnOff` cluster.
The advantage is that if commands from/to the `OnOff` cluster are missed, we'll get an attribute report in (max) 15 minutes from the custom Hue `contact` attribute.

We do this to avoid creating another entity and causing a breaking change if we removed the `OnOff` for this device.
The custom cluster is also only bound and sets up attribute reporting when running Home Assistant Core 2024.11.0 or later. Some devices may have been set up before. These devices will still work with this PR, as the `OnOff` changes are also still received.
Using this approach, we also stay flexible if we do further changes to the `OnOff` entities in the future (e.g. only creating on a whitelist for supported devices, so we don't create them for remotes).

cc @mguaylam
Please test the changes from this PR again, as they're slightly different. Just install `soc001.py` as a custom quirk again.

## Additional information
Closes https://github.com/zigpy/zha-device-handlers/pull/3464
Fixes https://github.com/zigpy/zha-device-handlers/issues/3314 (no entity for for last contact/tamper change though)

## Checklist

- [ ] The changes are tested and work correctly
- [x] `pre-commit` checks pass / the code has been formatted using Black
- [x] Tests have been added to verify that the new code works

### CODE REVIEW

**Comment by mguaylam** [comment]
ZHA can't setup anymore throwing this error :
```
Enregistreur: homeassistant.config_entries
Source: config_entries.py:635
S'est produit pour la première fois: 05:27:29 (1 occurrences)
Dernier enregistrement: 05:27:29

Error setting up entry HubZ Smart Home Controller, s/n: 81300134 - Silicon Labs for zha
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/zha/__init__.py", line 132, in async_setup_entry
    async with radio_mgr.connect_zigpy_app() as app:
  File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/zha/radio_manager.py", line 182, in connect_zigpy_app
    app = await self.radio_type.controller.new(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/zigpy/application.py", line 238, in new
    await app._load_db()
  File "/usr/local/lib/python3.12/site-packages/zigpy/application.py", line 110, in _load_db
    await self._dblistener.load()
  File "/usr/local/lib/python3.12/site-packages/zigpy/appdb.py", line 684, in load
    device = zigpy.quirks.get_device(device)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/zigpy/quirks/__init__.py", line 43, in get_device
    return _DEVICE_REGISTRY.get_device(device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/zigpy/quirks/registry.py", line 125, in get_device
    raise MultipleQuirksMatchException(
zigpy.exceptions.MultipleQuirksMatchException: Multiple matches found for device <Device model='SOC001' manuf='Signify Netherlands B.V.' nwk=0x2B03 ieee=00:17:88:01:0d:ce:f9:51 is_initialized=True>: [QuirksV2RegistryEntry(quirk_file=PosixPath('/usr/local/lib/python3.12/site-packages/zhaquirks/philips/soc001.py'), quirk_file_line=46, manufacturer_model_metadata=(ManufacturerModelMetadata(manufacturer='Signify Netherlands B.V.', model='SOC001'),), friendly_name=None, device_alerts=(), filters=(), custom_device_class=None, device_node_descriptor=None, skip_device_configuration=False, adds_metadata=(), removes_metadata=(), replaces_metadata=(ReplacesMetadata(remove=RemovesMetadata(cluster_id=64518, endpoint_id=2, cluster_type=<ClusterType.Server: 0>), add=AddsMetadata(cluster=<class 'zhaquirks.philips.soc001.PhilipsContactCluster'>, endpoint_id=2, cluster_type=<ClusterType.Server: 0>, constant_attributes=frozendict.frozendict({}))),), replaces_cluster_occurrences_metadata=(), entity_metadata=(BinarySensorMetadata(entity_platform=<EntityPlatform.BINARY_SENSOR: 'binary_sensor'>, entity_type=<EntityType.DIAGNOSTIC: 'diagnostic'>, cluster_id=64518, endpoint_id=2, cluster_type=<ClusterType.Server: 0>, initially_disabled=False, attribute_initialized_from_cache=True, translation_key=None, fallback_name='Tamper', attribute_name='tamper', reporting_config=None, device_class=<BinarySensorDeviceClass.TAMPER: 'tamper'>),), device_automation_triggers_metadata=frozendict.frozendict({})), QuirksV2RegistryEntry(quirk_file=PosixPath('/config/quirks/soc001.py'), quirk_file_line=63, manufacturer_model_metadata=(ManufacturerModelMetadata(manufacturer='Signify Netherlands B.V.', model='SOC001'),), friendly_name=None, device_alerts=(), filters=(), custom_device_class=None, device_node_descriptor=None, skip_device_configuration=False, adds_metadata=(), removes_metadata=(), replaces_metadata=(ReplacesMetadata(remove=RemovesMetadata(cluster_id=64518, endpoint_id=2, cluster_type=<ClusterType.Server: 0>), add=AddsMetadata(cluster=<class 'soc001.PhilipsContactCluster'>, endpoint_id=2, cluster_type=<ClusterType.Server: 0>, constant_attributes=frozendict.frozendict({}))),), replaces_cluster_occurrences_metadata=(), entity_metadata=(BinarySensorMetadata(entity_platform=<EntityPlatform.BINARY_SENSOR: 'binary_sensor'>, entity_type=<EntityType.DIAGNOSTIC: 'diagnostic'>, cluster_id=64518, endpoint_id=2, cluster_type=<ClusterType.Server: 0>, initially_disabled=False, attribute_initialized_from_cache=True, translation_key=None, fallback_name='Tamper', attribute_name='tamper', reporting_config=None, device_class=<BinarySensorDeviceClass.TAMPER: 'tamper'>),), device_automation_triggers_metadata=frozendict.frozendict({}))]
```

**Comment by TheJulianJES** [comment]
Uh, yeah. We have an issue where custom v2 quirks will cause this when there's already a v2 quirk present for the same device.. 

There's a workaround (in some other issue or PR) that you can use that deletes the old SOC001 registry entry. I'll put it here later if I don't forget.

**Comment by TheJulianJES** [comment]
See this workaround: https://github.com/zigpy/zha-device-handlers/pull/3465#issuecomment-2478619685

```python
from zigpy.quirks import DEVICE_REGISTRY
# other existing imports from custom quirks

# remove upstream quirk from registry
del DEVICE_REGISTRY._registry_v2[("Signify Netherlands B.V.", "SOC001")]

# add custom quirk...
```

**Comment by mguaylam** [comment]
It works and only create the necessary events. Thanks!
image

**Comment by TheJulianJES** [comment]
Thanks for testing!

**Pull request merged**
