### PR TITLE
Add support for Tuya LoraTap dimmers

### PR DESCRIPTION
**Pull request by ShogunMan**
Added support for more devices:
Loratap dimmers

### CODE REVIEW

**Comment by ShogunMan** [comment]
> Use [Black Playground](https://black.vercel.app/) for getting some of the bad formatting fixed and then look if its more that need being looking at for the test going thru.

I tried, but it did not fix anything, so I reverted back to the original h1_remote.py from dev repo. This still fails black & flake.
If you or someone would like to try and fix the h1_remote additonal versions, please go ahead :-)

**Comment by MattWestb** [comment]
Im looking on your privies commit https://github.com/zigpy/zha-device-handlers/pull/2291/commits/835da7dc20b1fabb7a4df7ca63e181297e41c574
and i can only see 2 easy thing.
W293 blank line contains whitespace = black is fixing it.
E302 expected 2 blank lines, found 1 = adding one new empty line and it shall being OK
W292 no newline at end of file = make one new line at the end and it shall being OK

Or you can posting one complete remote_h1.py and i can taking on look on it and you can fixing it  ?

**Comment by ShogunMan** [comment]
> Im looking on your privies commit [835da7d](https://github.com/zigpy/zha-device-handlers/commit/835da7dc20b1fabb7a4df7ca63e181297e41c574) and i can only see 2 easy thing. W293 blank line contains whitespace = black is fixing it. E302 expected 2 blank lines, found 1 = adding one new empty line and it shall being OK W292 no newline at end of file = make one new line at the end and it shall being OK
> 
> Or you can posting one complete remote_h1.py and i can taking one look on it and you can fixing it ?

This is the file that I am running in my production environment. I can't get it to pass checks.
[aqara_h1_remote.py.txt](https://github.com/zigpy/zha-device-handlers/files/11042884/aqara_h1_remote.py.txt)

**Comment by MattWestb** [comment]
Black was fixed only one dock string added and one more blacking.
Can you test adding it and we can looking if the test is working OK and if not i can helping getting it  right.
[aqara_h1_remote.py.txt](https://github.com/zigpy/zha-device-handlers/files/11043574/aqara_h1_remote.py.txt)

**Comment by ShogunMan** [comment]
> Black was fixed only one dock string added and one more blacking. Can you test adding it and we can looking if the test is working OK and if not i can helping getting it right.
> 
> [aqara_h1_remoteA.py.txt](https://github.com/zigpy/zha-device-handlers/files/11043582/aqara_h1_remoteA.py.txt)
> 
> Edit: was adding the original file and have fixing it now :-((

Added the file, black checks out ok, but Python fails.

**Comment by MattWestb** [comment]
All formatting in the quirk is OK but the system like have test code that is testing the code is doing what it meant to do and not other strange things but i cant doing coding so we must hoping some one can helping doing it.

I think best is making one new PR with this device and waiting and see if some is helping and only having the TuyaDimmerSwitch in this so its can being merged and not being held back for the Aqara device test code.

**Comment by ShogunMan** [comment]
Done, I will open a new PR when this is merged.

**Comment by TheJulianJES** [comment]
Just to confirm, did you test that both dimmers work correctly with these changes?

**Comment by ShogunMan** [comment]
> Just to confirm, did you test that both dimmers work correctly with these changes?

On/off is no problem. Dimming halogen and incandescent lights works fine.
But the dimmers seems very picky about what LED bulbs it can dim correctly. Some LEDS are full on @ 25% and does not dim very low. There is supposed to be a min/max level support, but I could not find any implementation for it.

**Review by TheJulianJES — APPROVED** [review]

**Pull request merged**
