### PR TITLE
Added quirk for Tuya TS0044 Remote Control

### PR DESCRIPTION
**Pull request by dumpfheimer**
Replacement for https://github.com/zigpy/zha-device-handlers/pull/603

Fixes https://github.com/zigpy/zha-device-handlers/issues/595

Related to https://github.com/zigpy/zha-device-handlers/issues/589
Related to https://github.com/zigpy/zha-device-handlers/issues/505
Related to https://github.com/zigpy/zha-device-handlers/issues/489

### CODE REVIEW

**Comment by TomKaltz** [comment]
I have one of the 4 button switched.  Hoping this will make mine work in Home Assistant.  Nice work!

**Review by Adminiuga — APPROVED** [review]
lgtm

**Comment by Adminiuga** [comment]
@dumpfheimer are you going to add the actual quirk? Apparently I was too quick on the trigger

**Comment by dumpfheimer** [comment]
Sorry, its committed now!

**Comment by dumpfheimer** [comment]
I see @tube0013 has already overtaken me and added more buttons, including the 4 button remote which I originally intended to support:
https://github.com/zigpy/zha-device-handlers/pull/611

**Comment by tube0013** [comment]
> I see @tube0013 has already overtaken me and added more buttons, including the 4 button remote which I originally intended to support:
> #611

@dumpfheimer hope I didn't step on you, I couldn't have done this without your work, so thank you.

Do you have the Manufacturer value for the ts0044?

**Comment by dumpfheimer** [comment]
Not at all, no worries!

Yes, exactly, this is how it registeres:

  "manufacturer": "_TZ3000_vp6clf9d",
  "model": "TS0044",

I've already commented on your PR, I guess its better to sort things out there, to keep it together.

**Pull request merged**
