### PR TITLE
Support for Tuya Carbon Dioxide/Air Quality Sensor -- _TZE200_8ygsuhe1

### PR DESCRIPTION
**Pull request by Adminiuga**
Support for [Tuya Air Quality Sensor](https://www.aliexpress.com/item/1005002474099751.html)
Device Signature:
```
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress|RxOnWhenIdle|MainsPowered|FullFunctionDevice: 142>, manufacturer_code=4098, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.0: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0051",
      "in_clusters": [
        "0x0000",
        "0x0004",
        "0x0005",
        "0xef00"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    }
  },
  "manufacturer": "_TZE200_8ygsuhe1",
  "model": "TS0601",
  "class": "zigpy.device.Device"
}
```

This PR also targets to establish a more universal Tuya Manufacturer Cluster, where you can just create handlers for Tuya command, instead of overloading `handle_cluster_request()` method.

For example, instead of checking the `hdr.command_id in (0x0001, 0x0002)` we just define `handle_get_data()` method, which corresponds to the previous `command_id==1`. `handle_get_data()` in turn just maps each datapoint (specific for each device) to a cluster and sends the attribute update to that cluster, using an optional "converter". Converter is a callable, which gets the datapoint value/payload and converts it to a corresponding ZCL attribute value.

### CODE REVIEW

**Comment by Adminiuga** [comment]
The sensor itself is meh, here's what CO2 measurement looks like
image

It does go up if you breathe onto sensor, so it does measure something. For camparison, here's output from MH-Z19B sensor from the same location:
image

**Comment by dougmaitelli** [comment]
Hi @Adminiuga,

Any chance these changes could be implemented for the following device handler as well?

Tuya Smart Air Box
TS0601
by _TZE200_ryfmq5rl

which uses the device handler _TZE200_ryfmq5rl instead of _TZE200_8ygsuhe1 from this PR.

I believe the hardware is basically the same.

**Comment by Adminiuga** [comment]
Add that manufacturer and model to existing quirk and try.

**Comment by dougmaitelli** [comment]
How can I do that?
I only have a a home assistant setup, so I am not sure if there is any way I can modify anything and try it out.

**Comment by MattWestb** [comment]
The device is added in ZHA dev but i think its not being added in HA then its between the main releases of HA https://github.com/zigpy/zha-device-handlers/pull/1013, https://github.com/zigpy/zha-device-handlers/releases/tag/0.0.61.

You can using the dev branch of ZHA in HA and you is getting the support or downloading the changed files and adding it in your local quirk folder after congratulating that in HA.

**Comment by dougmaitelli** [comment]
> The device is added in ZHA dev but i think its not being added in HA then its between the main releases of HA #1013, https://github.com/zigpy/zha-device-handlers/releases/tag/0.0.61.
> 
> You can using the dev branch of ZHA in HA and you is getting the support or downloading the changed files and adding it in your local quirk folder after congratulating that in HA.

Thank you very much @MattWestb, good to know that the change is already merged. I will wait for the next HA release to check.

Thanks,

**Pull request merged**
