### PR TITLE
Add support for the Osram Smart+ GU10 AC05347

### PR DESCRIPTION
**Pull request by Goldwing1973**
My first attempt of a quirk so i can use the AC05347 lights in ZHA.

### CODE REVIEW

**Review by Adminiuga — APPROVED** [review]
LGTM

**Comment by blakadder** [comment]
Any link to that AC05347 device since Google doesn't provide anything useful?

**Comment by Goldwing1973** [comment]
> 
> 
> Any link to that AC05347 device since Google doesn't provide anything useful?

https://www.amazon.de/gp/product/B077X7QS9D/
There you go.

**Comment by TheJulianJES** [comment]
Maybe the ".py" extension should be added to this "smartplusac05347" file?

**Comment by Adminiuga** [comment]
Yes, it should. My bad for not checking an obvious thing

**Comment by TheJulianJES** [comment]
This PR seems broken in more ways: https://github.com/zigpy/zha-device-handlers/pull/500#issuecomment-697661931

**Pull request merged**
