### PR TITLE
Add support for Aqara Curtain Driver E1

### PR DESCRIPTION
**Pull request by EverythingSmartHome**
Add's support for the Aqara curtain driver E1 - the cover itself worked OK but battery life and reversing direction did not which is what this PR adds.

### CODE REVIEW

**Review by QuentinBtd — APPROVED** [review]

**Comment by QuentinBtd** [comment]
Any news ? 👀

**Review by QuentinBtd — CHANGES_REQUESTED** [review]
After reading other .py file, you could rename this file into `driver_curtain_e1.py` to have same name structure that the 'roller_curtain_e1.py' file.

Maybe @dmulcahey will agree with this :)

**Comment by kurohouou** [comment]
Any update on when this may make it in?  I have 4 of these Curtain Drivers and none show the battery or invert direction :(

**Comment by QuentinBtd** [comment]
@dmulcahey Hello
Is something missing here ?

**Comment by circa1665** [comment]
I’ve added this as a custom quirk - this currently adds support for the battery level sensor, but the reversing direction and light level sensor don’t appear to work.

**Comment by EverythingSmartHome** [comment]
> I’ve added this as a custom quirk - this currently adds support for the battery level sensor, but the reversing direction and light level sensor don’t appear to work.

I never added the light level sensor, just battery and direction - both of which still work great for me personally. Perhaps someone else can give it a test to confirm either way

**Comment by circa1665** [comment]
My bad re: light level sensor. I’m away from home for a while. But will try connecting to a spare Aqara hub and updating the e1 firmware, then repair with ZHA and see if that enables the reversing direction.

**Comment by circa1665** [comment]
I updated the e1 firmware using an aqara hub. But still no joy, reversing direction doesn't work for me.

**Comment by LouisAtGH** [comment]
I try to get the curtain driver working, but not really success full yet:
- I am using the very latest home assistant build 2023.2.2
- with the SONOFF Zigbee 3.0 USB Dongle Plus V2 (the E-version)
- tryed with and without  quirks, among them this one 

Problems I have:
- the slider to control the curtain is gone (it was available when I was using older software with the Sonos P_dongle) !!
- related I can not longer use the go to position command (from Node Red and/or the gui
- battery is not working
- firmware not available
- set 0 and 100 % positions not available
- right and left setting not available (not a big problem for me, I can correct for that in Node Red)
- some other for me less important ones

Here my actual bindings

image

**Comment by ds-sebastian** [comment]
This is one of the few easy to install zigbee curtain motors, and it would be wonderful to have this working correctly!

**Comment by Hamish1066** [comment]
I can't get this working. Do I need to remove at re-add the device after adding the code for the quirk to my config?

**Comment by cannondale0815** [comment]
This quirk improves some aspects of the E1 curtain driver (like showing battery percentage now), but doesn't fix the issue that the curtain cannot be opened with the simple open/close controls. It only works if I use the percentage slider (0% to 100%), but not open/close. @EverythingSmartHome Would you happen to have come across this issue and have any thoughts on this?

[Myself and one other person](https://community.home-assistant.io/t/aqara-curtain-driver-e1/438974/62) appear to be having this issue.

**Comment by TheJulianJES** [comment]
I'm trying to clean up this PR soon. Can you send a screenshot of how the device shows in HA (with this quirk) and what controls are working and which aren't? (up/down/stop/percentage?)
Also, is it possible that like the E1 roller curtain, there's a difference depending on the firmware version?

Note for me in the future -- PR/quirk currently seems to throw an error (likely because inverted(?) attribute isn't in cache yet):

<details>
<summary>Error</summary>

```python
Logger: homeassistant.components.zha.core.cluster_handlers
Source: zha/quirks/curtain_e1.py:48
Integration: Zigbee Home Automation (documentation, issues)
First occurred: 10:21:47 PM (2 occurrences)
Last logged: 11:29:31 PM

[0x57FD:1:0x0102]: 'async_initialize' stage failed: 23
[0x8CB3:1:0x0102]: 'async_initialize' stage failed: 23
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/zha/core/helpers.py", line 340, in wrapper
    return await func(cluster_handler, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/zha/core/cluster_handlers/__init__.py", line 389, in async_initialize
    await self._get_attributes(
  File "/usr/src/homeassistant/homeassistant/components/zha/core/cluster_handlers/__init__.py", line 491, in _get_attributes
    read, _ = await self.cluster.read_attributes(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zigpy/zcl/__init__.py", line 545, in read_attributes
    self._update_attribute(record.attrid, value)
  File "/config/zha/quirks/curtain_e1.py", line 48, in _update_attribute
    if self.__getitem__(0x0017) == 1:
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zigpy/zcl/__init__.py", line 854, in __getitem__
    return self._attr_cache[self.find_attribute(key).id]
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 23
```

</details>

Another note: for some reason, the HA PR for this was merged some time ago already. It doesn't initialize the relevant attributes.. That needs to be fixed too.

**Comment by cannondale0815** [comment]
> I'm trying to clean up this PR soon. Can you send a screenshot of how the device shows in HA (with this quirk) and what controls are working and which aren't? (up/down/stop/percentage?) Also, is it possible that like the E1 roller curtain, there's a difference depending on the firmware version?

Thank you! Here's additional info from my device:

`Firmware: 0x0000001b
Zigbee info
IEEE: 54:ef:44:10:00:67:76:5d
Nwk: 0xbf57
Device Type: EndDevice
LQI: 87
RSSI: Unknown
Last seen: 2023-10-05T08:16:53
Power source: Battery or Unknown
Quirk: curtain_e1.E1Curtain
`

Close cover and open cover are not responding at all. Percentage slider for opening/closing is working fine, however.

I supposed it's possible that the device firmware plays a role. But I don't have any ability to update it, as I don't have the Aqara hub to perform a firmware update.

I'll happily provide any additional info you need.

**Comment by TheJulianJES** [comment]
Without a quirk, does the device show up as a "Router" / "Mains-Powered" or an "EndDevice"? (Wondering, because this quirk modifies the node descriptor)

Also, what about the stop action?

**Comment by TheJulianJES** [comment]
<details>
<summary>Quirk Test v2</summary>

```python
"""Aqara Curtain Driver E1 device."""
from __future__ import annotations

from typing import Any

from zigpy import types as t
from zigpy.profiles import zha
from zigpy.zcl import foundation
from zigpy.zcl.clusters.closures import WindowCovering
from zigpy.zcl.clusters.general import Basic, Identify, Ota, PowerConfiguration, Time
from zigpy.zdo.types import NodeDescriptor

from zhaquirks import CustomCluster
from zhaquirks.const import (
    DEVICE_TYPE,
    ENDPOINTS,
    INPUT_CLUSTERS,
    MODELS_INFO,
    NODE_DESCRIPTOR,
    OUTPUT_CLUSTERS,
    PROFILE_ID,
)
from zhaquirks.xiaomi import (
    BasicCluster,
    LUMI,
    XiaomiAqaraE1Cluster,
    XiaomiCluster,
    XiaomiCustomDevice,
    XiaomiPowerConfiguration,
)


class XiaomiAqaraDriverE1(XiaomiAqaraE1Cluster):
    """Xiaomi mfg cluster implementation specific for E1 Driver."""

    attributes = XiaomiCluster.attributes.copy()
    attributes.update(
        {
            0x0402: ("positions_stored", t.Bool, True),
            0x0407: ("store_position", t.uint8_t, True),
        }
    )


class WindowCoveringE1(CustomCluster, WindowCovering):
    """Xiaomi Window Covering configuration cluster."""

    def _update_attribute(self, attrid, value):
        if attrid == WindowCovering.AttributeDefs.current_position_lift_percentage.id:
            # TODO: improve this check? remove default? initialize? does the motor save this attr?
            # TODO: should we do this in HA? (does it have a way now to invert motor?)
            # TODO: should this always be reversed?
            if (
                self.get(WindowCovering.AttributeDefs.window_covering_mode.id, 0)
                & WindowCovering.WindowCoveringMode.Motor_direction_reversed
            ):
                value = 100 - value
        super()._update_attribute(attrid, value)

    async def command(
        self,
        command_id: foundation.GeneralCommand | int | t.uint8_t,
        *args: Any,
        manufacturer: int | t.uint16_t | None = None,
        expect_reply: bool = True,
        tsn: int | t.uint8_t | None = None,
        **kwargs: Any,
    ) -> Any:
        """Overwrite the commands to make it work for both firmware 1425 and 1427.

        We either overwrite analog_output's current_value or multistate_output's current
        value to make the roller work.
        """
        if command_id == WindowCovering.ServerCommandDefs.up_open.id:
            command_id = WindowCovering.ServerCommandDefs.go_to_lift_percentage.id
            args = (0,) # TODO: inverted?
        elif command_id == WindowCovering.ServerCommandDefs.down_close.id:
            command_id = WindowCovering.ServerCommandDefs.go_to_lift_percentage.id
            args = (100,) # TODO: inverted?
        # elif command_id == WindowCovering.ServerCommandDefs.go_to_lift_percentage.id:
        #     args = (100 - args[0],)  # TODO: needed to invert here? (depending on attr?)

        return await super().command(
            command_id,
            *args,
            manufacturer=manufacturer,
            expect_reply=expect_reply,
            tsn=tsn,
            **kwargs,
        )


# TODO: check if cluster works
# TODO: currently duplicated with roller_curtain_e1.py
class PowerConfigurationDriverE1(XiaomiPowerConfiguration):
    """Power cluster which ignores Xiaomi voltage reports."""

    def _update_battery_percentage(self, voltage_mv: int) -> None:
        """Ignore Xiaomi voltage reports, so they're not used to calculate battery percentage."""
        # This device sends battery percentage reports which are handled using a XiaomiCluster and
        # the inherited XiaomiPowerConfiguration cluster.
        # This device might also send Xiaomi battery reports, so we only want to use those for the voltage attribute,
        # but not for the battery percentage. XiaomiPowerConfiguration.battery_reported() still updates the voltage.


class DriverE1(XiaomiCustomDevice):
    """Aqara Curtain Driver E1 device."""

    signature = {
        MODELS_INFO: [(LUMI, "lumi.curtain.agl001")],
        ENDPOINTS: {
            # <SizePrefixedSimpleDescriptor endpoint=1 profile=260 device_type=263
            # device_version=1
            # input_clusters=[0, 1, 3, 10, 258, 64704]
            # output_clusters=[3, 10, 25, 64704]>
            1: {
                PROFILE_ID: zha.PROFILE_ID,
                DEVICE_TYPE: zha.DeviceType.OCCUPANCY_SENSOR,
                INPUT_CLUSTERS: [
                    Basic.cluster_id,
                    PowerConfiguration.cluster_id,
                    Identify.cluster_id,
                    Time.cluster_id,
                    WindowCovering.cluster_id,
                    XiaomiAqaraDriverE1.cluster_id,
                ],
                OUTPUT_CLUSTERS: [
                    Identify.cluster_id,
                    Time.cluster_id,
                    Ota.cluster_id,
                    XiaomiAqaraDriverE1.cluster_id,
                ],
            }
        },
    }
    replacement = {
        # TODO: needed?
        # NODE_DESCRIPTOR: NodeDescriptor(
        #     0x02, 0x40, 0x80, 0x115F, 0x7F, 0x0064, 0x2C00, 0x0064, 0x00
        # ),
        ENDPOINTS: {
            1: {
                PROFILE_ID: zha.PROFILE_ID,
                DEVICE_TYPE: zha.DeviceType.WINDOW_COVERING_DEVICE,
                INPUT_CLUSTERS: [
                    BasicCluster,
                    PowerConfigurationDriverE1,
                    Identify.cluster_id,
                    Time.cluster_id,
                    WindowCoveringE1,
                    XiaomiAqaraDriverE1,
                ],
                OUTPUT_CLUSTERS: [
                    Identify.cluster_id,
                    Time.cluster_id,
                    Ota.cluster_id,
                    # XiaomiAqaraDriverE1, # TODO: keep in OUTPUT too?
                ],
            }
        },
    }
```

</details>

Please test the quirk above and let me know what works and what doesn't (and what "powered by" status is shown).

-> Let's move that discussion to https://github.com/zigpy/zha-device-handlers/pull/2629

EDIT: also use the quirk from the link in the PR (not the one above)

**Comment by TheJulianJES** [comment]
- Superseded by https://github.com/zigpy/zha-device-handlers/pull/2629

Thanks for the PR!

**Pull request closed without merging**
