### PR TITLE
Add support for the Aqara c1 pet feeder

### PR DESCRIPTION
**Pull request by dmulcahey**
Huge thanks to the z2m folks who decoded how this works! https://github.com/Koenkk/zigbee-herdsman-converters/pull/4775

Xiaomi attr parsing updated to reflect changes in https://github.com/zigpy/zigpy/pull/1107

### CODE REVIEW

**Review by puddly — APPROVED** [review]

**Comment by wraith1385** [comment]
I saw the latest Core release added support for this device, however after I updated and attempted to add it, I only get the functionality shown in the screenshot.
Screenshot 2022-12-01 144941

**Comment by TheJulianJES** [comment]
@wraith1385 What coordinator are you using?

**Comment by wraith1385** [comment]
> @wraith1385 What coordinator are you using?

I'm using TubesZB Ethernet based CC2652P2 coordinator.  The device info from HA is:
 ZNP = Texas Instruments Z-Stack ZNP protocol: CC253x, CC26x2, CC13x2 by ZHA

**Comment by TheJulianJES** [comment]
What version of Z-Stack is it running? Also, please open a new issue in this repo and fill out the issue template

**Comment by lboue** [comment]
Thanks. It works since last HA update with _Elelabs Zigbee Raspberry Pi Shield_.

image

**Comment by vidplace7** [comment]
Curious if something similar to https://github.com/Koenkk/zigbee-herdsman-converters/pull/5364 can be implemented here, for fixing timezones.

**Pull request merged**
