### PR TITLE
Update DDS238-2 Din powerMeter with a new version of device

### LINKED ISSUE #1275: [Device Support Request] New manufacturerName for DDS238-2 Zigbee
In one chat I got information that from December 2021 this device now is sending with a new manufacturerName attribute: _TZE200_ewxhg6o9. The new version also contains the fix the switch issue (see the details in the #994 thread) and maybe something else, like EnergyFactor attribute.
I can update the quirck but I have no physically the new version of the DDS238-2 device to test, so if someone has the new version of device and can support me with the testing, I can help with the contribution of this update.

### PR DESCRIPTION
**Pull request by darckly**
New version of DDS238-2 Zigbee device was released with a new manufacturerName: _TZE200_ewxhg6o9. Device firmware contains a fix of the issue with incorrect Switch information, which the device sends (see details in the tread #994 )
The rest of the information is the same.
PR contains only the new manufacturer name as update, all other information is the same. PR closes #1275 .

### CODE REVIEW

**Comment by fvillena** [comment]
When this PR will be effectively available in ZHA for HA usage?

**Comment by MattWestb** [comment]
Its in version 0.0.66 of ZHA-quirk so it shall working https://github.com/zigpy/zha-device-handlers/releases/tag/0.0.66.

**Comment by fvillena** [comment]
Interesting, because i have HA 2022.5.5 and my device was not working until I manually performed the steps from issue #1275

**Comment by MattWestb** [comment]
If you was having one old not updated local quirk its overriding the quirk that is in the HA release.

If you is deleting all quirks in your local quirk folder and restarting HA is the system loading the right working quirk for your device ?

**Comment by fvillena** [comment]
The timing was as follows: 
- Today (HA version 2022.5.5) I adopted the new device and there were missing entities
- I created a custom quirk from issue #1275 
- All the entities were available correctly
So by default, HA was not detecting the device correctly

**Pull request merged**
