### PR TITLE
added Tuya Moes TS0041 (1 Gang) wireless switch

### PR DESCRIPTION
**Pull request by xriser**
added Tuya Moes TS0041 (1 Gang) wireless switch
https://www.aliexpress.com/item/1005001504737652.html

### CODE REVIEW

**Comment by jpillora** [comment]
hey @xriser, I've got a Tuya Moes TS0601 (2 Gang) wireless switch

Device Signature
```json
{
  "node_descriptor": "NodeDescriptor(byte1=2, byte2=64, mac_capability_flags=128, manufacturer_code=4098, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=0, *allocate_address=True, *complex_descriptor_available=False, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False, *is_valid=True, *logical_type=<LogicalType.EndDevice: 2>, *user_descriptor_available=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0051",
      "in_clusters": [
        "0x0000",
        "0x0004",
        "0x0005",
        "0xef00"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    }
  },
  "manufacturer": "_TZE200_g1ib5ldv",
  "model": "TS0601",
  "class": "zigpy.device.Device"
}
```

Would you be able to help me 1. modify the zigpy code (should be similar to your change) and 2. point me to resources for testing a fork of zigpy with my own HA instance? Then once it's working I'll contribute the change back to this repo :)

**Comment by xriser** [comment]
Hi, @jpillora 
1. Check the file https://github.com/zigpy/zha-device-handlers/blob/dev/zhaquirks/tuya/ts0601.py
If input clusters are the same as in your device signature, just add your manufacturer identifier '_TZE200_g1ib5ldv' to MODELS_INFO array in line 35
2. I have tested it in my homeassistant, just find the file ts0601.py do modification, remove python cache folder like __*cache*__,  restart HA, remove and pair device.

**Comment by jpillora** [comment]
Thanks! I’ll give it a try

**Comment by jpillora** [comment]
Update: it works, though only 1 of the 2 switches. This bug is known and discussed in other issues. Looks like I need to buy a different switch :(

**Pull request merged**
