### PR TITLE
get button press events from Tuya/LIDL/SilverCrest doorbell TS0211

### LINKED ISSUE #1168: [Device Support Request] TS0211 by _TZ1800_ladpngdx - Lidl - Silvercrest Doorbell Klingel
**Is your feature request related to a problem? Please describe.**

After Pairing to ZHA (Raspi 4/ Conbee2) the device shows a Sensor 'Ias_zone' which is in state 'Closed' - after pushing the Doorbell- button this state changes to "Open" and stays in that state.

**Describe the solution you'd like**

I want to use this doorbell as a push-button for an automation so i expect it to change back to the old state.

**Device signature - this can be acquired by removing the device from ZHA and pairing it again from the add devices screen. Be sure to add the entire content of the log panel after pairing the device to a code block below this line.**

{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4619, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0402",
      "in_clusters": [
        "0x0000",
        "0x0001",
        "0x0003",
        "0x0500",
        "0x0b05"
      ],
      "out_clusters": [
        "0x0019"
      ]
    }
  },
  "manufacturer": "_TZ1800_ladpngdx",
  "model": "TS0211",
  "class": "zigpy.device.Device"
}

Sent 'mgmt_permit_joining_req' to 84:18:26:00:00:0f:84:80: [<Status.SUCCESS: 0>]
Device 0x42d7 (84:2e:14:ff:fe:f8:09:83) joined the network
Device 84:2e:14:ff:fe:f8:09:83 changed id (0x42d7 => 0x42d7)
[0x42d7] Scheduling initialization
[0x42d7] Canceling old initialize call
Received frame on uninitialized device <Device model=None manuf=None nwk=0x42D7 ieee=84:2e:14:ff:fe:f8:09:83 is_initialized=False> from ep 0 to ep 0, cluster 19: b'\xf8\xd7B\x83\t\xf8\xfe\xff\x14.\x84\x80'
[0x42d7:zdo] ZDO request ZDOCmd.Device_annce: [0x42D7, 84:2e:14:ff:fe:f8:09:83, 128]
Tries remaining: 3
[0x42d7] Discovering endpoints
Tries remaining: 3
[0x42d7] Extending timeout for 0x71 request
Received frame on uninitialized device <Device model=None manuf=None nwk=0x42D7 ieee=84:2e:14:ff:fe:f8:09:83 is_initialized=False> from ep 0 to ep 0, cluster 6: b'C\xfd\xff\x04\x01\x00\x01\x00\x05'
[0x42d7:zdo] ZDO request ZDOCmd.Match_Desc_req: [0xFFFD, 260, [], [1280]]
Received frame on uninitialized device <Device model=None manuf=None nwk=0x42D7 ieee=84:2e:14:ff:fe:f8:09:83 is_initialized=False> from ep 0 to ep 0, cluster 32773: b'q\x00\xd7B\x01\x01'
[0x42d7] Discovered endpoints: [1]
[0x42d7] Initializing endpoints [<Endpoint id=1 in=[] out=[] status=<Status.NEW: 0>>]
[0x42d7:1] Discovering endpoint information
Tries remaining: 3
[0x42d7] Extending timeout for 0x74 request
Received frame on uninitialized device <Device model=None manuf=None nwk=0x42D7 ieee=84:2e:14:ff:fe:f8:09:83 is_initialized=False> from ep 0 to ep 0, cluster 32772: b't\x00\xd7B\x14\x01\x04\x01\x02\x04\x01\x05\x00\x00\x01\x00\x03\x00\x00\x05\x05\x0b\x01\x19\x00'
[0x42d7:1] Discovered endpoint information: SizePrefixedSimpleDescriptor(endpoint=1, profile=260, device_type=1026, device_version=1, input_clusters=[0, 1, 3, 1280, 2821], output_clusters=[25])
[0x42d7] Extending timeout for 0x76 request
[0x42d7:1:0x0000] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=True> manufacturer=None tsn=118 command_id=Command.Read_Attributes_rsp>
[0x42d7] Read model 'TS0211' and manufacturer '_TZ1800_ladpngdx' from <Endpoint id=1 in=[basic:0x0000, power:0x0001, identify:0x0003, ias_zone:0x0500, diagnostic:0x0B05] out=[ota:0x0019] status=<Status.ZDO_INIT: 1>>
[0x42d7] Discovered basic device information for <Device model='TS0211' manuf='_TZ1800_ladpngdx' nwk=0x42D7 ieee=84:2e:14:ff:fe:f8:09:83 is_initialized=True>
Device is initialized <Device model='TS0211' manuf='_TZ1800_ladpngdx' nwk=0x42D7 ieee=84:2e:14:ff:fe:f8:09:83 is_initialized=True>
Checking quirks for _TZ1800_ladpngdx TS0211 (84:2e:14:ff:fe:f8:09:83)
Considering <class 'zhaquirks.xbee.xbee_io.XBeeSensor'>
Fail because endpoint list mismatch: {232, 230} {1}
Considering <class 'zhaquirks.xbee.xbee3_io.XBee3Sensor'>
Fail because endpoint list mismatch: {232, 230} {1}
Considering <class 'zhaquirks.smartthings.tag_v4.SmartThingsTagV4'>
Fail because device_type mismatch on at least one endpoint
Considering <class 'zhaquirks.smartthings.multi.SmartthingsMultiPurposeSensor'>
Fail because input cluster mismatch on at least one endpoint
Considering <class 'zhaquirks.netvox.z308e3ed.Z308E3ED'>
Fail because input cluster mismatch on at least one endpoint
Considering <class 'zhaquirks.gledopto.soposhgu10.SoposhGU10'>
Fail because endpoint list mismatch: {11, 13} {1}
Considering <class 'bellows.zigbee.application.EZSPCoordinator'>
Fail because device_type mismatch on at least one endpoint
device - 17111:84:2e:14:ff:fe:f8:09:83 entering async_device_initialized - is_new_join: True
device - 17111:84:2e:14:ff:fe:f8:09:83 has joined the ZHA zigbee network
[17111](TS0211): started configuration
[17111:ZDO](TS0211): 'async_configure' stage succeeded
Error handling '_save_attribute' event with (84:2e:14:ff:fe:f8:09:83, 1, 0, 4, '_TZ1800_ladpngdx') params: FOREIGN KEY constraint failed
[0x42d7] Extending timeout for 0x78 request
[0x42d7] Extending timeout for 0x7a request
[17111:1:0x0000]: finished channel configuration
[17111:1:0x0019]: finished channel configuration
Error handling '_save_attribute' event with (84:2e:14:ff:fe:f8:09:83, 1, 0, 5, 'TS0211') params: FOREIGN KEY constraint failed
[0x42d7:1:0x0500] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=True> manufacturer=None tsn=120 command_id=Command.Read_Attributes_rsp>
[17111:1:0x0500]: started IASZoneChannel configuration
[0x42d7] Extending timeout for 0x7c request
[17111:1:0x0001]: bound 'power' cluster: Status.SUCCESS
[0x42d7] Extending timeout for 0x7e request
[17111:1:0x0500]: bound 'ias_zone' cluster: Status.SUCCESS
[0x42d7] Extending timeout for 0x80 request
[0x42d7:1:0x0001] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=126 command_id=Command.Configure_Reporting_rsp>
[17111:1:0x0001]: Successfully configured reporting for '{'battery_voltage': (3600, 10800, 1), 'battery_percentage_remaining': (3600, 10800, 1)}' on 'power' cluster: [ConfigureReportingResponseRecord(status=0)]
[17111:1:0x0001]: finished channel configuration
[0x42d7:1:0x0500] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=True> manufacturer=None tsn=128 command_id=Command.Write_Attributes_rsp>
[17111:1:0x0500]: wrote cie_addr: 00:21:2e:ff:ff:07:56:52 to 'ias_zone' cluster: [WriteAttributesStatusRecord(status=<Status.SUCCESS: 0>)]
[17111:1:0x0500]: Sending pro-active IAS enroll response
[17111:1:0x0500]: finished IASZoneChannel configuration
[0x42d7] Extending timeout for 0x82 request
[17111:1:0x0500]: 'async_configure' stage succeeded
[17111:1:0x0001]: 'async_configure' stage succeeded
[17111:1:0x0000]: 'async_configure' stage succeeded
[17111:1:0x0019]: 'async_configure' stage succeeded
[17111](TS0211): completed configuration
[17111](TS0211): stored in registry: ZhaDeviceEntry(name='_TZ1800_ladpngdx TS0211', ieee='84:2e:14:ff:fe:f8:09:83', last_seen=1637571737.562357)
[0x42d7] Extending timeout for 0x84 request
[0x42d7:1:0x0003] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=132 command_id=Command.Default_Response>
[17111:1:0x0003]: executed 'trigger_effect' command with args: '(2, 0)' kwargs: '{}' result: [64, <Status.UNSUP_CLUSTER_COMMAND: 129>]
[17111](TS0211): started initialization
[17111:ZDO](TS0211): 'async_initialize' stage succeeded
[17111:1:0x0500]: initializing channel: from_cache: False
[0x42d7] Extending timeout for 0x86 request
[17111:1:0x0001]: initializing channel: from_cache: False
[0x42d7] Extending timeout for 0x88 request
[17111:1:0x0000]: initializing channel: from_cache: False
[17111:1:0x0000]: finished channel initialization
[17111:1:0x0019]: initializing channel: from_cache: False
[17111:1:0x0019]: finished channel initialization
[0x42d7:zdo] ZDO request ZDOCmd.NWK_addr_req: [00:21:2e:ff:ff:07:56:52, 0, 0]
[0x42d7:zdo] ZDO request ZDOCmd.NWK_addr_req: [00:21:2e:ff:ff:07:56:52, 0, 0]
[0x42d7:zdo] ZDO request ZDOCmd.NWK_addr_req: [00:21:2e:ff:ff:07:56:52, 0, 0]
[0x42d7:1:0x0500] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=True> manufacturer=None tsn=134 command_id=Command.Read_Attributes_rsp>
[17111:1:0x0500]: finished channel initialization
[0x42d7:zdo] ZDO request ZDOCmd.NWK_addr_req: [00:21:2e:ff:ff:07:56:52, 0, 0]
[0x42d7:1:0x0001] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=True> manufacturer=None tsn=136 command_id=Command.Read_Attributes_rsp>
[0x42d7] Extending timeout for 0x8e request
[0x42d7:1:0x0500] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=CLUSTER_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=99 command_id=0>
[0x42d7:1:0x0500] ZCL request 0x0000: [<ZoneStatus.Supervision_reports|Tamper: 20>, <bitmap8.0: 0>, 0, 0]
[17111:1:0x0500]: Updated alarm state: ZoneStatus.0
[0x42d7:1:0x0001] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=True> manufacturer=None tsn=142 command_id=Command.Read_Attributes_rsp>
[17111:1:0x0001]: finished channel initialization
[17111:1:0x0500]: 'async_initialize' stage succeeded
[17111:1:0x0001]: 'async_initialize' stage succeeded
[17111:1:0x0000]: 'async_initialize' stage succeeded
[17111:1:0x0019]: 'async_initialize' stage succeeded
[17111](TS0211): power source: Battery or Unknown
[17111](TS0211): completed initialization

**Additional context**

Accidently i just found out that the Button on the (back under the lid) changes the State back to "Closed".
It seems to me as if the two buttons "doorbell" on front "and "Manipulation Detection/Open lid" are messed up in "one sensor".

image

Unfortunatly i am not able to reproduce that.

Thanks in advance - Michael

### PR DESCRIPTION
**Pull request by Habbie**
Fixes #1168.

This PR generates events (3, because the doorbell sends state 3 times in 5 seconds after a press) when the doorbell is pushed.

The event looks like this:

```
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "84:2e:14:ff:fe:f8:2a:08",
        "unique_id": "84:2e:14:ff:fe:f8:2a:08:1:0x0500",
        "device_id": "e3f05ce1cdd24bfe305af5c1ff166fec",
        "endpoint_id": 1,
        "cluster_id": 1280,
        "command": "single",
        "args": []
    },
    "origin": "LOCAL",
    "time_fired": "2022-03-04T19:41:28.219516+00:00",
    "context": {
        "id": "89f36ff0868b8763214b628f5af2bbf8",
        "parent_id": null,
        "user_id": null
    }
}
```

For previous ramblings I wrote while working on this, unfold below.

<details>
  <summary> Previous PR text</summary>
This is my first time working on ZHA and I have not figured everything out yet. I am also aware I have some unused imports, some debugging `print`s ~~and probably some other things black will be unhappy about~~. I'll clean all of that up.

For now, while this PR works (it generates a `zha_event` when I push the doorbell - in fact, it generates 3 of them over 6 seconds, which I guess makes some sense for a doorbell), I'd also like to expose the Tamper and Battery states correctly to Home Assistant. The states are currently logged, but I have not yet figured out how to cause related States to appear correctly in HA. Some hints about this would be very welcome!

Do I correctly get the impression that IasZone, generally (because this doorbell is not -that- deviated from the basic definition of IasZone) is not completely implemented in (Z)HA? #419 sounds that way.

Sorry to drop unfinished work on you - I suspect this is pretty close to workable, but I could really use a review.

Thanks!
</details>

### CODE REVIEW

**Comment by MattWestb** [comment]
If the device is is reseeding the same frame as it thinks it was not getting OK replay from the coordinator you can filtering that out. For detecting lost unicast the underlying network is using Transaction Number (tsn) and if 2 commands is having the same its one reseeding.
If its have different tsn its its technically 2 different commands.

One example of one device class that is filtering resent commands (if the system is not sending default response fast enough) : https://github.com/zigpy/zha-device-handlers/blob/e4e62504738ced0c54c983ee5094a3a6af0a741d/zhaquirks/tuya/__init__.py#L777

If you device sending with different tsn (that i think its doing) its need one other solution for doing the denounce.
Also leaving it and the user must taking care of it in the automation is OK then its how the device is working.

**Comment by Habbie** [comment]
> If you device sending with different tsn (that i think its doing) its need one other solution for doing the denounce.

Indeed, tsn 88, 89, 90 just now on one press.

> Also leaving it and the user must taking care of it in the automation is OK then its how the device is working.

I think this makes sense, it gives full flexibility to the user.

**Comment by MattWestb** [comment]
Great then its one real future of the device and not one undocumented future (bug).
Better leaving it and if like only getting one command then making denounce in the automation.

### By the way great work done !!

**Comment by Habbie** [comment]
> ### By the way great work done !!

Thank you :blush:

**Pull request merged**
