### PR TITLE
Fix Xiaomi MAEU01 plug

### LINKED ISSUE #1337: [BUG] Aqara plug (lumi.plug.maeu01) generates errors post-2022.2
**Describe the bug**
I use this plug with HA 2022.2.3, where it's been updated to use the quirk for lumi.plug.mmeu01 after [this pull](https://github.com/zigpy/zha-device-handlers/pull/1252/commits).

There are errors popping up in the log after this update.

```
Logger: homeassistant.util.logging
Source: util/logging.py:105
First occurred: 4:34:56 PM (16 occurrences)
Last logged: 4:55:26 PM

Exception in async_state_changed when dispatching 'LUMI lumi.plug.maeu01_54:ef:44:10:00:0e:52:9d_available_entity': () Traceback (most recent call last): 
 File  "/usr/src/homeassistant/homeassistant/components/zha/entity.py", line 107, in async_state_changed self.async_write_ha_state() 
 File  "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in async_write_ha_state self._async_write_ha_state() 
 File  "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 563, in _async_write_ha_state state = self._stringify_state() 
 File  "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 536, in _stringify_state if (state := self.state) is None: 
 File  "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 371, in state value = self.native_value 
 File  "/usr/src/homeassistant/homeassistant/components/zha/sensor.py", line 175, in native_value return self.formatter(raw_state) 
 File  "/usr/src/homeassistant/homeassistant/components/zha/sensor.py", line 472, in formatter return self._channel.summa_formatter(value) 
 File  "/usr/src/homeassistant/homeassistant/components/zha/core/channels/smartenergy.py", line 196, in _formatter_function return self._summa_format.format(value).lstrip() AttributeError: 'NoneType' object has no attribute 'format'
```

**To Reproduce**
Steps to reproduce the behavior: unknown

**Additional context**
```
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress|RxOnWhenIdle|MainsPowered|FullFunctionDevice: 142>, manufacturer_code=4447, maximum_buffer_size=127, maximum_incoming_transfer_size=100, server_mask=11264, maximum_outgoing_transfer_size=100, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0051",
      "in_clusters": [
        "0x0000",
        "0x0002",
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006",
        "0x0009",
        "0x0702",
        "0x0b04"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    },
    "21": {
      "profile_id": 260,
      "device_type": "0x0009",
      "in_clusters": [
        "0x000c"
      ],
      "out_clusters": [
        "0x0004",
        "0x000c"
      ]
    },
    "242": {
      "profile_id": 41440,
      "device_type": "0x0061",
      "in_clusters": [],
      "out_clusters": [
        "0x0021"
      ]
    }
  },
  "manufacturer": "LUMI",
  "model": "lumi.plug.maeu01",
  "class": "zhaquirks.xiaomi.aqara.plug_mmeu01.Plug"
}
```

### PR DESCRIPTION
**Pull request by dmulcahey**
Fixes #1337
Fixes: https://github.com/home-assistant/core/issues/67644
Fixes: https://github.com/home-assistant/core/issues/65292

### CODE REVIEW

**Comment by niorko** [comment]
Home Assistant 2022.9.0
Supervisor 2022.08.5
Operating System 8.5
Frontend 20220907.0 - latest

image

```
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress|RxOnWhenIdle|MainsPowered|FullFunctionDevice: 142>, manufacturer_code=4447, maximum_buffer_size=127, maximum_incoming_transfer_size=100, server_mask=11264, maximum_outgoing_transfer_size=100, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0051",
      "in_clusters": [
        "0x0000",
        "0x0002",
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006",
        "0x0009",
        "0x0702",
        "0x0b04",
        "0xfcc0"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    },
    "242": {
      "profile_id": 41440,
      "device_type": "0x0061",
      "in_clusters": [],
      "out_clusters": [
        "0x0021"
      ]
    }
  },
  "manufacturer": "LUMI",
  "model": "lumi.plug.maeu01",
  "class": "zhaquirks.xiaomi.aqara.plug_mmeu01.PlugMAEU01"
}
```

With my version, it is still showing 0W. It worked with Z2M.

**Comment by No0Vad** [comment]
I also get measures of 0 on my plug
image

Signature
```JSON
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress|RxOnWhenIdle|MainsPowered|FullFunctionDevice: 142>, manufacturer_code=4447, maximum_buffer_size=127, maximum_incoming_transfer_size=100, server_mask=11264, maximum_outgoing_transfer_size=100, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0051",
      "in_clusters": [
        "0x0000",
        "0x0002",
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006",
        "0x0009",
        "0x0702",
        "0x0b04",
        "0xfcc0"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    },
    "21": {
      "profile_id": 260,
      "device_type": "0x0051",
      "in_clusters": [
        "0x000c"
      ],
      "out_clusters": []
    },
    "242": {
      "profile_id": 41440,
      "device_type": "0x0061",
      "in_clusters": [],
      "out_clusters": [
        "0x0021"
      ]
    }
  },
  "manufacturer": "LUMI",
  "model": "lumi.plug.maeu01",
  "class": "zhaquirks.xiaomi.aqara.plug_eu.PlugMAEU01"
}
```

- Home Assistant 2022.10.5
- Supervisor 2022.10.0
- Operating System 9.2
- Frontend 20221010.0 - latest

**Comment by TheJulianJES** [comment]
@No0Vad Did you try re-pairing the plug? Also, what coordinator are you using?

**Comment by No0Vad** [comment]
> @No0Vad Did you try re-pairing the plug? Also, what coordinator are you using?

Yeah, I removed it from HA. Shutdown HA and unplugged the USB device for a few minutes and reconnected it all again.

Using: deCONZ = dresden elektronik deCONZ protocol: ConBee I/II, RaspBee I/II
by ZHA 

```JSON
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Coordinator: 0>, complex_descriptor_available=0, user_descriptor_available=1, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.RxOnWhenIdle|MainsPowered|FullFunctionDevice|AlternatePanCoordinator: 15>, manufacturer_code=4405, maximum_buffer_size=89, maximum_incoming_transfer_size=61, server_mask=64, maximum_outgoing_transfer_size=61, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=False, *is_alternate_pan_coordinator=True, *is_coordinator=True, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=False, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0400",
      "in_clusters": [
        "0x0000",
        "0x0006",
        "0x000a",
        "0x0019",
        "0x0501"
      ],
      "out_clusters": [
        "0x0001",
        "0x0020",
        "0x0500",
        "0x0502"
      ]
    },
    "2": {
      "profile_id": 49246,
      "device_type": "0x0820",
      "in_clusters": [
        "0x0000"
      ],
      "out_clusters": []
    }
  },
  "manufacturer": "dresden elektronik",
  "model": "ConBee II",
  "class": "zigpy_deconz.zigbee.application.DeconzDevice"
}
```

**Comment by TheJulianJES** [comment]
Can you check the app_version attribute on the Basic cluster?
Some versions of those plugs require to receive Xiaomi manufacturing codes during pairing.

It's likely that your Conbee just needs a firmware upgrade then.

**Comment by No0Vad** [comment]
I tried to read the value, but it failed. In fact I cant read any attributes.
image

**Comment by TheJulianJES** [comment]
Well, at least it's not a quirk problem then.

Try setting ZHA logs to debug by executing the following service call:
```yaml
service: logger.set_level
data:
  homeassistant.core: debug
  homeassistant.components.zha: debug
  bellows.zigbee.application: debug
  bellows.ezsp: debug
  zigpy: debug
  zigpy_deconz.zigbee.application: debug
  zigpy_deconz.api: debug
  zigpy_xbee.zigbee.application: debug
  zigpy_xbee.api: debug
  zigpy_zigate: debug
  zigpy_znp: debug
  zhaquirks: debug
```
Do another attribute read and see what's in ``home-assistant.log`` then.

**Comment by No0Vad** [comment]
I'll think these is the intressting part (at least starts with the request).
I have also noticed HA looses connection to it? (Or the device loosed connection) because after a while the LED starts to flash red slowly.

```
2022-10-26 19:30:04.674 DEBUG (MainThread) [homeassistant.components.zha.api] Requested attributes for: cluster_id: 0, cluster_type: 'in', endpoint_id: 1, response: [{'id': 0, 'name': 'zcl_version'}, {'id': 1, 'name': 'app_version'}, {'id': 2, 'name': 'stack_version'}, {'id': 3, 'name': 'hw_version'}, {'id': 4, 'name': 'manufacturer'}, {'id': 5, 'name': 'model'}, {'id': 6, 'name': 'date_code'}, {'id': 7, 'name': 'power_source'}, {'id': 8, 'name': 'generic_device_class'}, {'id': 9, 'name': 'generic_device_type'}, {'id': 10, 'name': 'product_code'}, {'id': 11, 'name': 'product_url'}, {'id': 12, 'name': 'manufacturer_version_details'}, {'id': 13, 'name': 'serial_number'}, {'id': 14, 'name': 'product_label'}, {'id': 16, 'name': 'location_desc'}, {'id': 17, 'name': 'physical_env'}, {'id': 18, 'name': 'device_enabled'}, {'id': 19, 'name': 'alarm_mask'}, {'id': 20, 'name': 'disable_local_config'}, {'id': 16384, 'name': 'sw_build_id'}, {'id': 65533, 'name': 'cluster_revision'}, {'id': 65534, 'name': 'attr_reporting_status'}]
2022-10-26 19:30:07.261 DEBUG (MainThread) [zigpy.zcl] [0x0000:1:0x0000] Sending request header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.GLOBAL_COMMAND: 0>, is_manufacturer_specific=False, direction=<Direction.Server_to_Client: 0>, disable_default_response=0, reserved=0, *is_cluster=False, *is_general=True, *is_reply=False), tsn=19, command_id=<GeneralCommand.Read_Attributes: 0>, *direction=<Direction.Server_to_Client: 0>, *is_reply=False)
2022-10-26 19:30:07.262 DEBUG (MainThread) [zigpy.zcl] [0x0000:1:0x0000] Sending request: Read_Attributes(attribute_ids=[1])
2022-10-26 19:30:07.263 DEBUG (MainThread) [zigpy_deconz.zigbee.application] Sending packet: ZigbeePacket(src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=1, source_route=None, extended_timeout=False, tsn=19, profile_id=260, cluster_id=0, data=Serialized[b'\x00\x13\x00\x01\x00'], tx_options=<TransmitOptions.ACK: 1>, radius=0, non_member_radius=0, lqi=None, rssi=None)
2022-10-26 19:30:07.263 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_request (20, 20, <DeconzSendDataFlags.NONE: 0>, <DeconzAddressEndpoint address_mode=AddressMode.NWK address=0x0000 endpoint=1>, 260, 0, 1, b'\x00\x13\x00\x01\x00', <DeconzTransmitOptions.USE_APS_ACKS|USE_NWK_KEY_SECURITY: 6>, 0)
2022-10-26 19:30:07.267 DEBUG (MainThread) [zigpy_deconz.api] Received command aps_data_request[2, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|2: 34>, 20]
2022-10-26 19:30:07.267 DEBUG (MainThread) [zigpy_deconz.api] APS data request response: [2, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|2: 34>, 20]
2022-10-26 19:30:07.268 DEBUG (MainThread) [zigpy_deconz.api] Received command device_state_changed[<DeviceState.128|APSDE_DATA_REQUEST_SLOTS_AVAILABLE|APSDE_DATA_INDICATION|APSDE_DATA_CONFIRM|2: 174>, 0]
2022-10-26 19:30:07.268 DEBUG (MainThread) [zigpy_deconz.api] Device state changed response: [<DeviceState.128|APSDE_DATA_REQUEST_SLOTS_AVAILABLE|APSDE_DATA_INDICATION|APSDE_DATA_CONFIRM|2: 174>, 0]
2022-10-26 19:30:07.268 DEBUG (MainThread) [zigpy_deconz.api] Received command device_state_changed[<DeviceState.128|APSDE_DATA_REQUEST_SLOTS_AVAILABLE|APSDE_DATA_INDICATION|APSDE_DATA_CONFIRM|2: 174>, 0]
2022-10-26 19:30:07.268 DEBUG (MainThread) [zigpy_deconz.api] Device state changed response: [<DeviceState.128|APSDE_DATA_REQUEST_SLOTS_AVAILABLE|APSDE_DATA_INDICATION|APSDE_DATA_CONFIRM|2: 174>, 0]
2022-10-26 19:30:07.269 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_indication (1, <DataIndicationFlags.Always_Use_NWK_Source_Addr: 1>)
2022-10-26 19:30:07.273 DEBUG (MainThread) [zigpy_deconz.api] Received command aps_data_indication[28, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|APSDE_DATA_INDICATION|APSDE_DATA_CONFIRM|2: 46>, <DeconzAddress address_mode=AddressMode.NWK address=0x0000>, 1, <DeconzAddress address_mode=AddressMode.NWK address=0x0000>, 1, 260, 0, b'\x00\x13\x00\x01\x00', 0, 175, 69, 42, 1, 0, 0, 27]
2022-10-26 19:30:07.273 DEBUG (MainThread) [zigpy_deconz.api] APS data indication response: [28, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|APSDE_DATA_INDICATION|APSDE_DATA_CONFIRM|2: 46>, <DeconzAddress address_mode=AddressMode.NWK address=0x0000>, 1, <DeconzAddress address_mode=AddressMode.NWK address=0x0000>, 1, 260, 0, b'\x00\x13\x00\x01\x00', 0, 175, 69, 42, 1, 0, 0, 27]
2022-10-26 19:30:07.274 DEBUG (MainThread) [zigpy.application] Received a packet: ZigbeePacket(src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=1, source_route=None, extended_timeout=False, tsn=None, profile_id=260, cluster_id=0, data=Serialized[b'\x00\x13\x00\x01\x00'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=69, rssi=27)
2022-10-26 19:30:07.274 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0x0000](ConBee II): Update device availability -  device available: False - new availability: True - changed: True
2022-10-26 19:30:07.274 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0x0000](ConBee II): Device availability changed and device became available, reinitializing channels
2022-10-26 19:30:07.275 DEBUG (MainThread) [zigpy.zcl] [0x0000:1:0x0000] Received ZCL frame: b'\x00\x13\x00\x01\x00'
2022-10-26 19:30:07.275 DEBUG (MainThread) [zigpy.zcl] [0x0000:1:0x0000] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.GLOBAL_COMMAND: 0>, is_manufacturer_specific=0, direction=<Direction.Server_to_Client: 0>, disable_default_response=0, reserved=0, *is_cluster=False, *is_general=True, *is_reply=False), tsn=19, command_id=0, *direction=<Direction.Server_to_Client: 0>, *is_reply=False)
2022-10-26 19:30:07.276 DEBUG (MainThread) [zigpy.zcl] [0x0000:1:0x0000] Decoded ZCL frame: Basic:Read_Attributes(attribute_ids=[1])
2022-10-26 19:30:07.277 DEBUG (MainThread) [zigpy.zcl] [0x0000:1:0x0000] Received command 0x00 (TSN 19): Read_Attributes(attribute_ids=[1])
2022-10-26 19:30:07.277 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0x0000](ConBee II): started initialization
2022-10-26 19:30:07.277 DEBUG (MainThread) [homeassistant.components.zha.core.channels.base] [0x0000:ZDO](ConBee II): 'async_initialize' stage succeeded
2022-10-26 19:30:07.278 DEBUG (MainThread) [zigpy_deconz.api] 'aps_data_indication' response from <DeconzAddress address_mode=AddressMode.NWK address=0x0000>, ep: 1, profile: 0x0104, cluster_id: 0x0000, data: b'0013000100'
2022-10-26 19:30:07.278 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_confirm (0,)
2022-10-26 19:30:07.279 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0x0000](ConBee II): power source: Mains
2022-10-26 19:30:07.279 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0x0000](ConBee II): completed initialization
2022-10-26 19:30:07.281 DEBUG (MainThread) [zigpy_deconz.api] Received command aps_data_confirm[12, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|APSDE_DATA_INDICATION|2: 42>, 20, <DeconzAddressEndpoint address_mode=AddressMode.NWK address=0x0000 endpoint=1>, 1, <TXStatus.SUCCESS: 0>, 0, 0, 0, 0]
2022-10-26 19:30:07.281 DEBUG (MainThread) [zigpy_deconz.api] APS data confirm response for request with id 20: 00
2022-10-26 19:30:07.281 DEBUG (MainThread) [zigpy_deconz.api] Request id: 0x14 'aps_data_confirm' for <DeconzAddressEndpoint address_mode=AddressMode.NWK address=0x0000 endpoint=1>, status: 0x00
2022-10-26 19:30:07.282 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_indication (1, <DataIndicationFlags.Always_Use_NWK_Source_Addr: 1>)
2022-10-26 19:30:07.290 DEBUG (MainThread) [zigpy_deconz.api] Received command aps_data_indication[28, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|2: 34>, <DeconzAddress address_mode=AddressMode.NWK address=0x0000>, 1, <DeconzAddress address_mode=AddressMode.NWK address=0x0000>, 1, 260, 0, b'\x18\x13\x0b\x00\x00', 0, 175, 69, 42, 1, 0, 0, 27]
2022-10-26 19:30:07.290 DEBUG (MainThread) [zigpy_deconz.api] APS data indication response: [28, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|2: 34>, <DeconzAddress address_mode=AddressMode.NWK address=0x0000>, 1, <DeconzAddress address_mode=AddressMode.NWK address=0x0000>, 1, 260, 0, b'\x18\x13\x0b\x00\x00', 0, 175, 69, 42, 1, 0, 0, 27]
2022-10-26 19:30:07.291 DEBUG (MainThread) [zigpy.application] Received a packet: ZigbeePacket(src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=1, source_route=None, extended_timeout=False, tsn=None, profile_id=260, cluster_id=0, data=Serialized[b'\x18\x13\x0b\x00\x00'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=69, rssi=27)
2022-10-26 19:30:07.291 DEBUG (MainThread) [zigpy.zcl] [0x0000:1:0x0000] Received ZCL frame: b'\x18\x13\x0b\x00\x00'
2022-10-26 19:30:07.292 DEBUG (MainThread) [zigpy.zcl] [0x0000:1:0x0000] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.GLOBAL_COMMAND: 0>, is_manufacturer_specific=0, direction=<Direction.Client_to_Server: 1>, disable_default_response=1, reserved=0, *is_cluster=False, *is_general=True, *is_reply=True), tsn=19, command_id=11, *direction=<Direction.Client_to_Server: 1>, *is_reply=True)
2022-10-26 19:30:07.293 DEBUG (MainThread) [zigpy.zcl] [0x0000:1:0x0000] Decoded ZCL frame: Basic:Default_Response(command_id=0, status=<Status.SUCCESS: 0>)
2022-10-26 19:30:07.293 DEBUG (MainThread) [zigpy.zcl] [0x0000:1:0x0000] Received command 0x0B (TSN 19): Default_Response(command_id=0, status=<Status.SUCCESS: 0>)
2022-10-26 19:30:07.294 DEBUG (MainThread) [zigpy_deconz.api] 'aps_data_indication' response from <DeconzAddress address_mode=AddressMode.NWK address=0x0000>, ep: 1, profile: 0x0104, cluster_id: 0x0000, data: b'18130b0000'
2022-10-26 19:30:07.294 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_indication (1, <DataIndicationFlags.Always_Use_NWK_Source_Addr: 1>)
2022-10-26 19:30:12.283 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139865578271696] Error handling message: Timeout (timeout)
```

**Comment by DlargeX** [comment]
I also got 2 Aqara Smart Plugs yesterday and they don't show any values except ON/OFF in ZHA either. Isn't there a solution for this?

**Comment by TheJulianJES** [comment]
@DlargeX Install the latest Z-Stack version on your coordinator and re-pair the plugs. Then see if it's solved

**Comment by MrGlad8** [comment]
> @DlargeX Install the latest Z-Stack version on your coordinator and re-pair the plugs. Then see if it's solved

I have Conbee2, how do I do that? My Aqara Smartplug doesnt show energy as well!

**Comment by Steephsel** [comment]
I have the same issue on 2 of 4 plugs with SkyConnect. Any solution for this het?

**Comment by TheJulianJES** [comment]
@Steephsel Create a new issue in this repo, fill out the template, and mention what your issue is. I've confirmed that the MAEU01 plugs work with SkyConnect,
Feel free to tag me in the new GitHub issue (@TheJulianJES).

**Comment by homerojleal** [comment]
> @Steephsel Create a new issue in this repo, fill out the template, and mention what your issue is. I've confirmed that the MAEU01 plugs work with SkyConnect, Feel free to tag me in the new GitHub issue (@TheJulianJES).

@Steephsel did you end up opening a new issue for MAEU01 plugs with SkyConnect?

**Pull request merged**
