### PR TITLE
Add support for TRADFRI GU10 WS 400lm

### PR DESCRIPTION
**Pull request by pgrondek**
I had a problem with GU10 bulb, after paring i could only turn it on or off, this quirk add support for brightness control and color temperature

### CODE REVIEW

**Comment by dmulcahey** [comment]
Took me a sec to see what this was doing... @Adminiuga another case of IKEA reporting a ZLL device type on a ZHA profile 🤦🏻‍♂️

**Comment by Adminiuga** [comment]
What firmware version the bulb is reporting?

I think the problem with that, the entity discover uses clusters and not the device type, so it matches to the switch domain. 
Should we add a work around and lookup zll device ID if zha lookup fails?

**Comment by dmulcahey** [comment]
> What firmware version the bulb is reporting?
> 
> I think the problem with that, the entity discover uses clusters and not the device type, so it matches to the switch domain.
> Should we add a work around and lookup zll device ID if zha lookup fails?

Up to you... I’m ok with this as a solution

**Comment by Adminiuga** [comment]
That's fine, but if the firmware update fixes it, maybe should also recommend the firmware update. Although Ikea OTA updates have been a separate problem lately

**Comment by pgrondek** [comment]
> What firmware version the bulb is reporting?
0x23050631 

I've enabled ota updates so I don't know if bulbs has been updated. I have also 4 bulbs connected to smartthings that reports version 0x11115720

**Comment by TheJulianJES** [comment]
Just wondering, what is the model number of the IKEA bulb that you have? (There are multiple "TRADFRI bulb GU10 WS 400lm" -> I've got the older LED1737R5 model and they work.)
Is it the LED1739R5 you're having issues with or a completely different model? (Model number should be written on the box/perhaps even the light itself?)

**Comment by pgrondek** [comment]
> Just wondering, what is the model number of the IKEA bulb that you have? (There are multiple "TRADFRI bulb GU10 WS 400lm" -> I've got the older LED1737R5 model and they work.)
> Is it the LED1739R5 you're having issues with or a completely different model? (Model number should be written on the box/perhaps even the light itself?)

I think I have even older model. On bulb I found model: LED1537R6, I thrown out box about 2 years ago.

**Comment by TheJulianJES** [comment]
I guess a fix is really needed for some (older) IKEA bulbs then. Adminiuga recommended this workaround which would probably fix all IKEA lights misreporting a ZLL device type on the ZHA profile. Individual quirks wouldn't be needed when doing it this way. #243 could also be fixed by doing this and there wouldn't be any issues with the special character in the model id for some of the bulbs.
> I think the problem with that, the entity discover uses clusters and not the device type, so it matches to the switch domain.
> Should we add a work around and lookup zll device ID if zha lookup fails?

**Comment by dmulcahey** [comment]
going to merge this for now... we can reassess if necessary.

**Pull request merged**
