### PR TITLE
Fix Nimly smart lock mains-powered capability

### PR DESCRIPTION
**Pull request by uvNikita**
## Proposed change
Add nimly smart lock quirk
Clears the mains powered mac capability flag since lock is battery powered.

Note that after quirk is applied, ZHA reports that my lock has 20% remaining battery, but when I query PowerConfiguration/battery_percentage_remaining attribute it reports 41%.
Not sure where ZHA gets 20% from.

See picture below:

## Additional information
Tested on NimlyPro model.

Ref
#3095
#2354

## Checklist

- [x] The changes are tested and work correctly
- [x] `pre-commit` checks pass / the code has been formatted using Black
- [ ] Tests have been added to verify that the new code works

### CODE REVIEW

**Comment by uvNikita** [comment]
I didn't add tests since I'm not sure how to test quirks v2, e.g. `assert_signature_matches_quirk`. Also not sure how to test node descriptor and power source specifically.

So it would be great with some direction on this if tests are required :)

**Comment by TheJulianJES** [comment]
Tests aren't really required for this. All good.

**Comment by TheJulianJES** [comment]
> when I query PowerConfiguration/battery_percentage_remaining attribute it reports 41%.
Not sure where ZHA gets 20% from.

`battery_percentage_remaining` goes from 0 to 200. 200 means 100%. ZHA remaps it.
Some manufacturers also miss that and use 100 for 100%, which is wrong. There's a doubling power configuration cluster which doubles that attribute value before it reaches ZHA. We can also use that if the manufacturer made the same mistake.

**Review by TheJulianJES — APPROVED** [review]
Thanks!

**Comment by uvNikita** [comment]
Thanks for the review and the explanation about battery levels. I'll try to replace the battery and see if it will report the correct value. If not, I'll open another PR 🙂

**Comment by jb3112** [comment]
How to add it, im not very expirenced with home assistant

**Comment by uvNikita** [comment]
@jb3112 this quirk is available since Home Assistant 2024.11, so just make sure you are running the latest version.
Reported battery level will be halved until you will update to Home Assistant 2024.12 where fix for that was pulled.

**Comment by jb3112** [comment]
how to make quirk

**Comment by uvNikita** [comment]
@jb3112 The quirk from this PR is applied automatically if your are using ZHA, the device producer is "Onesti Products AS", model name is "NimlyPRO", "NimlyCode", "NimlyTouch", "NimlyIn", "EasyFingerTouch, or "EasyCodeTouch". Nothing that you should be doing other than update Home Assistant.

**Comment by jb3112** [comment]
I have it here 
image

**Comment by uvNikita** [comment]
Oh, I see the issue. Your model name is `easyCodeTouch_v1` which is not on the list.

I'll create another PR to add it. Unfortunately you will have to wait for a new release to get the battery readings.

**Comment by jb3112** [comment]
Great, is there other thinks, like who has unlocked
Had it on smarthings before there i could see who unlocked

**Comment by uvNikita** [comment]
Not yet, but I'm planning to add this information too. Here is my comment for the reference: https://github.com/zigpy/zha-device-handlers/pull/3465#issuecomment-2439976447

**Pull request merged**
