### PR TITLE
Add round e-ink meter with external wired outdoor sensor

### PR DESCRIPTION
**Pull request by m0nty81**

### CODE REVIEW

**Review by MattWestb — APPROVED** [review]
Now its looks nice :-)))

**Review by TheJulianJES — APPROVED** [review]
Judging from https://github.com/zigpy/zha-device-handlers/issues/2113, these changes seem to work and LGTM.

**Review by javicalle — APPROVED** [review]
LGTM

**Comment by javicalle** [comment]
Duplicate of #2117

**Comment by TheJulianJES** [comment]
Thanks for your contribution!

It's rare but apparently someone was a bit faster and also added the same sensor in this PR: https://github.com/zigpy/zha-device-handlers/pull/2117

**Pull request closed without merging**
