### PR TITLE
Add Tuya switch TS0041 manufacturer

### PR DESCRIPTION
**Pull request by koying**
Ref: https://community.home-assistant.io/t/cant-get-ali-express-button-to-work/317597

Add manufacturer `_TZ3000_q68478x7` to the list of manufacturers for Tuya switch TS0041

### CODE REVIEW

**Comment by MattWestb** [comment]
Still missing one comma after the last ID:
`            ("_TZ3400_keyjqthh", "TS0041"),`

Good work :-))

**Comment by koying** [comment]
Thanks. Just using the github editor so was wondering :)

**Review by Adminiuga — APPROVED** [review]

**Comment by Adminiuga** [comment]
Please update the PR description with a brief of changes, like added new manufacturer identifies to xxx quirk

**Comment by koying** [comment]
Done

**Comment by Gershy13** [comment]
I have another manufacturer for the same switch. it isn't being detected. What do i need to provide?

TS0041
by _TZ3000_fkp5zyho

**Comment by RobDiederen** [comment]
Same here 
Iam just starting with home assistant, is this sufficient? : 

TS0041
by _TZ3000_tk3s5tyg

**Pull request merged**
