### PR TITLE
Update vibration_aq1.py

### PR DESCRIPTION
**Pull request by wes1993**
This fix is because this attibute RECENT_ACTIVITY_LEVEL_ATTR trigger the sensor also when anyone touch this, so removing this strings won't trigger the sensor ad we don't have fake trigger also in HA (I use this for alarm).

Remove This:
```
            elif attrid == RECENT_ACTIVITY_LEVEL_ATTR:
                # these seem to be sent every minute when vibration is active
                self.endpoint.device.motion_bus.listener_event(MOTION_EVENT)
```
I think we could also remove this string:
```
RECENT_ACTIVITY_LEVEL_ATTR = 0x0505  # decimal = 1285
```

### CODE REVIEW

**Comment by dmulcahey** [comment]
@Adminiuga dont merge this until I get a chance to test it please. I am pretty sure this will break the sensor

**Comment by wes1993** [comment]
@dmulcahey 
Thanks for your reply,
I have tested this in my HA and seems that work well.
Sorry it's my first time i will do a pull request in github i just think it could help

I hope  doesen't have created disturb

Regards
Stefano

**Comment by dmulcahey** [comment]
No need to apologize for anything! We appreciate the help. I just want to make sure this is actually necessary. Can you add the details for what you are trying to fix to the PR description please?

**Comment by wes1993** [comment]
It's ok now the description?
I also add this:
```
2020-12-18 16:18:33 DEBUG (MainThread) [zigpy.zcl] [0xf1b4:1:0x0101] Attribute report received: 1285=327680
2020-12-18 16:21:07 DEBUG (MainThread) [zigpy.zcl] [0x699a:1:0x0101] Attribute report received: 1285=2621440
2020-12-18 16:23:34 DEBUG (MainThread) [zigpy.zcl] [0xf1b4:1:0x0101] Attribute report received: 1285=327680
2020-12-18 16:26:08 DEBUG (MainThread) [zigpy.zcl] [0x699a:1:0x0101] Attribute report received: 1285=2818048
2020-12-18 16:28:35 DEBUG (MainThread) [zigpy.zcl] [0xf1b4:1:0x0101] Attribute report received: 1285=131072
2020-12-18 16:33:36 DEBUG (MainThread) [zigpy.zcl] [0xf1b4:1:0x0101] Attribute report received: 1285=131072
2020-12-18 16:39:43 DEBUG (MainThread) [zigpy.zcl] [0x4282:1:0x0101] Attribute report received: 1285=327680
2020-12-18 16:44:44 DEBUG (MainThread) [zigpy.zcl] [0x4282:1:0x0101] Attribute report received: 1285=524288
2020-12-18 16:48:22 DEBUG (MainThread) [zigpy.zcl] [0xbf30:1:0x0101] Attribute report received: 1285=393216
2020-12-18 16:53:23 DEBUG (MainThread) [zigpy.zcl] [0xbf30:1:0x0101] Attribute report received: 1285=327680
2020-12-18 16:55:47 DEBUG (MainThread) [zigpy.zcl] [0x3dfe:1:0x0101] Attribute report received: 1285=1048576
```
I haven't touched any of my sensors but the sensor report 1285=1048576 so leaving the string cause my alarm to false trigger

**Comment by wes1993** [comment]
> @Adminiuga dont merge this until I get a chance to test it please. I am pretty sure this will break the sensor

Sorry one question, why do you think that removing the strings will break the sensor?

Thanks again a lot
Stefano

**Comment by jimford-sudo** [comment]
I look forward to this update. The constant random triggering of my sensor makes it useless.
Thanks for your work, Stefano.

**Review by dmulcahey — APPROVED** [review]
Verified that this is the correct thing to do here. Thanks!

**Comment by wes1993** [comment]
Hello @dmulcahey 
This evening i have updated my HA and the sensor is incorrect again,
Do you know when the new file will be available in HA update?
Thanks a lot
Stefano

**Comment by Adminiuga** [comment]
In next HA release

**Comment by wes1993** [comment]
Thanks a lot for your reply
:-D

**Pull request merged**
