### PR TITLE
Add battery level for frient Entry Sensor and Entry Sensor Pro

### PR DESCRIPTION
**Pull request by danielpetrovic**
Added battery level support for frient Entry Sensor and Entry Sensor Pro.

## Checklist

- [x] The changes are tested and work correctly
- [x] `pre-commit` checks pass / the code has been formatted using Black
- [ ] Tests have been added to verify that the new code works

### CODE REVIEW

**Comment by MattWestb** [comment]
Black like have one space between:
```
-        MODELS_INFO: [(DEVELCO, "WISZB-121"),(FRIENT, "WISZB-121")],
+        MODELS_INFO: [(DEVELCO, "WISZB-121"), (FRIENT, "WISZB-121")],
```

**Comment by danielpetrovic** [comment]
How can I fix this in the current pull request?

**Comment by MattWestb** [comment]
Do new edetings in your "local" git ([danielpetrovic:patch-1](https://github.com/danielpetrovic/zha-device-handlers/tree/patch-1)) and then saving it its asking if like posting it directly or later and you can getting the pull being updated.

**Comment by danielpetrovic** [comment]
> Do new edetings in your "local" git ([danielpetrovic:patch-1](https://github.com/danielpetrovic/zha-device-handlers/tree/patch-1)) and then saving it its asking if like posting it directly or later and you can getting the pull being updated.

Thanks, I’ve pushed it again within patch-1 and fixed all the things it suggested. The check finished fully now.

**Review by TheJulianJES — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
