### PR TITLE
E1525 Zigbee 3 update

### PR DESCRIPTION
**Pull request by MattWestb**
### Now IKEA is all Zigbee 3.
As expected it have loosing group binding and reporting wrong battery %. Delete the device in ZHA and waiting one minute and adding it new and reconfigure it then its OK pared and its start reporting OK and also is doing check ins every 55 minute.

### CODE REVIEW

**Comment by MattWestb** [comment]
With new firmware and updated quirk:

Device info
TRADFRI motion sensor
by IKEA of Sweden
Connected via [Billy RCP 4.2.0 RK3318]
Firmware: 0x24040005
Zigbee info
IEEE: 90:fd:9f:ff:fe:59:bb:73
Nwk: 0x4544
Device Type: EndDevice
LQI: Unknown
RSSI: Unknown
Last Seen: 2023-01-26T19:30:54
Power Source: Battery or Unknown
Quirk: motionzha.IkeaTradfriMotionE1525

Its reporting LQI but  ZHA is not showing it in the device info for the moment (bug in ZHA ? or need one more restart) but ZHA maps is listing it OK.

**Comment by TheJulianJES** [comment]
Do we maybe also want to rename the quirk/class in line 25 to `IkeaTradfriMotionE1745_1` (assuming it's for that model) and line 92 to `IkeaTradfriMotionE1745_2`? (Other IKEA remote just append V1/V2 but I feel like an underscore is better here, so it doesn't get confused with the model.

And/or maybe update the docstring in quotes to mention the model?

**Comment by javicalle** [comment]
Or maybe just `IkeaTradfriMotion`, `IkeaTradfriMotion_Var02`, `IkeaTradfriMotion_Var03`, ...

That `Var` states for 'variation'. I prefer it before 'version' which can appear to be new versions of the device.
I would also remove the device code as a generic rule.

**Review by javicalle — APPROVED** [review]
LGTM

**Comment by MattWestb** [comment]
Have putting the good from both comment in naming and dock strings.

**Review by javicalle — APPROVED** [review]

**Review by TheJulianJES — APPROVED** [review]

**Comment by MattWestb** [comment]
Thanks J & J !!

**Comment by MattWestb** [comment]
Only for documentation the signature for the E1745 updated with Dirigera (no released in TFGW  OTA feed).
```
    "signature": {
      "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4476, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
      "endpoints": {
        "1": {
          "profile_id": 260,
          "device_type": "0x0850",
          "in_clusters": [
            "0x0000",
            "0x0001",
            "0x0003",
            "0x0020",
            "0x1000",
            "0xfc57",
            "0xfc7c"
          ],
          "out_clusters": [
            "0x0003",
            "0x0004",
            "0x0006",
            "0x0008",
            "0x0019",
            "0x1000"
          ]
        }
      }
    },
```
and the device card:
```
Device info
TRADFRI motion sensor
by IKEA of Sweden
Connected via [Billy RCP 4.2.1 RK3228A](http://192.168.2.65:8123/config/devices/device/e96ce063acfe580c70ca981efa995aab)
Firmware: 0x24040005
Zigbee info
IEEE: cc:cc:cc:ff:fe:c1:3a:8c
Nwk: 0x2f6f
Device Type: EndDevice
LQI: 196
RSSI: -60
Last Seen: 2023-02-16T09:30:39
Power Source: Battery or Unknown
```
Its very tricky getting pared (resetting the device is nearly impossible) and then is the best is taking the battery out and doing one reconfigure then putting them back for getting it reporting OK.
No quirk is loaded but battery looks being reported OK as Zigbee standard and motion detected if bright or not.

Z2M user is also reporting that the Dirigera is updating the blinds to the new standard but we dont knowing the URL for the update server.

**Pull request merged**
