### PR TITLE
Enumerates Zigbee Green Power profile and device types in existing quirks

### PR DESCRIPTION
**Pull request by nworbneb**
## Proposed change

This is purely a documentation excercise, to enhance readability of quirks, with no functional impact.

## Additional information

Requires merged zigpy pull to add Zigbee Green Power enumerations (https://github.com/zigpy/zigpy/pull/1213)

## Checklist

- [x] The changes are tested and work correctly
- [x] `pre-commit` checks pass / the code has been formatted using Black
- [ ] Tests have been added to verify that the new code works

### CODE REVIEW

**Comment by nworbneb** [comment]
I suspect this will take a little time for the necessary pull to make it into latest zigpy and the CI requirements to be updated to allow it to run successfully.

My intention, once included, is to circle back in a month or so to catch any in-flight pull requests, such as https://github.com/zigpy/zha-device-handlers/pull/2411.

**Comment by Hedda** [comment]
> Requires merged zigpy pull to add Zigbee Green Power enumerations ([zigpy/zigpy#1213](https://github.com/zigpy/zigpy/pull/1213))

Maybe make a draft for now as dependent on the currently unreleased [zigpy 0.56.0](https://github.com/zigpy/zigpy/releases/tag/0.56.0) library which will contain https://github.com/zigpy/zigpy/pull/1213 ?

PS: If possible please also update the ZGP feature request discussion for zigpy library here -> https://github.com/zigpy/zigpy/issues/341

**Comment by Hedda** [comment]
@zoic21 have you had a chance to try https://github.com/zigpy/zigpy/pull/1213 and https://github.com/zigpy/zha-device-handlers/pull/2414 with your [Zigbee plugin for Jeedom](https://doc.jeedom.com/en_US/plugins/automation%20protocol/zigbee/)? As I understand these should hopefully make your zigpy ZGP patches  in Jeedom from https://github.com/zigpy/zigpy/pull/656 (previously https://github.com/zigpy/zigpy/pull/519) unnecessary, or?

**Comment by dmulcahey** [comment]
Thanks for this!!

**Pull request merged**
