### PR TITLE
add _TZE200_9yapgbuv to TuyaTempHumiditySensorVar03

### PR DESCRIPTION
**Pull request by marktimmerman-dev**
Fixes https://github.com/zigpy/zha-device-handlers/issues/1918

### CODE REVIEW

**Comment by TheJulianJES** [comment]
Nice! Did you test if this change works for that new sensor (using a custom quirk for example)?

**Comment by marktimmerman-dev** [comment]
Yes, I have two of two devices in my Home Assistant setup, where I patched
the file with the file I submitted. Humidity and temperature work.

**Comment by marktimmerman-dev** [comment]
Related issue:
https://github.com/zigpy/zha-device-handlers/issues/1918

**Review by TheJulianJES — APPROVED** [review]

**Review by javicalle — APPROVED** [review]
LGTM

**Comment by javicalle** [comment]
I was going to point the diference between those same 2 issues.
Thank you @marktimmerman-dev  for taking the trouble to create a PR and contribute to the library.

**Pull request merged**
