### PR TITLE
Add support for Develco Air Quality Sensor AQSZB-110

### PR DESCRIPTION
**Pull request by EverythingSmartHome**
Create's quirk for Develco Air Quality Sensor AQSZB-110.

Big thanks to @rampage128 for the big help with this and for getting the final solution!

### CODE REVIEW

**Comment by dmulcahey** [comment]
Can you run black / flake8 / isort please?

**Comment by dmulcahey** [comment]
just whitespace issues now... you can see what is flagged in the PR itself. Ping me on discord if you need a hand. Same handle.

**Comment by MattWestb** [comment]
I think the last change is not so well seen by black  :-((
Look on it at [Black playground](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4CMMByNdAD2IimZxl1N_Wk8FsBxGOjUIy5MUwM0ysA6qhi3ex4m3mpJtAb_LerSN1gYoEQphpwYu4dgwXiiTJaToC7m6YaMmIaiGYcDuQe0aU44G4BYR8dJ_fT3H9mxgDnoHnYt06-7-EfFghplD_0zNQnLnbq7R3faX3ca_30oGdDqSCdO5J1cijY5Ub3MU6fjKY3jbSBAurN9UnKyPhofEIeLywx4vUZSlCmk9Mvt1StqYchIq6lNhwt0jq6AZV9r4a0PDX_y4d68DcuAyZbRQJpgz2EPcOzZ0fUuvXGohr9yY06NCdtxOt2pChAGfURIS-0HYJHFgq39TvYsDDwDs8Viz2d5g8biVb4B4fjbwyd1vvADOgGgDwp-rdQgX20F-mx9gYO-3Ytelr7aZ37wE_0wRzM2Yggk0GCGpdu61luxrmp-anijBd14aCg7xVc2MpOa55QB_XqWa-9b1N1cQYtw04xOa8EqETLQgDHCf-_VBjePupPLnKlTVKWhZ-KS2kOy0g_omfnc3hFwG0bCtt4xSeZG2svQ6v_ct7aLkR5dLKzJjA5RmT_ctAPSoBjtQn5498_STbbH2IKbmSezCISnjr_eAksBjKj3T9oggc8CcEGc3EtessS__TuNQc-3B5pgISiRRHwfzqrljGrPeCoq3JZLr7NDf4YIY-HMyMKcWtvT_mgFRLAKA9p_2rC7rMOIRGzGYqtmdYxP2nuvXlfX-CVLMkdN8Mya_4Ad1woX2KLBmregXo1G8fY_BtlqF9hjI_erZFehcfTIJVtskDtc_9e1OHeVa7Bq8WQ8HZyaTyT0IjlQEX-MOYMv3Qt4xLzgBgQpkYaSwZjE3qZHOtr7HyWgfmlGep4KCvZYQNoDqOurTh9KeYwq9tkgD_A6NXWn86ViPNrlMwpe_cdDII-RKRQlJXw7SGvKSIn2dMo1FdJQE9U7DTChtRRkJRJk8ZgkvRN0yfVvwT2QeIHJ8A23Fy1dUtBDQFb3-CbkjuvL3T7q1rQuMCfjRh0KOoiE-Xei1IJCndkOUhFNPSBr4HVX6VaUDbxNJ8Hv4XM4wZcdJZPfMDQvP2E8fH2cmkv2OEbXk0JHrT8Sw2aO-eKqT8cCEokfyquaJVRSVFbeXcmDquZkHUDlHUL-ZR6Mo-JO60eO6inFDF4yF0ElPIqzSI7CZfmwTr_u3zte_TUc1vjg0IuMuI0_8UDg9wh5aD_XTtiALqcLfhrPBUWsFESn2WR9DuFtQu0P6nRlS14KVNMEkDmLbalcFFVr6k9DORufwD6joNnDfY35SBkHCkd9CUpwk3STrplPYNcBLpaTHLAs09e-aPJIL2KatS89PMZUijjeXz22kGSCZc4dkpGXaiwGHaQxU3wh3b2ASbysnYKcRN80hjJjkZqvJuVivZVahe7pzHUA2ZZ0AF0tabp-Jt452uYMpOE93eV7gL20tjpwfmDy-aHkkXqEkS8WdmM4rIprhw4jf6mdpGfPo_2g0hO5-H-fxHrcrhhy--bxnyBoTTlYQytyeEpNCuZ-Qwbh8l8vm4_j5QWus7uAE6GAZk4hpe52fLArahcgq0oVYaG7bEqskU2nxha9lZM7yfWb4jp8wvqh_13rv-p6sSlM4CQIJGrn9VGrQxDp-2hH9y2jXy--IFijsk5BEXGQ6uLOfKaOivJItkuyd478Bkw8ugR3eAClSaKgO5Vhp0iKqRgU-JFV1KNMTE5jJid3bi3Cd3I-M_ym30UU6WlxqZx9it6oQmx8_9ksdFDL8z8clnaG5y2-2wvX6OU_GhDdGX4i4GVHRoviMo_BKLeqsNVLPhzGqZjy3bRTjnvGC0bP53egeFhMsiF2NiDm_DqsOapsVB5NGiVU3SZxKih5C_9V-cO0fvHbmGpFQtYNrNFz1AzmV6BLXN-YI9ZKBRWDBngUVO_sJnmi6IdLRSAA0BcG6Q7A3AG4j-YqcNJXuMzZyEYLMOWaWBujEgSh7ebm1Eajy4Su0TdTt_XwnLMa-KRmYYUKFPoPgQDBR1EAxvqeOl3Co4GEM6KxKXmzM3_F8EOTOtiZGcs4sRM1FdOtu0Gw0qryLq5PFk93-pcOobEJkouNNNb_cxIJAUPbN7UC0GioRqq6SwpDRI7dGxDq72tv1jIYm9DClcdEmldOy2vzVQPAmuQQdGaKHx2vPzaEdbnH1azgzWoad5YR-jUU8vhyAh5roJ1kDJk1D792OPiU0LN-mlE60EuHiEGJdaDE0KSyIBlYd_kSfiN7cAQiHUUC8KT-znBijskjHWf1ZCHfjf3fRu72jMH7uRuxAG2QpmRnVfarmI5tqQWuAHeKt9Fx2_nAN-1QeVTqA4X-AOxRtuU4pUYfYNn4ZBXD5g-QMDdi7200C1aJ7BoNiY4K1uS-Ac0BtMjQ-dtE4DS5kpBi2wZYPDRCVCQ7_Abn_caUlS7hqiiaKK7_izQAA42B1Md-J0v8AAb8OjUYAAIhU3fyxxGf7AgAAAAAEWVo=)

**Comment by EverythingSmartHome** [comment]
As you can see, I'm clearly not very good at this! 😄 

Done another edit now!

**Comment by MattWestb** [comment]
Im also one novice in coding but i have learned some tricks the hard way then adding tuya devices.

Hopefully all is OK and it can being merged if not more tests is complaining :-))

**Comment by EverythingSmartHome** [comment]
> Im also one novice in coding but i have learned some tricks the hard way then adding tuya devices.
> 
> Hopefully all is OK and it can being merged if not more tests is complaining :-))

I don't envy you! I've looked at some of the Tuya ones and they look extremely complicated in comparison, your doing a great job!

**Comment by EverythingSmartHome** [comment]
More formatting...

**Review by dmulcahey — APPROVED** [review]

**Pull request merged**
