### PR TITLE
Add long_press release

### PR DESCRIPTION
**Pull request by M4TH76**
To receive en event after a click hold release (dimmer release)

### CODE REVIEW

**Comment by M4TH76** [comment]
I'm not sure of ARGS in command_stop (copied them form long_press)

**Comment by dmulcahey** [comment]
You can see them by subscribing to zha_event in the event tool in the developer tools area in home assistant.

**Comment by dmulcahey** [comment]
You may also have to log in to travisci. And you potentially have to email them.

**Comment by dmulcahey** [comment]
@M4TH76 lmk what you need to get this finished...

**Comment by dmulcahey** [comment]
By removing the args there is no way to distinguish between each stop event. I'm guessing one of these isn't working. Also, you have to message the Travis CI support and get your account unblocked by them so this build will run.

Congrats btw!

**Comment by dmulcahey** [comment]
Please rebase to pick up the CI change. We swapped from travis to GH Actions. Sorry for the inconvenience.

**Comment by denilsonsa** [comment]
Hi! I was confused when I saw ZHA provides triggers for button presses, for buttons being continuously held, but it's missing a trigger for the button being released. That makes it tricky and counter-intuitive to build automations (we have to dive into `zha_event` details, instead of just using the much simpler *device triggers*).

image

---

I captured a few events. Here's what I found:

* Short button presses (on/off) only generate a single event. (Works as intended in ZHA.)
* Long button presses generate `move` and `move_with_on_off` events with some arguments, but those arguments don't seem to be useful anyway. (So far, also working as intended in ZHA.)
* Releasing from a long press generates a `stop` event with no arguments. Yes, it looks like the same event for either button. (This behavior is still missing from ZHA, and I hope this PR can help bringing it in.)

<details>

<summary>zha_event logs</summary>

```
Event 7 fired 8:45 AM:
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒",
        "unique_id": "▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒:1:0x0008",
        "device_id": "▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒",
        "endpoint_id": 1,
        "cluster_id": 8,
        "command": "stop",
        "args": []
    },
    "origin": "LOCAL",
    "time_fired": "2020-12-17T07:45:58.381877+00:00",
    "context": {
        "id": "bfdd7a959402a6b344a07dbf6c8407aa",
        "parent_id": null,
        "user_id": null
    }
}
Event 6 fired 8:45 AM:
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒",
        "unique_id": "▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒:1:0x0008",
        "device_id": "▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒",
        "endpoint_id": 1,
        "cluster_id": 8,
        "command": "move",
        "args": [
            1,
            83
        ]
    },
    "origin": "LOCAL",
    "time_fired": "2020-12-17T07:45:57.516022+00:00",
    "context": {
        "id": "e1d171d0e3d211ddedc4d0752802e87d",
        "parent_id": null,
        "user_id": null
    }
}
Event 5 fired 8:45 AM:
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒",
        "unique_id": "▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒:1:0x0008",
        "device_id": "▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒",
        "endpoint_id": 1,
        "cluster_id": 8,
        "command": "stop",
        "args": []
    },
    "origin": "LOCAL",
    "time_fired": "2020-12-17T07:45:55.566549+00:00",
    "context": {
        "id": "016129adc2bae2fc0e39f699e4414d5e",
        "parent_id": null,
        "user_id": null
    }
}
Event 4 fired 8:45 AM:
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒",
        "unique_id": "▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒:1:0x0008",
        "device_id": "▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒",
        "endpoint_id": 1,
        "cluster_id": 8,
        "command": "move_with_on_off",
        "args": [
            0,
            83
        ]
    },
    "origin": "LOCAL",
    "time_fired": "2020-12-17T07:45:54.786269+00:00",
    "context": {
        "id": "d0185e0424022d4d61e80b55bfec2de7",
        "parent_id": null,
        "user_id": null
    }
}
```

</details>

---

I have two ideas for solutions:

1. Send a single "release" trigger that works when any of those two buttons is released. (This looks like [the behavior in *controllerx*](https://github.com/xaviml/controllerx/blob/ca107554d00202cc9af48c99035e1c9fbec0cb84/apps/controllerx/cx_devices/ikea.py#L126-L236).)
2. Store a state somewhere to remember the last pressed button, so the appropriate "release" trigger can be sent. (I guess [that's what deconz does](https://github.com/xaviml/controllerx/blob/ca107554d00202cc9af48c99035e1c9fbec0cb84/apps/controllerx/cx_devices/ikea.py#L145-L146), but I can't test.)

Additionally, looks like [other (IKEA) remotes might also be missing the "release" trigger](https://github.com/zigpy/zha-device-handlers/blob/dev/zhaquirks/ikea/fivebtnremotezha.py#L110-L170), but I can't test that either.

I hope the logs in my comment prove useful. And I'm sorry, but I don't have time now to contribute with code.

**Comment by dmulcahey** [comment]
I rebased this and fixed the sort errors. Thanks for the contribution!

**Pull request merged**
