### PR TITLE
Create zgv1.py

### PR DESCRIPTION
**Pull request by zoic21**
Add support for tuya zigbee valve (https://www.domotique-store.fr/domotique/usages/arrosage-domotique-automatique-a-distance/1536-electrovanne-programmateur-d-arrosage-automatique-connecte-zigbee-compatible-app-smartphone-tuya-smart-life-et-lidl-home.html)

### CODE REVIEW

**Review by MattWestb — COMMENTED** [review]
I dont like the name of the quirk then i have renaming all "DP" devices quirks starting with `ts0601_ function_nanme` for getting some structure of tuya quirks.
Also many different devices was being putted in the same quirk that was confusing for all.

And for names is not the brand name its the manufacturing company (= no Moes pleas).

Perhaps `ts0601_valve_zgv1` ?

Great work done !!!

**Comment by dmulcahey** [comment]
There is something wrong with this PR. It shows as no changes

**Comment by Flow76320** [comment]
Hi ! 
Any news about merging this?

**Comment by dmulcahey** [comment]
Are we going to do anything with this?

**Comment by Flow76320** [comment]
File has been deleted in [this commit](https://github.com/zigpy/zha-device-handlers/pull/1253/commits/6332d6def5800bc79090cf32b58f3f29dcbe2882).

I've tested it but I could not make this device react. Maybe my testings were wrong though.

**Pull request closed without merging**
