### PR TITLE
Extended Beca TRV

### PR DESCRIPTION
**Pull request by rforro**
I've finalized quirk for BECA TRV which was written by @jacekk015 but PR got stuck because of missing tests. This code was extracted from https://github.com/zigpy/zha-device-handlers/pull/1192 which is basically dead, because it is not compatible with current zigpy version.

Note this PR uses AnalogInput cluster which is currently not exposed in HA, but I'm working on it. @Adminiuga @dmulcahey I need your advice, please look at https://github.com/home-assistant/core/pull/69063

After merging, this PR should close following issue https://github.com/zigpy/zha-device-handlers/issues/1123

### CODE REVIEW

**Comment by rforro** [comment]
PR #1464 was applied

**Comment by rforro** [comment]
@dmulcahey Can you tell me what is been hindering this PR from being merged?

**Comment by dmulcahey** [comment]
> @dmulcahey Can you tell me what hinders this PR from being merged?

I need to look at the analog input stuff... we are adding correct support for configuration entities in HA and I do not want to continue abusing analog input clusters.

**Comment by bh** [comment]
This is an image
This is an image


The "switch" over the cursor in the second screenshot is the childlock switch. The entity of the switch is "switch.tze200_b6wax7g0_ts0601_5bb99efe_on_off_". Can you change it to indicate that this is the child lock switch?

Works fine with Moes BRT-100. Good job!

**Review by dmulcahey — CHANGES_REQUESTED** [review]
<https://github.com/home-assistant/core/pull/70110> Let's change how this works so we aren't adding a bunch of fake clusters to the device to handle the configuration of the device. We can target the mfg cluster + make + model directly in HA.

**Comment by rforro** [comment]
> [home-assistant/core#70110](https://github.com/home-assistant/core/pull/70110) Let's change how this works so we aren't adding a bunch of fake clusters to the device to handle the configuration of the device. We can target the mfg cluster + make + model directly in HA.

I'm sorry but I don't get what you mean. Should I replace those generic AnalogInput/Output with my own and then add all of them into `homeassistant/components/zha` but target them to this TRV only?

**Comment by dmulcahey** [comment]
Do you have discord?

**Comment by miklosbagi** [comment]
I'm not sure if you guys have actually discussed the fake cluster issue came up in this PR, however, I'm happy to report that ts0601_trv_beca.py applied via zha_quirks fixes how my TRVs look like.

So for folks searching for Moes/Tuya/Beca Radiator Thermostat BRT-100-TRV ZHA support as of issues with the currently (2022.8.7) applied zhaquirks.tuya.ts0601_trv.MoesHY368_Type1new quirk (ping #1192 #932), this PR has the best quirk to be applied to date.

Fingers crossed it can get merged soon, I've got like 10 of these devices, so this was great help. Thanks @rforro !

**Comment by dmulcahey** [comment]
Is this still needed? If so, can we work towards getting it mergeable?

**Comment by MattWestb** [comment]
Nearly all tuya TRVs have very basic functionality and not working in ZHA GUI and we have spending weeks of testing and coding so the user can getting there devices working OK in ZHA.

Still If no one can doing it better this PR is much better then no or very bad support for tuya TRVs and more user is getting them and moving to other system (normaly not to de(F)CON) then is not getting any functionality in ZHA GUI.

Also pleas say what is wrong and trying getting it fixed instead letting it dying **jacekk015] on Nov 29, 2021** and in some week the PR is needed then its being cold in the north.

**Comment by miklosbagi** [comment]
> Is this still needed? If so, can we work towards getting it mergeable?

Yes - it solved my problem.

Out of the box the Moes TRV provides proper climate entities. However, on the latest 2022.8.7, battery % is reported as "unknown" and there's a bunch of entities missing compared to what's visible in @bh 's screenshots (child lock, min max temps, temp correction, etc).

It'd be awesome getting this merge-ready.

**Pull request closed without merging**
