### PR TITLE
Add quirk ts001x.py

### PR DESCRIPTION
**Pull request by sylvaing**
Add quirk for Tuya no neutral device TS001x (zigpy#826)

### CODE REVIEW

**Comment by dmulcahey** [comment]
What does this PR actually do? I don't see any changes to the OOTB devices.

**Comment by sstefanowski** [comment]
Hmmm, 
I noticed that  `replacement` has no output Time Cluster... was it a problem? @sylvaing can you comment?

BTW. I'm also interested in the support of these switches as I ordered a few MOES no-neutrals for testing...

**Review by Adminiuga — APPROVED** [review]
lgtm

**Comment by sylvaing** [comment]
@sstefanowski
Your are rignt, there no Time Cluster on the `replacement`.

Thanks @Adminiuga for the merge.

**Comment by HakunaMatmata** [comment]
Hi guys, 
we actually removed this Time Cluster in the replacement as it seemed to be the root cause of the problem of auto-off behavior on these devices.

**Pull request merged**
