### PR TITLE
Update valve.py

### PR DESCRIPTION
**Pull request by MattWestb**
Adding second version of Revolt TRV with other zigbee module. #631

### CODE REVIEW

**Comment by MattWestb** [comment]
Its my first try doing on RP and i hope i have getting it right (but black is complaining).

**Comment by MattWestb** [comment]
Thanks tube0013 !!!

**Comment by MattWestb** [comment]
Pleas putting on hold then the cluster is not OK.

**Comment by MattWestb** [comment]
Now its working the user is saying :-)))

**Comment by MattWestb** [comment]
The user is happy and black 2 and I hope @Adminiuga is also ;-)

How do I requesting the PR for being pulled in the dev branch ?

Its still my first PR so i dont knowing the routine in github.

**Review by dmulcahey — APPROVED** [review]

**Pull request merged**
