### PR TITLE
Hue in Wall Switch - RDM001

### PR DESCRIPTION
**Pull request by tube0013**
Add Support for Hue In Wall Switch. has been working for me. might need some clean up of the device automations?

### CODE REVIEW

**Comment by BrammyS** [comment]
I'd love to test this as well, but can't seem to find any way how. Can you point me into the right direction? :P

**Comment by tube0013** [comment]
check here:

https://github.com/zigpy/zha-device-handlers/issues/858#issuecomment-988490028

**Comment by BrammyS** [comment]
Everything seems to be working fine!
Added the custom quirk and an automation for it.

**Comment by apadua** [comment]
Hi Everyone. Mine works but only one port (LEFT). Is there a way to configure/enable support of the 2nd toggle? I’ve tried an old one i removed from the Hue hub and a net-new one from the sealed box.

**Comment by evpaassen** [comment]
> Hi Everyone. Mine works but only one port (LEFT). Is there a way to configure/enable support of the 2nd toggle? I’ve tried an old one i removed from the Hue hub and a net-new one from the sealed box.

You might find some useful information here: https://github.com/zigpy/zha-device-handlers/issues/858#issuecomment-1077615576 (and reply https://github.com/zigpy/zha-device-handlers/issues/858#issuecomment-1077624165). I'm not sure the second toggle is supported in the UI already, but you should be able to get it working by adding a trigger on a custom ZHA event.

**Pull request merged**
