### PR TITLE
Add support TS0601 _TZE200_9mahtqtg TB26

### LINKED ISSUE #1558: [Device Support Request] TS0601 _TZE200_9mahtqtg Zemismart Tuya 6 Gangs Smart Wall Light Switch 4x4 TB26
**Is your feature request related to a problem? Please describe.**
Device is detected but no cover entity is exposed only basic_lqi and basic_rssi

**Describe the solution you'd like**
 Add support for TS0601 _TZE200_9mahtqtg Zemismart Tuya 6 Gangs Smart Wall Light Switch 4x4 TB26

<details>
<summary>Device signature - this can be acquired by clicking on the "Zigbee Device Signature" button in the device settings</summary>

```
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4417, maximum_buffer_size=66, maximum_incoming_transfer_size=66, server_mask=10752, maximum_outgoing_transfer_size=66, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0051",
      "in_clusters": [
        "0x0000",
        "0x0004",
        "0x0005",
        "0x0006",
        "0xef00"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    }
  },
  "manufacturer": "_TZE200_9mahtqtg",
  "model": "TS0601",
  "class": "zigpy.device.Device"
}
```

</details>

<details>
<summary>Diagnostic information - this can be acquired by clicking on the "Download Diagnostics" button in the device settings</summary>

```
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.4.7",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.9.9",
    "docker": true,
    "arch": "aarch64",
    "timezone": "America/Recife",
    "os_name": "Linux",
    "os_version": "5.10.103-v8",
    "supervisor": "2022.05.1",
    "host_os": "Home Assistant OS 7.6",
    "docker_version": "20.10.9",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "zha_toolkit": {
      "version": "v0.8.8",
      "requirements": []
    },
    "hacs": {
      "version": "1.24.5",
      "requirements": [
        "aiogithubapi>=21.11.0"
      ]
    },
    "multiscrape": {
      "version": "6.2.0",
      "requirements": [
        "lxml",
        "beautifulsoup4==4.10.0"
      ]
    },
    "alexa_media": {
      "version": "3.11.3",
      "requirements": [
        "alexapy==1.25.5",
        "packaging>=20.3",
        "wrapt>=1.12.1"
      ]
    },
    "smartir": {
      "version": "1.17.6",
      "requirements": [
        "aiofiles==0.6.0"
      ]
    }
  },
  "integration_manifest": {
    "domain": "zha",
    "name": "Zigbee Home Automation",
    "config_flow": true,
    "documentation": "https://www.home-assistant.io/integrations/zha",
    "requirements": [
      "bellows==0.29.0",
      "pyserial==3.5",
      "pyserial-asyncio==0.6",
      "zha-quirks==0.0.72",
      "zigpy-deconz==0.14.0",
      "zigpy==0.44.2",
      "zigpy-xbee==0.14.0",
      "zigpy-zigate==0.7.4",
      "zigpy-znp==0.7.0"
    ],
    "usb": [
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*2652*",
        "known_devices": [
          "slae.sh cc2652rb stick"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*zigstar*",
        "known_devices": [
          "ZigStar Coordinators"
        ]
      },
      {
        "vid": "1CF1",
        "pid": "0030",
        "description": "*conbee*",
        "known_devices": [
          "Conbee II"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8A2A",
        "description": "*zigbee*",
        "known_devices": [
          "Nortek HUSBZB-1"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8B34",
        "description": "*bv 2010/10*",
        "known_devices": [
          "Bitron Video AV2010/10"
        ]
      }
    ],
    "codeowners": [
      "@dmulcahey",
      "@adminiuga"
    ],
    "zeroconf": [
      {
        "type": "_esphomelib._tcp.local.",
        "name": "tube*"
      }
    ],
    "after_dependencies": [
      "usb",
      "zeroconf"
    ],
    "iot_class": "local_polling",
    "loggers": [
      "aiosqlite",
      "bellows",
      "crccheck",
      "pure_pcapy3",
      "zhaquirks",
      "zigpy",
      "zigpy_deconz",
      "zigpy_xbee",
      "zigpy_zigate",
      "zigpy_znp"
    ],
    "is_built_in": true
  },
  "data": {
    "ieee": "**REDACTED**",
    "nwk": 2000,
    "manufacturer": "_TZE200_9mahtqtg",
    "model": "TS0601",
    "name": "_TZE200_9mahtqtg TS0601",
    "quirk_applied": false,
    "quirk_class": "zigpy.device.Device",
    "manufacturer_code": 4417,
    "power_source": "Battery or Unknown",
    "lqi": 255,
    "rssi": -82,
    "last_seen": "2022-05-11T20:41:14",
    "available": true,
    "device_type": "EndDevice",
    "signature": {
      "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4417, maximum_buffer_size=66, maximum_incoming_transfer_size=66, server_mask=10752, maximum_outgoing_transfer_size=66, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
      "endpoints": {
        "1": {
          "profile_id": 260,
          "device_type": "0x0051",
          "in_clusters": [
            "0x0000",
            "0x0004",
            "0x0005",
            "0x0006",
            "0xef00"
          ],
          "out_clusters": [
            "0x000a",
            "0x0019"
          ]
        }
      }
    },
    "entities": [],
    "neighbors": [],
    "endpoint_names": [
      {
        "name": "SMART_PLUG"
      }
    ],
    "user_given_name": null,
    "device_reg_id": "ed6af84d6998fe9d5fb07286fd20f775",
    "area_id": null
  }
}
```

</details>

<details>
<summary>Additional logs</summary>

```
Paste any additional debug logs here.
```

</details>

**Additional context**
I created `TuyaSextupleSwitchTO` based on `zhaquirks.tuya.ts0601_switch.TuyaQuadrupleSwitchTO` with a few modifications.
It didn't work with default manufacturer.
I copied `NoManufacturerCluster` and `TuyaOnOffNM` from `zhaquirks.tuya.ts0601_dimmer` to `zhaquirks.tuya.mcu`

### PR DESCRIPTION
**Pull request by w35l3y**
Zemismart Tuya 6 Gangs Smart Wall Light Switch 4x4

Fixes #1558

### CODE REVIEW

**Comment by javicalle** [comment]
Thanks @w35l3y, great job!

Once merged, the `ts0601_dimmer.py` would be refactored to use the generic classes. That's something pending from previous PRs.

**Review by javicalle — APPROVED** [review]
LGTM

**Comment by lleonardos** [comment]
i have an issue trying to pair my, i have 3 of them, all pair with no entities. log below:

Device signature

`{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress|RxOnWhenIdle|MainsPowered|FullFunctionDevice: 142>, manufacturer_code=4417, maximum_buffer_size=66, maximum_incoming_transfer_size=66, server_mask=10752, maximum_outgoing_transfer_size=66, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0051",
      "in_clusters": [
        "0x0000",
        "0x0004",
        "0x0005",
        "0xef00"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    },
    "242": {
      "profile_id": 41440,
      "device_type": "0x0061",
      "in_clusters": [],
      "out_clusters": [
        "0x0021"
      ]
    }
  },
  "manufacturer": "_TZE200_9mahtqtg",
  "model": "TS0601",
  "class": "zigpy.device.Device"
}`


Pairing Log:

`[0x0000:zdo] ZDO request ZDOCmd.Mgmt_Permit_Joining_rsp: [<Status.SUCCESS: 0>]
[0x0000:zdo] No handler for ZDO request:ZDOCmd.Mgmt_Permit_Joining_rsp([<Status.SUCCESS: 0>])
Device 0x19cd (a4:c1:38:ed:b0:12:62:bc) joined the network
Device a4:c1:38:ed:b0:12:62:bc changed id (0x4b97 => 0x19cd)
[0x19cd] Skipping initialization, device is fully initialized
Device is initialized <Device model='TS0601' manuf='_TZE200_9mahtqtg' nwk=0x19CD ieee=a4:c1:38:ed:b0:12:62:bc is_initialized=True>
Checking quirks for _TZE200_9mahtqtg TS0601 (a4:c1:38:ed:b0:12:62:bc)
Considering <class 'zhaquirks.tuya.ts0601_switch.TuyaSextupleSwitchTO'>
Fail because endpoint list mismatch: {1} {1, 242}
Considering <class 'zhaquirks.xbee.xbee_io.XBeeSensor'>
Fail because endpoint list mismatch: {232, 230} {1, 242}
Considering <class 'zhaquirks.xbee.xbee3_io.XBee3Sensor'>
Fail because endpoint list mismatch: {232, 230} {1, 242}
Considering <class 'zhaquirks.smartthings.tag_v4.SmartThingsTagV4'>
Fail because endpoint list mismatch: {1} {1, 242}
Considering <class 'zhaquirks.smartthings.multi.SmartthingsMultiPurposeSensor'>
Fail because endpoint list mismatch: {1} {1, 242}
Considering <class 'zhaquirks.netvox.z308e3ed.Z308E3ED'>
Fail because endpoint list mismatch: {1} {1, 242}
Considering <class 'zhaquirks.gledopto.soposhgu10.SoposhGU10'>
Fail because endpoint list mismatch: {11, 13} {1, 242}
device - 0x19CD:a4:c1:38:ed:b0:12:62:bc entering async_device_initialized - is_new_join: False
device - 0x19CD:a4:c1:38:ed:b0:12:62:bc has been reset and re-added or its nwk address changed
skipping discovery for previously discovered device - 0x19CD:a4:c1:38:ed:b0:12:62:bc
[0x19CD](TS0601): started configuration
[0x19CD:ZDO](TS0601): 'async_configure' stage succeeded
[0x19CD:1:0x0000]: Configuring cluster attribute reporting
[0x19CD:1:0x0000]: finished channel configuration
[0x19CD:1:0x0019]: finished channel configuration
[0x19CD:1:0x0000]: 'async_configure' stage succeeded
[0x19CD:1:0x0019]: 'async_configure' stage succeeded
[0x19CD](TS0601): completed configuration
[0x19CD](TS0601): Update device availability -  device available: False - new availability: True - changed: True
[0x19CD](TS0601): Device availability changed and device became available, reinitializing channels
[0x19CD](TS0601): started initialization
[0x19CD:ZDO](TS0601): 'async_initialize' stage succeeded
[0x19CD:1:0x0000]: initializing channel: from_cache: False
[0x19CD:1:0x0000]: finished channel initialization
[0x19CD:1:0x0019]: initializing channel: from_cache: False
[0x19CD:1:0x0019]: finished channel initialization
[0x19CD:1:0x0000]: 'async_initialize' stage succeeded
[0x19CD:1:0x0019]: 'async_initialize' stage succeeded
[0x19CD](TS0601): power source: Mains
[0x19CD](TS0601): completed initialization
[0xAFB3](lumi.weather): last_seen is 1166317.4376654625 seconds ago and ping attempts have been exhausted, marking the device unavailable
[0xAFB3](lumi.weather): Update device availability -  device available: False - new availability: False - changed: False
[0x0840](lumi.sensor_magnet.aq2): Device seen - marking the device available and resetting counter
[0x0840](lumi.sensor_magnet.aq2): Update device availability -  device available: True - new availability: True - changed: False
[0x19CD:1:0xef00] Received ZCL frame: b'\x09\x9F\x11\x00\x12\x40'
[0x19CD:1:0xef00] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.CLUSTER_COMMAND: 1>, is_manufacturer_specific=0, is_reply=1, disable_default_response=0, reserved=0, *is_cluster=True, *is_general=False), tsn=159, command_id=17, *is_reply=True)
[0x19CD:1:0xef00] Unknown cluster command 17 b'\x00\x12@'
[0x19CD:1:0xef00] Received command 0x11 (TSN 159): b'\x00\x12@'
[0x19CD:1:0xef00] No explicit handler for cluster command 0x11: b'\x00\x12@'
[0x19CD:1:0xef00] Received ZCL frame: b'\x09\x9F\x11\x00\x12\x40'
[0x19CD:1:0xef00] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.CLUSTER_COMMAND: 1>, is_manufacturer_specific=0, is_reply=1, disable_default_response=0, reserved=0, *is_cluster=True, *is_general=False), tsn=159, command_id=17, *is_reply=True)
[0x19CD:1:0xef00] Unknown cluster command 17 b'\x00\x12@'
[0x19CD:1:0xef00] Received command 0x11 (TSN 159): b'\x00\x12@'
[0x19CD:1:0xef00] No explicit handler for cluster command 0x11: b'\x00\x12@'
[0x19CD:1:0xef00] Received ZCL frame: b'\x09\x9F\x11\x00\x12\x40'
[0x19CD:1:0xef00] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.CLUSTER_COMMAND: 1>, is_manufacturer_specific=0, is_reply=1, disable_default_response=0, reserved=0, *is_cluster=True, *is_general=False), tsn=159, command_id=17, *is_reply=True)
[0x19CD:1:0xef00] Unknown cluster command 17 b'\x00\x12@'
[0x19CD:1:0xef00] Received command 0x11 (TSN 159): b'\x00\x12@'
[0x19CD:1:0xef00] No explicit handler for cluster command 0x11: b'\x00\x12@'
[0x19CD:1:0xef00] Received ZCL frame: b'\x09\xA0\x02\x00\x49\x01\x01\x00\x01\x00'
[0x19CD:1:0xef00] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.CLUSTER_COMMAND: 1>, is_manufacturer_specific=0, is_reply=1, disable_default_response=0, reserved=0, *is_cluster=True, *is_general=False), tsn=160, command_id=2, *is_reply=True)
[0x19CD:1:0xef00] Unknown cluster command 2 b'\x00I\x01\x01\x00\x01\x00'
[0x19CD:1:0xef00] Received command 0x02 (TSN 160): b'\x00I\x01\x01\x00\x01\x00'
[0x19CD:1:0xef00] No explicit handler for cluster command 0x02: b'\x00I\x01\x01\x00\x01\x00'
[0x19CD:1:0xef00] Received ZCL frame: b'\x09\xA0\x02\x00\x49\x01\x01\x00\x01\x00'
[0x19CD:1:0xef00] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.CLUSTER_COMMAND: 1>, is_manufacturer_specific=0, is_reply=1, disable_default_response=0, reserved=0, *is_cluster=True, *is_general=False), tsn=160, command_id=2, *is_reply=True)
[0x19CD:1:0xef00] Unknown cluster command 2 b'\x00I\x01\x01\x00\x01\x00'
[0x19CD:1:0xef00] Received command 0x02 (TSN 160): b'\x00I\x01\x01\x00\x01\x00'
[0x19CD:1:0xef00] No explicit handler for cluster command 0x02: b'\x00I\x01\x01\x00\x01\x00'
[0x90E9](c700000202): Device seen - marking the device available and resetting counter
[0x90E9](c700000202): Update device availability -  device available: True - new availability: True - changed: False
[0x19CD:1:0xef00] Received ZCL frame: b'\x09\xA0\x02\x00\x49\x01\x01\x00\x01\x00'
[0x19CD:1:0xef00] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.CLUSTER_COMMAND: 1>, is_manufacturer_specific=0, is_reply=1, disable_default_response=0, reserved=0, *is_cluster=True, *is_general=False), tsn=160, command_id=2, *is_reply=True)
[0x19CD:1:0xef00] Unknown cluster command 2 b'\x00I\x01\x01\x00\x01\x00'
[0x19CD:1:0xef00] Received command 0x02 (TSN 160): b'\x00I\x01\x01\x00\x01\x00'
[0x19CD:1:0xef00] No explicit handler for cluster command 0x02: b'\x00I\x01\x01\x00\x01\x00'
[0x19CD:1:0xef00] Received ZCL frame: b'\x09\xA0\x02\x00\x49\x01\x01\x00\x01\x00'
[0x19CD:1:0xef00] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.CLUSTER_COMMAND: 1>, is_manufacturer_specific=0, is_reply=1, disable_default_response=0, reserved=0, *is_cluster=True, *is_general=False), tsn=160, command_id=2, *is_reply=True)
[0x19CD:1:0xef00] Unknown cluster command 2 b'\x00I\x01\x01\x00\x01\x00'
[0x19CD:1:0xef00] Received command 0x02 (TSN 160): b'\x00I\x01\x01\x00\x01\x00'
[0x19CD:1:0xef00] No explicit handler for cluster command 0x02: b'\x00I\x01\x01\x00\x01\x00'
[0x19CD:1:0xef00] Received ZCL frame: b'\x09\xA0\x02\x00\x49\x01\x01\x00\x01\x00'
[0x19CD:1:0xef00] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.CLUSTER_COMMAND: 1>, is_manufacturer_specific=0, is_reply=1, disable_default_response=0, reserved=0, *is_cluster=True, *is_general=False), tsn=160, command_id=2, *is_reply=True)
[0x19CD:1:0xef00] Unknown cluster command 2 b'\x00I\x01\x01\x00\x01\x00'
[0x19CD:1:0xef00] Received command 0x02 (TSN 160): b'\x00I\x01\x01\x00\x01\x00'
[0x19CD:1:0xef00] No explicit handler for cluster command 0x02: b'\x00I\x01\x01\x00\x01\x00'
[0x19CD:1:0xef00] Received ZCL frame: b'\x09\xA0\x02\x00\x49\x01\x01\x00\x01\x00'
[0x19CD:1:0xef00] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.CLUSTER_COMMAND: 1>, is_manufacturer_specific=0, is_reply=1, disable_default_response=0, reserved=0, *is_cluster=True, *is_general=False), tsn=160, command_id=2, *is_reply=True)
[0x19CD:1:0xef00] Unknown cluster command 2 b'\x00I\x01\x01\x00\x01\x00'
[0x19CD:1:0xef00] Received command 0x02 (TSN 160): b'\x00I\x01\x01\x00\x01\x00'
[0x19CD:1:0xef00] No explicit handler for cluster command 0x02: b'\x00I\x01\x01\x00\x01\x00'
[0xC054](lumi.sensor_magnet.aq2): Device seen - marking the device available and resetting counter
[0xC054](lumi.sensor_magnet.aq2): Update device availability -  device available: True - new availability: True - changed: False
[0x19CD:1:0xef00] Received ZCL frame: b'\x09\xA4\x02\x00\x4D\x05\x01\x00\x01\x01'
[0x19CD:1:0xef00] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.CLUSTER_COMMAND: 1>, is_manufacturer_specific=0, is_reply=1, disable_default_response=0, reserved=0, *is_cluster=True, *is_general=False), tsn=164, command_id=2, *is_reply=True)
[0x19CD:1:0xef00] Unknown cluster command 2 b'\x00M\x05\x01\x00\x01\x01'
[0x19CD:1:0xef00] Received command 0x02 (TSN 164): b'\x00M\x05\x01\x00\x01\x01'
[0x19CD:1:0xef00] No explicit handler for cluster command 0x02: b'\x00M\x05\x01\x00\x01\x01'
[0x19CD:1:0xef00] Received ZCL frame: b'\x09\xA5\x02\x00\x4E\x06\x01\x00\x01\x00'
[0x19CD:1:0xef00] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.CLUSTER_COMMAND: 1>, is_manufacturer_specific=0, is_reply=1, disable_default_response=0, reserved=0, *is_cluster=True, *is_general=False), tsn=165, command_id=2, *is_reply=True)
[0x19CD:1:0xef00] Unknown cluster command 2 b'\x00N\x06\x01\x00\x01\x00'
[0x19CD:1:0xef00] Received command 0x02 (TSN 165): b'\x00N\x06\x01\x00\x01\x00'
[0x19CD:1:0xef00] No explicit handler for cluster command 0x02: b'\x00N\x06\x01\x00\x01\x00'
[0x19CD:1:0x0000] Received ZCL frame: b'\x08\xA7\x0A\x01\x00\x20\x46\xE2\xFF\x20\x36\xE4\xFF\x20\x00'
[0x19CD:1:0x0000] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.GLOBAL_COMMAND: 0>, is_manufacturer_specific=0, is_reply=1, disable_default_response=0, reserved=0, *is_cluster=False, *is_general=True), tsn=167, command_id=10, *is_reply=True)
[0x19CD:1:0x0000] Decoded ZCL frame: Basic:Report_Attributes(attribute_reports=[Attribute(attrid=0x0001, value=TypeValue(type=uint8_t, value=70)), Attribute(attrid=0xFFE2, value=TypeValue(type=uint8_t, value=54)), Attribute(attrid=0xFFE4, value=TypeValue(type=uint8_t, value=0))])
[0x19CD:1:0x0000] Received command 0x0A (TSN 167): Report_Attributes(attribute_reports=[Attribute(attrid=0x0001, value=TypeValue(type=uint8_t, value=70)), Attribute(attrid=0xFFE2, value=TypeValue(type=uint8_t, value=54)), Attribute(attrid=0xFFE4, value=TypeValue(type=uint8_t, value=0))])
[0x19CD:1:0x0000] Attribute report received: app_version=70, 0xFFE2=54, 0xFFE4=0
[0x19CD:1:0x0000] Sending reply header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.GLOBAL_COMMAND: 0>, is_manufacturer_specific=False, is_reply=1, disable_default_response=1, reserved=0, *is_cluster=False, *is_general=True), tsn=167, command_id=<GeneralCommand.Default_Response: 11>, *is_reply=True)
[0x19CD:1:0x0000] Sending reply: Default_Response(command_id=10, status=<Status.SUCCESS: 0>)
[0x84A5](lumi.sensor_magnet.aq2): Device seen - marking the device available and resetting counter
[0x84A5](lumi.sensor_magnet.aq2): Update device availability -  device available: True - new availability: True - changed: False
[0x1B15:1:0x0500]: Updated alarm state: 0
[0x1B15](lumi.sensor_motion.aq2): Device seen - marking the device available and resetting counter
[0x1B15](lumi.sensor_motion.aq2): Update device availability -  device available: True - new availability: True - changed: False
[0x19CD](TS0601): Attempting to checkin with device - missed checkins: 1
[0x19CD:1:0x0000] Sending request header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.GLOBAL_COMMAND: 0>, is_manufacturer_specific=False, is_reply=0, disable_default_response=0, reserved=0, *is_cluster=False, *is_general=True), tsn=22, command_id=<GeneralCommand.Read_Attributes: 0>, *is_reply=False)
[0x19CD:1:0x0000] Sending request: Read_Attributes(attribute_ids=[4])
[0x19CD:1:0x0000] Received ZCL frame: b'\x18\x16\x01\x04\x00\x00\x42\x10\x5F\x54\x5A\x45\x32\x30\x30\x5F\x39\x6D\x61\x68\x74\x71\x74\x67'
[0x19CD:1:0x0000] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.GLOBAL_COMMAND: 0>, is_manufacturer_specific=0, is_reply=1, disable_default_response=1, reserved=0, *is_cluster=False, *is_general=True), tsn=22, command_id=1, *is_reply=True)
[0x19CD:1:0x0000] Decoded ZCL frame: Basic:Read_Attributes_rsp(status_records=[ReadAttributeRecord(attrid=0x0004, status=<Status.SUCCESS: 0>, value=TypeValue(type=CharacterString, value='_TZE200_9mahtqtg'))])`

**Comment by w35l3y** [comment]
> "class": "zigpy.device.Device"

Your device was not paired with this quirk.
This quirk is supposed to be at 0.0.74+ and at HA core 2022.07.x

https://github.com/home-assistant/core/pull/72482

What version are you using?

**Comment by w35l3y** [comment]
@javicalle , my device doesn't have endpoint 242.
That is the reason why it is not in the PR.

This new one brought to us by @lleonardos has endpoint 242.

Both have the exact same manufacturer and model.

What do you recommend ?

**Comment by lleonardos** [comment]
I´m running the latest version as you can see below: so that is ruled out
´´´
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.8.7",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.5",
    "docker": true,
    "arch": "x86_64",
    "timezone": "America/Sao_Paulo",
    "os_name": "Linux",
    "os_version": "5.15.60",
    "supervisor": "2022.08.3",
    "host_os": "Home Assistant OS 8.5",
    "docker_version": "20.10.14",
    "chassis": "embedded",
    "run_as_root": true
  },´´´

**Comment by javicalle** [comment]
> What do you recommend ? Maybe TuyaSextupleSwitchTO_GP ?

This is the way 😉 

@lleonardos could you try to configure your local quirk with file `ts0601_switch.py` and add this class at the end of the file:
```python
class TuyaSextupleSwitchTO_GP(TuyaSwitch):
    """Tuya sextuple channel switch devices with GreenPowerProxy cluster and time on out cluster."""

    signature = {
        # <SimpleDescriptor endpoint=1 profile=260 device_type=81
        # input_clusters=[0x0000,0x0004,0x0005,0xEF00]
        # output_clusters=[0x000A,0x0019]>
        MODELS_INFO: [
            ("_TZE200_9mahtqtg", "TS0601"),
        ],
        ENDPOINTS: {
            1: {
                PROFILE_ID: zha.PROFILE_ID,
                DEVICE_TYPE: zha.DeviceType.SMART_PLUG,
                INPUT_CLUSTERS: [
                    Basic.cluster_id,
                    Groups.cluster_id,
                    Scenes.cluster_id,
                    TuyaOnOffManufCluster.cluster_id,
                ],
                OUTPUT_CLUSTERS: [Time.cluster_id, Ota.cluster_id],
            },
            # "profile_id": 41440,
            # "device_type": "0x0061",
            # "in_clusters": [],
            # "out_clusters": ["0x0021"]
            242: {
                PROFILE_ID: 41440,
                DEVICE_TYPE: 97,
                INPUT_CLUSTERS: [],
                OUTPUT_CLUSTERS: [GreenPowerProxy.cluster_id],
            },
        },
    }

    replacement = {
        ENDPOINTS: {
            1: {
                DEVICE_TYPE: zha.DeviceType.ON_OFF_LIGHT,
                INPUT_CLUSTERS: [
                    Basic.cluster_id,
                    Groups.cluster_id,
                    Scenes.cluster_id,
                    TuyaOnOffManufCluster,
                    TuyaOnOffNM,
                ],
                OUTPUT_CLUSTERS: [Time.cluster_id, Ota.cluster_id],
            },
            2: {
                PROFILE_ID: zha.PROFILE_ID,
                DEVICE_TYPE: zha.DeviceType.ON_OFF_LIGHT,
                INPUT_CLUSTERS: [
                    TuyaOnOffNM,
                ],
                OUTPUT_CLUSTERS: [],
            },
            3: {
                PROFILE_ID: zha.PROFILE_ID,
                DEVICE_TYPE: zha.DeviceType.ON_OFF_LIGHT,
                INPUT_CLUSTERS: [
                    TuyaOnOffNM,
                ],
                OUTPUT_CLUSTERS: [],
            },
            4: {
                PROFILE_ID: zha.PROFILE_ID,
                DEVICE_TYPE: zha.DeviceType.ON_OFF_LIGHT,
                INPUT_CLUSTERS: [
                    TuyaOnOffNM,
                ],
                OUTPUT_CLUSTERS: [],
            },
            5: {
                PROFILE_ID: zha.PROFILE_ID,
                DEVICE_TYPE: zha.DeviceType.ON_OFF_LIGHT,
                INPUT_CLUSTERS: [
                    TuyaOnOffNM,
                ],
                OUTPUT_CLUSTERS: [],
            },
            6: {
                PROFILE_ID: zha.PROFILE_ID,
                DEVICE_TYPE: zha.DeviceType.ON_OFF_LIGHT,
                INPUT_CLUSTERS: [
                    TuyaOnOffNM,
                ],
                OUTPUT_CLUSTERS: [],
            },
            242: {
                PROFILE_ID: 41440,
                DEVICE_TYPE: 97,
                INPUT_CLUSTERS: [],
                OUTPUT_CLUSTERS: [GreenPowerProxy.cluster_id],
            },
        }
    }
```

Reference:
* https://github.com/zigpy/zha-device-handlers/blob/dev/zhaquirks/tuya/ts0601_switch.py

**Comment by w35l3y** [comment]
> This is the way 😉

I have already created PR #1719

**Pull request merged**
