### PR TITLE
Add support for saswell sea801-z01

### PR DESCRIPTION
**Pull request by ha-zig**
This device "_TZE200_c88teujp", "TS0601" was classified under MoesHY368 quirk wrongly, as the attributes are different. Added new classes for saswell, Note device does not report whether valve is open or closed, similar to other Tuya battery reporting is good or bad no in between. Also not nasty hack of SASWELL_STATE_ATTR and SASWELL_MODE_ATTR to same value to get buttons working on HA thermostat interface. Basic functionallity added here, turn on device to manual, off to off you can also set temperature setpoint, device also reports room temperature. More to add here later, possible to set to auto mode and remotely programme the schedule.

### CODE REVIEW

**Comment by Adminiuga** [comment]
@ha-zig can you post your device signature for posterity here?

@fastcolors seems like you've added the same model in #710 Do we have two different devices with the exactly same model/manufacturer or does this new PR works good with your device?

**Comment by ha-zig** [comment]
@fastcolors that patch does not work for me on, debug shows different attribs, device sig:

{
  "node_descriptor": "NodeDescriptor(byte1=2, byte2=64, mac_capability_flags=128, manufacturer_code=4098, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=0)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0301",
      "in_clusters": [
        "0x0000",
        "0x0001",
        "0x0004",
        "0x0005",
        "0x0201",
        "0x0204",
        "0xef00"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    }
  },
  "manufacturer": "_TZE200_c88teujp",
  "model": "TS0601",
  "class": "zhaquirks.tuya.valve.SaswellSEA801"
}

example of valve

https://www.aliexpress.com/item/1005001774162057.html

changes work for me for basic functionality, device is slow to send updates after mode change (it will change straight away but wont send the mode change back often for upto a minute)

**Comment by MattWestb** [comment]
The timing problem you can very likely fixing with this: https://github.com/zigpy/zha-device-handlers/pull/726#issuecomment-767589485 and the comment a above it.

**Comment by MattWestb** [comment]
@Adminiuga I have trying doing one matrix in the Wiki https://github.com/zigpy/zigpy/discussions/653#discussioncomment-314395 and its looks being OK then following the commits backwards. I think  its easier than having pictures for the user saying its right or not (some is working OK with wrong quirk and can throwing errors but working).

**Comment by Adminiuga** [comment]
Unless there are different models with the same model/manufacturer and two users report conflicting data.

**Comment by MattWestb** [comment]
@Adminiuga     **This is being one big MESS !!**

The MoesHY368 was working but luck of futures and being updated PR #726  is waiting and ("_TZE200_ckud7u2l", "TS0601"), is one true MoesHY368 and being moved to the "new MoesHY368" in the PR #726 .

("_TZE200_kfvq6avy", "TS0601"), Revolt NX-4911 II and ("_TZE200_zivfvd7h", "TS0601"), Siterwell GS361A II was in the MoesHY368 because new zigbee module and was working but cant being moved to the "new MoesHY368" then its dont have all the extras the new inplanting so its being renamed in the same PR to Siterwell  II in the PR and the "old MoesHY368" away PR #726 .
This devises looks working but can complaining of time setting is not working.

("_TZE200_c88teujp", "TS0601"), Saswell SEA801 1 was also in the MoesHY368 but was working 
bad PR #710 . 
One new PR #751 is made and shall moving the fingerprint from the "old MoesHY368".

I have verified all IDs with deCONZ and Z2M and also with photos of devices that is verified by users having the devices.

Sorry for all the problems but then the "descrambling" is made all shall being in the right place.
That is missing is updating the original Siterwell that only having basic functions (not urgent but need being done).

And its also one or 2 uncommon models that i shall putting in the matrix with picture and information of providing issues for adding them **with device signature** that was the large problem then users have adding them without no information at all in the PRs (#710).

Mvh  Mattias

**Comment by dmulcahey** [comment]
Needs a rebase

**Comment by ha-zig** [comment]
#576`removes need for this

**Pull request closed without merging**
