### PR TITLE
Add Quirk For Konke Contact Sensor - Battery

### PR DESCRIPTION
**Pull request by tube0013**
Added a new quirk for the Konke 3AFE270104020015 contact sensor so it can report battery percentage in HA. Tested and working with sensor I just received recently. Is there any way to set the battery size via quirk - temp sensor also shows unknown for battery size? (Its a 3v CR1632 for the sensor.)

Screen Shot 2020-05-25 at 11 39 22 PM

### CODE REVIEW

**Comment by Adminiuga** [comment]
Can you black format the `zha-device-handlers/zhaquirks/konke/magnet.py` ?

**Comment by tube0013** [comment]
I did this locally and added the change in my fork but not sure how to push that over here. I'm not at all versed in git and fiddle my way through.

**Comment by Adminiuga** [comment]
ok. a few tips:
When fixing something or working on a new feature, do it on a separate branch, not the dev branch of your clone, that would save some pain of keeping your clone up-to-date with upstream changes

to create branch:
1. `git checkout -b fix/my-fix-1`  -- this would create a new branch, based on your current branch. It is a good idea to be on the `dev` branch with the latest updates. i.e `git checkout dev; git fetch upstream-remote-name; git pull upstream-remote-name`
2. commit your changes
3. push your changes to your clone on GH and create the PR

https://xkcd.com/1597/

**Comment by tube0013** [comment]
Okay I think I was mostly there and had to just merge my branch changes in my fork.  seeme to have showed up here. lol

**Comment by Adminiuga** [comment]
yeah, my black reformats it the same, not sure why flake is complaining.

**Comment by Adminiuga** [comment]
if you add space after the comma, then black would complain about reformatting again. I think I had a similar problem, don't remember how i fixed it

**Comment by Adminiuga** [comment]
hold on a sec, gonna remove those commas

**Pull request merged**
