### PR TITLE
Fix `manufacturer` type for `TuyaClusterData`

### PR DESCRIPTION
**Pull request by javicalle**
Fix for the `TuyaClusterData` the `manufacturer` type.

### CODE REVIEW

**Comment by javicalle** [comment]
Required change for make work `manufacturer=foundation.ZCLHeader.NO_MANUFACTURER_ID`

**Comment by puddly** [comment]
Can you add a unit test for this change?

**Comment by javicalle** [comment]
Ummmm, thanks for your suggestion but this change is only for the `TuyaClusterData` struct.
I can look to add tests for all the class attributes.

**Comment by javicalle** [comment]
@puddly test for manufacturer attribute added.
I'm not sure other tests would be valuable.

It's fine to you to continue with the version as is?

**Pull request merged**
