### PR TITLE
add support for bseed touch switches

### PR DESCRIPTION
**Pull request by Tropaion**
Added support for these touch switches: [Ali](https://de.aliexpress.com/item/1005002637772369.html?gatewayAdapt=glo2deu&spm=a2g0o.9042311.0.0.311f4c4dih8mRz)

Tested with single and double switch, I don't have triple switch to test.
Created issue about this: https://github.com/zigpy/zha-device-handlers/issues/1301#issuecomment-1020633355

We also discussed that these switches sometimes react very delayed or even not a bit, also zigbee groups don't work.
I'm not a professional in this but I don't think thats a problem with the quirk.

### CODE REVIEW

**Comment by Tropaion** [comment]
I don't know why it doesn't pass the isort check, maybe someone else can edit it

**Comment by MattWestb** [comment]
Isort like that  you to deleting line 18 - 27 
```
from zigpy.profiles import zha
from zigpy.zcl.clusters.general import (
    Basic,
    Groups,
    Identify,
    OnOff,
    Ota,
    Scenes,
    Time,
)
```
and add 
```
from zigpy.profiles import zha
from zigpy.zcl.clusters.general import Basic, Groups, Identify, OnOff, Ota, Scenes, Time
```
on line 2.

But after doing the change run the code in black then i think its like splitting the block.

**Comment by Tropaion** [comment]
@MattWestb Did as you said but failed again, also tried with https://pycqa.github.io/isort/docs/quick_start/0.-try.html

**Comment by MattWestb** [comment]
It was not going to well ;-((

Your first correction was 95% OK and only having one sorting issue https://github.com/zigpy/zha-device-handlers/runs/4929778994?check_suite_focus=true

Only need from `zigpy.zcl.clusters.general import Basic, Identify, Groups, OnOff, Ota, Scenes, Time` `to from zigpy.zcl.clusters.general import Basic, Groups, Identify, OnOff, Ota, Scenes, Time`

If you going back to commit 7e2f9d0 its easier fixing then multiple lines that is wrong from the moment.


Isort is trickey then HA is using custom parameters and is is needing some extra manual fixing for working OK.

**Comment by Tropaion** [comment]
I give up this isort shit -.- maybe some dev will add or not...

**Comment by MattWestb** [comment]
I have trying doing what isort is complaining of from your git and then running balck so its shall being OK (if i have doing the copy and past OK)
[ts000x.txt](https://github.com/zigpy/zha-device-handlers/files/7937434/ts000x.txt)
[ts001x.txt](https://github.com/zigpy/zha-device-handlers/files/7937435/ts001x.txt)
.Put it in your git and and making one pull of the changes and see if its happy or not.

**Comment by MattWestb** [comment]
### THATS dont looks so bad !!

Its only one copy past problem:
`"Warning: zhaquirks/tuya/ts001x.py:474:6: W292 no newline at end of file"`
Adding one new line in  the end off `ts001x.py` and all shall bing OK !!
If you like being on the safe side use black playground for fixing it https://black.vercel.app/.

**Comment by MattWestb** [comment]
Not so bad i have bigger problem getting the tests working Ok !!

### GREAT DONE !!

**Comment by Tropaion** [comment]
@MattWestb Haha, yeah finally...thanks :D

**Comment by MattWestb** [comment]
You was doing the coding and the testing and in the end it was working well !!!

I hope its can being added in the quirk for HA 2011-01 but i think its too late then the best is starting today i think.

**Pull request merged**
