### PR TITLE
[help wanted] Add quirks for tuya ts0601 touch devices

### PR DESCRIPTION
**Pull request by delneet**
Adds quirks for Tuya TS0601 1,2,3,4-gang touch devices.
Only the first channel works for now.

- [ ] **Need help getting the other channels working**

The devices I use are branded as Somgoms.
Screenshot 2021-05-27 at 23 57 49

<details><summary>Home Assistant log</summary>
<p>
Excerpt.

Interesting parts I think are  
`channel: x` in `[zhaquirks.tuya] 5c:02:72:ff:fe:c2:01:d5 - Received switch event message, channel: 3, state: 0`

```
[zigpy_deconz.api] Command Command.aps_data_indication (1, 1)
[zigpy_deconz.api] APS data indication response: [33, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|2: 34>, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x0000>, 1, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x06e7>, 1, 260, 61184, b'\tH\x02\x04!\x03\x01\x00\x01\x00', 0, 175, 183, 172, 20, 61, 0, -71]
[zigpy.zcl] [0x06e7:1:0xef00] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=CLUSTER_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=72 command_id=2>
[zigpy.zcl] [0x06e7:1:0xef00] ZCL request 0x0002: [Command(status=4, tsn=33, command_id=259, function=0, data=[1, 0])]
[zhaquirks.tuya] 5c:02:72:ff:fe:c2:01:d5 - Received switch event message, channel: 3, state: 0
[zigpy_deconz.api] 'aps_data_indication' response from <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x06e7>, ep: 1, profile: 0x0104, cluster_id: 0xef00, data: b'09480204210301000100'
[zigpy_deconz.api] Device state changed response: [<DeviceState.128|APSDE_DATA_REQUEST_SLOTS_AVAILABLE|APSDE_DATA_INDICATION|2: 170>, 0]

[zigpy_deconz.api] Command Command.aps_data_indication (1, 1)
[zigpy_deconz.api] APS data indication response: [33, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|2: 34>, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x0000>, 1, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x06e7>, 1, 260, 61184, b'\tJ\x02\x04"\x04\x01\x00\x01\x01', 0, 175, 255, 191, 20, 61, 0, -61]
[zigpy.zcl] [0x06e7:1:0xef00] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=CLUSTER_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=74 command_id=2>
[zigpy.zcl] [0x06e7:1:0xef00] ZCL request 0x0002: [Command(status=4, tsn=34, command_id=260, function=0, data=[1, 1])]
[zhaquirks.tuya] 5c:02:72:ff:fe:c2:01:d5 - Received switch event message, channel: 4, state: 1
[zigpy_deconz.api] 'aps_data_indication' response from <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x06e7>, ep: 1, profile: 0x0104, cluster_id: 0xef00, data: b'094a0204220401000101'
[zigpy_deconz.api] Device state changed response: [<DeviceState.128|APSDE_DATA_REQUEST_SLOTS_AVAILABLE|APSDE_DATA_INDICATION|2: 170>, 0]

[zigpy_deconz.api] Command Command.aps_data_indication (1, 1)
[zigpy_deconz.api] APS data indication response: [33, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|2: 34>, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x0000>, 1, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x06e7>, 1, 260, 61184, b'\tK\x02\x04#\x04\x01\x00\x01\x00', 0, 175, 255, 191, 20, 61, 0, -62]
[zigpy.zcl] [0x06e7:1:0xef00] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=CLUSTER_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=75 command_id=2>
[zigpy.zcl] [0x06e7:1:0xef00] ZCL request 0x0002: [Command(status=4, tsn=35, command_id=260, function=0, data=[1, 0])]
[zhaquirks.tuya] 5c:02:72:ff:fe:c2:01:d5 - Received switch event message, channel: 4, state: 0
[zigpy_deconz.api] 'aps_data_indication' response from <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x06e7>, ep: 1, profile: 0x0104, cluster_id: 0xef00, data: b'094b0204230401000100'
[zigpy_deconz.api] Device state changed response: [<DeviceState.128|APSDE_DATA_REQUEST_SLOTS_AVAILABLE|APSDE_DATA_INDICATION|2: 170>, 0]
```
</p>
</details>

Relates to https://github.com/zigpy/zha-device-handlers/issues/716
Somehow fixed in z2mqtt / herdsman https://github.com/Koenkk/zigbee-herdsman-converters/pull/2137

<details><summary>Device signature for 4 gang switch</summary>

All devices only have 1 endpoint.
This is the initial signature:
```
{
  "node_descriptor": "NodeDescriptor(byte1=1, byte2=64, mac_capability_flags=142, manufacturer_code=4098, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=0, *allocate_address=True, *complex_descriptor_available=False, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False, *is_valid=True, *logical_type=<LogicalType.Router: 1>, *user_descriptor_available=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0100",
      "in_clusters": [
        "0x0000",
        "0x0004",
        "0x0005",
        "0xef00"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    }
  },
  "manufacturer": "_TZE200_aqnazj70",
  "model": "TS0601",
  "class": "device.Device"
}
```

This is the signature after adding the quirk:
```
{
  "node_descriptor": "NodeDescriptor(byte1=1, byte2=64, mac_capability_flags=142, manufacturer_code=4098, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=0, *allocate_address=True, *complex_descriptor_available=False, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False, *is_valid=True, *logical_type=<LogicalType.Router: 1>, *user_descriptor_available=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0100",
      "in_clusters": [
        "0x0000",
        "0x0004",
        "0x0005",
        "0x0006",
        "0xef00"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    }
  },
  "manufacturer": "_TZE200_aqnazj70",
  "model": "TS0601",
  "class": "zhaquirks.tuya.ts0601_touch_4gang.TuyaTouch4Gang"
}
```
</details>

### CODE REVIEW

**Comment by MattWestb** [comment]
Its 3 more PR for tuya switched with the same problem and need support for more then the first gang so i hope some device can helping implanting it in the quirk so we can adding it to our devices.

**Comment by MattWestb** [comment]
Its looks one user have getting one working code for multi gang switches working but having problem testing it on system with multiple devices in the network.
https://github.com/zigpy/zha-device-handlers/issues/1038
Test and implantation help is needed :-))

**Comment by delneet** [comment]
> Its looks one user have getting one working code for multi gang switches working but having problem testing it on system with multiple devices in the network. #1038 Test and implantation help is needed :-))

I have the ones pictured above, 1,2,3,4 gang and curtain switch.
But failing to get this to work I'm afraid I just switched to zigbee2mqtt 🙈 
Sry, also no time any time soon to test a zha setup again...

**Comment by javicalle** [comment]
Already implemented:
* PR # 1166

Closing.

**Pull request closed without merging**
