### PR TITLE
TRADFRI remote control - add fw support v24.4.5

### PR DESCRIPTION
**Pull request by stickpin**
TRADFRI remote control  - Add support for firmware v24.4.5

More details in this bug report: https://github.com/zigpy/zha-device-handlers/issues/2139

### CODE REVIEW

**Comment by MattWestb** [comment]
Thanks for the updated quirk i have the same done nut i have portable verifying that is working then the remote was not liking upgrading to the last OTA and after flashing it with the last good with group supported my ZHA with RCP firmware 4.1.4 and 4.2.0 dont like paring it so i must sniffing what is going wrong.

Device class naming i do not comments then its one question for the maintainers.

PS: is one risk that you need rebasing your PR then its one in the pipe for merger that is fixing some old DA and raking some unneeded things away.
https://github.com/zigpy/zha-device-handlers/pull/2123

**Comment by stickpin** [comment]
> Thanks for the updated quirk i have the same done nut i have portable verifying that is working then the remote was not liking upgrading to the last OTA and after flashing it with the last good with group supported my ZHA with RCP firmware 4.1.4 and 4.2.0 dont like paring it so i must sniffing what is going wrong.
> 
> Device class naming i do not comments then its one question for the maintainers.
> 
> PS: is one risk that you need rebasing your PR then its one in the pipe for merger that is fixing some old DA and raking some unneeded things away. #2123

No problem, I will rebase it once it's merged.

There is still a problem with the battery reporting. It looks like IKEA changed measurement from percentage 0-100 to 0-255. Meaning that we need a convertor in the quirk for this now as well. I am new to quirks, so I will see what is the best way to implement the convertor.

**Comment by TheJulianJES** [comment]
Yeah, check the `PowerConfiguration1CRCluster` you're using.

ZCL requires 0—200 for battery and. Is it possible that IKEA uses those values? (Or where are you getting the 255?)

**Comment by stickpin** [comment]
> Yeah, check the `PowerConfiguration1CRCluster` you're using.
> 
> ZCL requires 0—200 for battery and. Is it possible that IKEA uses those correct values now? (Or where are you getting the 255?)

Yes, you are right. I've just changed to the new battery and checked the `PowerConfiguration1CRCluster`:
Should we just divide the value by 2?

**Comment by TheJulianJES** [comment]
0 to 200 should be what ZHA expects (and will divide that by 2 per ZCL spec).

So right now your quirk is overriding the `PowerConfiguration` cluster with the custom `PowerConfiguration1CRCluster`.
What happens if you also put `PowerConfiguration.cluster_id` in the replacement (instead of `PowerConfiguration1CRCluster`)?

**Comment by MattWestb** [comment]
All IKEA controller is reporting 100% then full and ZCL it shall being reported 200 for being full so all IKEA quirks is id dubeling the reported valiue.
Its looks like some Z2M user have reported that the new firmware is ZCL and dont need the doubling but i have not verifying that.

**Comment by stickpin** [comment]
@TheJulianJES, @MattWestb thanks a lot for the hint!
It worked!
Screenshot 2023-01-27 at 20 07 51
I've updated the quirk.

**Comment by TheJulianJES** [comment]
> Its looks like some Z2M user have reported that the new firmware is ZCL 

Also, the updated remote reports `zcl_version = 8` (ZCL revision 8), so IKEA finally used a way newer EmberZNet release to build this firmware and even used this for their older products. (yay)
(Hoping IKEA also does this for every other 2.x.x products. STARKVIND and other 1.x firmware products already report `zcl_version = 8`)

Weirdly for me, the remote didn't get the new signature after re-pairing. It *shouldn't* require me to delete the remote first though. (I'll look at this later)

**Comment by MattWestb** [comment]
I still fighting getting the old firmware on the Zigbee module also the very old ZLL 1.1.1 that i have "found".
In the end its looks Segger have changing there libs and silabs have updating then with the last SS5 updates and now its required having hardware reset for loading the CPU code and flashing MG1 device that was not needed before. So i must braking it more and souring cables then i cant hold 5 jumpers in place and start flashing with the other hand :-(((

Great that the quirk looks being in place so user can installing it  and using there devices !!!

**Comment by MattWestb** [comment]
Have getting the WSTK working after getting the PCB out and back with cables so can flashing it OK. The `TRADFRI-remote-control-1111` is not starting OK (one very old TLL firmware and very likely is the bootloader to new for it).
The last `TRADFRI-remote-control-2.3.080` was `Ember Version: 6.3.1.1` and the update is  `Ember Version: 6.10.2.0` = many battery draining bugs and network problems.
The `TRADFRI-motion-sensor-24.4.5` is also `Ember Version: 6.10.2.0` so its all great only that IKEA can have one small step to 6.10.3 but i cant complaining.

I trying OTA updating from 2.3.80 and its taking some time if its working OK.

The Starkvind OTA file is in GBL format and is not having any metadata for the compiling.
But in the release note:
- Release Version: 1.22.0 GA
  - 6th Sep 2022
    - STARKVIND Air Purifier (v1.1.001)
    - Upgrade to stack v6.10.2.

I think it can being one more problem with very old devices is having old bootloaders that making hard flashing 7.X firmware and 7.1 have dropping all Zigbee support for MG1 (first and second gen devices) devices but i being very happy with 6.10.X :-)))
I think the first gen need EBL files for the bootloader and second and 3 gen can using GBL files.
Also its possible updating the bootloader with OTA but Silbas is not recommending it then its not 100% sure its working OK and getting hardware bricking.

For third gen devices have not limit if have making all right.

**Comment by MattWestb** [comment]
I have testing and doing automatons from all DAs and they is working !!!

If some line doing more DAs its possible for dim up and down release:
```
up relese

  endpoint_id: 1
  cluster_id: 8
  command: stop_with_on_off
  args: []
  params: {}


down relese

  endpoint_id: 1
  cluster_id: 8
  command: stop
  args:
    - 0
    - 0
  params:
    options_mask: 0
    options_override: 0
```
is always the same and is unique = can being used for dim up / down released after long press.

Long release for left / right hold is also possible but little tricky is sending:
```
Left release:

  endpoint_id: 1
  cluster_id: 5
  command: release
  args:
    - 4112
  params:
    param1: 4112


Right release:

  endpoint_id: 1
  cluster_id: 5
  command: release
  args:
    - 3548
  params:
    param1: 3548
```
And the parm1 / arg is the time the button was hold. The problem is that 0 is being used for toggle long press / release but can filtering 0 away and it shall working.
Getting release from right left its possible using the same logic as Open / Close button that is saving the last direction and using it for next release.

Great work done !!

**Review by MattWestb — APPROVED** [review]
Also battery is working OK (10% after firmware up and downgrade many times ).

**Comment by MattWestb** [comment]
The reseal from hold dim up and down is one PR for adding in current devices so i think its good putting in here 2.
https://github.com/zigpy/zha-device-handlers/pull/2123/files

**Review by MattWestb — COMMENTED** [review]
Not one must but its easy adding the dim up and down release after hold.

**Comment by TheJulianJES** [comment]
Let's try and wait for https://github.com/zigpy/zha-device-handlers/pull/2123 first. Then, this can be rebased and hopefully just copy all device automation triggers.

**Comment by stickpin** [comment]
@MattWestb 
Screenshot 2023-01-31 at 09 33 54

**Comment by MattWestb** [comment]
Thanks then i think my remote have one older bootloader that making the OTA not being installed normal way.

**Pull request closed without merging**
