### PR TITLE
Add lights dimmer support for _TZE200_w4cryh2i

### PR DESCRIPTION
**Pull request by aistis-**
Closes https://github.com/zigpy/zha-device-handlers/issues/2125

### CODE REVIEW

**Comment by TheJulianJES** [comment]
Nice! Did you test that everything works as expected?

**Comment by aistis-** [comment]
Unfortunately, I did not test it. I am not sure how can I quickly alter code in my HA setup for a test. I assume it would work, because it is another variant of the device like `_TZE200_9i9dt8is`.

Let me know how I could run a test on my HA OS.

**Comment by TheJulianJES** [comment]
Search for "ZHA custom quirks" and/or check the wiki section on the zigpy repo.
You shouldn't need to alter any more code hopefully. Just copy the altered quirks file to your custom quirks folder (set in your configuration.yaml) and restart HA. Then see if the quirk applies.

**Comment by aistis-** [comment]
Thanks! Tested and it works 👍

**Review by TheJulianJES — APPROVED** [review]

**Review by javicalle — APPROVED** [review]
LGTM

**Pull request merged**
